// Bundle the Editor's built-in Google Fonts into the desktop app, so text looks right offline.
// Latin and Latin Extended only. Writes desktop/app/fonts/fonts.css and the .woff2 files it uses.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const io = fs.readFileSync(path.join(root, 'src/editor/io.ts'), 'utf8')
const m = io.match(/const FONT_SPECS: Record<string, string> = (\{[\s\S]*?\n\})/)
if (!m) { console.error('FONT_SPECS not found in src/editor/io.ts'); process.exit(1) }
const specs = new Function(`return ${m[1]}`)()
const dir = path.join(root, 'desktop', 'app', 'fonts')
fs.mkdirSync(dir, { recursive: true })

// A modern browser user agent, so Google serves woff2 split by subset.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'
const keep = new Set(['latin', 'latin-ext'])
let css = '/* Built-in fonts for offline use. Generated by desktop/scripts/fetch-fonts.mjs */\n'
let n = 0
for (const [family, spec] of Object.entries(specs)) {
  const url = `https://fonts.googleapis.com/css2?family=${family.replace(/ /g, '+')}${spec}&display=swap`
  const res = await fetch(url, { headers: { 'user-agent': UA } })
  if (!res.ok) { console.error(`Could not fetch ${family}: ${res.status}`); process.exit(1) }
  const text = await res.text()
  for (const block of text.split(/(?=\/\* [a-z-]+ \*\/)/)) {
    const subset = block.match(/^\/\* ([a-z-]+) \*\//)?.[1]
    if (!subset || !keep.has(subset)) continue
    let out = block
    for (const [, src] of block.matchAll(/url\((https:[^)]+\.woff2)\)/g)) {
      const name = `${family.replace(/ /g, '')}-${path.basename(new URL(src).pathname)}`
      const file = path.join(dir, name)
      if (!fs.existsSync(file)) {
        const r = await fetch(src); if (!r.ok) { console.error(`Could not fetch ${src}`); process.exit(1) }
        fs.writeFileSync(file, Buffer.from(await r.arrayBuffer())); n++
      }
      out = out.replace(src, `/fonts/${name}`)
    }
    css += out
  }
}
fs.writeFileSync(path.join(dir, 'fonts.css'), css)
console.log(`Bundled ${Object.keys(specs).length} font families (${n} files) into desktop/app/fonts`)
