// Everyday editing on desktop: duplicating, copy and paste, select all, nudging, lining up to a key object,
// rotating several layers, snapping, the right-click menu, editing a group on its own, appearance, number fields,
// spacing, the Layers panel, and no empty undo steps. Checks the design's rules after each part.
import { chromium } from 'playwright'
import { FIX } from './fixtures.mjs'
const BASE = process.env.BASE || 'http://localhost:3123'
const out = []; const ok = (n, c, i = '') => { out.push(`${c ? 'PASS' : 'FAIL'} ${n} ${i}`); if (!c) process.exitCode = 1 }
const b = await chromium.launch()
const errors = []
const E = (p, f, a) => p.evaluate(f, a)
const fresh = async (p, name = 'Editing') => { await E(p, n => { const s = window.__voidEditor.getState(); s.newDoc({ name: n, width: 1200, height: 900, background: '#ffffff' }); window.__voidEditor.getState().setTool('move') }, name); await p.waitForTimeout(200) }
const shape = (p, x, y, w = 120, h = 120, fill = '#ff0000', extra = {}) => E(p, ([x, y, w, h, fill, extra]) => window.__voidEditor.getState().addShape('rect', x, y, w, h, { fill, ...extra }), [x, y, w, h, fill, extra])
const check = p => E(p, () => window.__vcCheck())
const toScreen = (p, dx, dy) => E(p, ([dx, dy]) => { const s = window.__voidEditor.getState(); const r = document.querySelector('.touch-none.select-none').getBoundingClientRect(); const v = s.view; return { x: r.left + v.panX + dx * v.zoom, y: r.top + v.panY + dy * v.zoom } }, [dx, dy])
const L = (p, id) => E(p, id => { const l = window.__voidEditor.getState().layers.find(l => l.id === id); return l ? { x: l.x, y: l.y, w: l.w, h: l.h, sx: l.scaleX, sy: l.scaleY, r: l.rotation, name: l.name, fill: l.fill, stroke: l.stroke, opacity: l.opacity, groupId: l.groupId ?? null } : null }, id)
const hist = p => E(p, () => { const s = window.__voidEditor.getState(); return { n: s.historyIndex, label: s.history[s.historyIndex]?.label } })
const count = p => E(p, () => window.__voidEditor.getState().layers.length)
const select = (p, ids) => E(p, ids => { const s = window.__voidEditor.getState(); s.setActive(ids[0]); for (const id of ids.slice(1)) s.toggleSelect(id) }, ids)
const drag = async (p, from, to, steps = 10) => { await p.mouse.move(from.x, from.y); await p.mouse.down(); await p.mouse.move(to.x, to.y, { steps }); await p.mouse.up(); await p.waitForTimeout(120) }
const rulesHold = async (p, part) => { const r = await check(p); ok(`${part}: the design's rules hold`, r.length === 0, JSON.stringify(r)) }

const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, permissions: ['clipboard-read', 'clipboard-write'] })
const p = await ctx.newPage(); p.on('pageerror', e => errors.push(e.message)); p.on('dialog', d => d.accept())
await p.goto(`${BASE}/editor`); await p.waitForSelector('button:has-text("Open a photo")')
await (await p.$('input[type=file]')).setInputFiles(FIX.land); await p.waitForFunction(() => window.__voidEditor?.getState().layers.length > 0)

// ── Alt-drag copies; a plain Alt-click does not
await fresh(p, 'Alt drag')
let a = await shape(p, 200, 200)
await select(p, [a])
let h0 = await hist(p)
await p.keyboard.down('Alt'); await drag(p, await toScreen(p, 260, 260), await toScreen(p, 460, 260)); await p.keyboard.up('Alt')
ok('alt-drag: makes a copy', (await count(p)) === 2)
ok('alt-drag: the original stays where it was', (await L(p, a)).x === 200)
let copy = await E(p, () => window.__voidEditor.getState().activeId)
ok('alt-drag: the copy is where it was dropped', Math.abs((await L(p, copy)).x - 400) < 2, JSON.stringify(await L(p, copy)))
let h1 = await hist(p)
ok('alt-drag: one undo step', h1.n === h0.n + 1 && /Duplicate/.test(h1.label), JSON.stringify(h1))
await p.keyboard.press('Control+z'); await p.waitForTimeout(100)
ok('alt-drag: undo removes the copy', (await count(p)) === 1)
await select(p, [a]); h0 = await hist(p)
const ac = await toScreen(p, 260, 260)
await p.keyboard.down('Alt'); await p.mouse.click(ac.x, ac.y); await p.keyboard.up('Alt'); await p.waitForTimeout(150)
ok('alt-click: no copy and no undo step', (await count(p)) === 1 && (await hist(p)).n === h0.n)

// ── Ctrl+D repeats the last duplicate and move (step and repeat); with a pixel selection it deselects
await select(p, [a])
await p.keyboard.down('Alt'); await drag(p, await toScreen(p, 260, 260), await toScreen(p, 260, 410)); await p.keyboard.up('Alt')
await p.keyboard.press('Control+d'); await p.waitForTimeout(150)
const third = await E(p, () => window.__voidEditor.getState().active())
ok('ctrl+d: repeats the same step', (await count(p)) === 3 && Math.abs(third.y - 500) < 2, JSON.stringify({ y: third.y }))
await E(p, () => window.__voidEditor.getState().selectAll())
await p.keyboard.press('Control+d'); await p.waitForTimeout(100)
ok('ctrl+d: with a pixel selection it deselects', (await count(p)) === 3 && !(await E(p, () => !!window.__voidEditor.getState().selection)))
await rulesHold(p, 'duplicate')

// ── Ctrl+J duplicates beside; Ctrl+A and Ctrl+Alt+A select every layer
await fresh(p, 'Select all')
a = await shape(p, 100, 100); const b2 = await shape(p, 400, 100); const c3 = await shape(p, 700, 100)
await select(p, [a])
await p.keyboard.press('Control+j'); await p.waitForTimeout(100)
const jj = await E(p, () => window.__voidEditor.getState().active())
ok('ctrl+j: a copy 16 px down and right', (await count(p)) === 4 && jj.x === 116 && jj.y === 116, JSON.stringify({ x: jj.x, y: jj.y }))
await E(p, () => window.__voidEditor.getState().setActive(null))
await p.keyboard.press('Control+a'); await p.waitForTimeout(100)
ok('ctrl+a: with the Move tool selects every layer', (await E(p, () => window.__voidEditor.getState().selectedIds.length)) === 4 && !(await E(p, () => !!window.__voidEditor.getState().selection)))
await E(p, () => { const s = window.__voidEditor.getState(); s.setActive(null); s.setTool('marquee') })
await p.keyboard.press('Control+a'); await p.waitForTimeout(100)
ok('ctrl+a: with a selection tool selects every pixel', await E(p, () => !!window.__voidEditor.getState().selection))
await E(p, () => window.__voidEditor.getState().setSelection(null))
await p.keyboard.press('Control+Alt+a'); await p.waitForTimeout(100)
ok('ctrl+alt+a: selects every layer with any tool', (await E(p, () => window.__voidEditor.getState().selectedIds.length)) === 4)
await E(p, () => window.__voidEditor.getState().setTool('move'))

// ── Copy and paste layers: paste in view, paste in place, names
await select(p, [b2])
await p.keyboard.press('Control+c'); await p.waitForTimeout(400)
await p.keyboard.press('Control+Shift+v'); await p.waitForTimeout(300)
const pp = await E(p, () => window.__voidEditor.getState().active())
const names = await E(p, () => window.__voidEditor.getState().layers.map(l => l.name))
ok('paste in place: same spot, a name of its own', pp.x === 400 && pp.y === 100 && /^Rectangle \d+$/.test(pp.name) && names.filter(n => n === pp.name).length === 1, JSON.stringify({ x: pp.x, y: pp.y, name: pp.name }))
await rulesHold(p, 'paste')

// ── Nudging: presses in a row make one undo step; Shift nudges further; the step sizes are preferences
await select(p, [c3]); h0 = await hist(p)
for (let i = 0; i < 5; i++) await p.keyboard.press('ArrowRight')
await p.waitForTimeout(80)
ok('nudge: five presses move five pixels', (await L(p, c3)).x === 705)
ok('nudge: and make one undo step', (await hist(p)).n === h0.n + 1)
await p.keyboard.press('Shift+ArrowDown'); await p.waitForTimeout(50)
ok('nudge: Shift moves ten', (await L(p, c3)).y === 110)
await E(p, () => window.__voidUi.getState().setPref('nudge', 5))
await p.keyboard.press('ArrowLeft'); await p.waitForTimeout(50)
ok('nudge: follows the step size preference', (await L(p, c3)).x === 700)
await E(p, () => window.__voidUi.getState().setPref('nudge', 1))

// ── Key object: click a selected layer again and the others line up to it
await fresh(p, 'Key object')
const k1 = await shape(p, 100, 100, 100, 100), k2 = await shape(p, 400, 300, 200, 100)
await select(p, [k1, k2])
const kc = await toScreen(p, 500, 350)
await p.mouse.click(kc.x, kc.y); await p.waitForTimeout(150)
ok('key object: set by clicking a selected layer', (await E(p, () => window.__voidEditor.getState().keyObjectId)) === k2)
ok('key object: both stay selected', (await E(p, () => window.__voidEditor.getState().selectedIds.length)) === 2)
await E(p, () => window.__voidEditor.getState().align('left'))
ok('key object: align left moves the other layer, not the key object', (await L(p, k2)).x === 400 && (await L(p, k1)).x === 400)
await rulesHold(p, 'key object')

// ── Rotating several layers together with the round handle
await fresh(p, 'Rotate several')
const r1 = await shape(p, 300, 300, 100, 100), r2 = await shape(p, 600, 300, 100, 100)
await select(p, [r1, r2]); h0 = await hist(p)
const zoom = await E(p, () => window.__voidEditor.getState().view.zoom)
const rh = await toScreen(p, 500, 300 - 28 / zoom)
const rc = await toScreen(p, 500, 350)
await drag(p, rh, { x: rc.x + (rc.y - rh.y), y: rc.y }, 12)
const rr1 = await L(p, r1), rr2 = await L(p, r2)
ok('rotate several: both turn by the same angle', Math.abs(rr1.r - rr2.r) < 1e-6 && Math.abs(rr1.r) > 1, JSON.stringify([rr1.r, rr2.r]))
ok('rotate several: they turn around their shared centre', Math.abs((rr1.x + rr2.x) / 2 - 450) < 3, JSON.stringify([rr1.x, rr2.x]))
ok('rotate several: one undo step', (await hist(p)).n === h0.n + 1)
await rulesHold(p, 'rotate several')

// ── Snapping: to the page centre; Ctrl or Cmd turns it off for that drag
await fresh(p, 'Snap')
const sn = await shape(p, 100, 100, 100, 100)
await select(p, [sn])
await drag(p, await toScreen(p, 150, 150), await toScreen(p, 150 + 447, 150 + 200), 14)
ok('snap: the centre lands on the page centre', (await L(p, sn)).x === 550, JSON.stringify(await L(p, sn)))
await p.keyboard.down('Control'); await drag(p, await toScreen(p, 600, 350), await toScreen(p, 600 + 3, 350 + 50), 10); await p.keyboard.up('Control')
ok('snap: off while Ctrl is held', Math.abs((await L(p, sn)).x - 553) < 0.5, JSON.stringify(await L(p, sn)))
// Equal gaps between two neighbours
await fresh(p, 'Gaps')
const g1 = await shape(p, 100, 400, 100, 100), g3 = await shape(p, 600, 400, 100, 100), g2 = await shape(p, 330, 700, 100, 100)
await select(p, [g2])
await drag(p, await toScreen(p, 380, 750), await toScreen(p, 380 + 22, 450), 14)
const gl = await L(p, g2)
ok('snap: settles with equal space on both sides', Math.abs((gl.x - 200) - (600 - (gl.x + 100))) < 1, JSON.stringify(gl))

// ── Resize: Alt resizes from the centre; a click on a handle is not an undo step
await fresh(p, 'Resize')
const rz = await shape(p, 400, 300, 200, 100)
await select(p, [rz]); h0 = await hist(p)
const corner = await toScreen(p, 600, 400)
await p.mouse.click(corner.x, corner.y); await p.waitForTimeout(100)
ok('resize: clicking a handle adds no undo step', (await hist(p)).n === h0.n)
await p.keyboard.down('Alt'); await drag(p, corner, await toScreen(p, 650, 450)); await p.keyboard.up('Alt')
const rzl = await L(p, rz), rzw = rzl.w * rzl.sx, rzh = rzl.h * rzl.sy
ok('resize: Alt keeps the centre in place', Math.abs(rzl.x + rzw / 2 - 500) < 2 && Math.abs(rzl.y + rzh / 2 - 350) < 2 && rzw > 250, JSON.stringify({ x: rzl.x, y: rzl.y, rzw, rzh }))

// ── Right-click menu on the canvas
await fresh(p, 'Right click')
const m1 = await shape(p, 300, 300, 150, 150)
await E(p, () => window.__voidEditor.getState().setActive(null))
const mc = await toScreen(p, 370, 370)
await p.mouse.click(mc.x, mc.y, { button: 'right' }); await p.waitForTimeout(200)
ok('right click: selects the layer under the pointer', (await E(p, () => window.__voidEditor.getState().activeId)) === m1)
ok('right click: shows the layer menu', await p.locator('[data-canvas-menu] [role=menuitem]:has-text("Duplicate")').isVisible())
await p.locator('[data-canvas-menu] [role=menuitem]:has-text("Duplicate")').first().click(); await p.waitForTimeout(200)
ok('right click: Duplicate works from the menu', (await count(p)) === 2)
const empty = await toScreen(p, 1000, 800)
await p.mouse.click(empty.x, empty.y, { button: 'right' }); await p.waitForTimeout(200)
ok('right click: on an empty spot offers Paste', await p.locator('[data-canvas-menu] [role=menuitem]:has-text("Paste")').first().isVisible())
await p.keyboard.press('Escape'); await p.waitForTimeout(100)
ok('right click: Escape closes the menu', !(await p.locator('[data-canvas-menu]').count()))

// ── Groups: Escape goes up a level, Enter goes in, editing a group on its own
await fresh(p, 'Groups')
const i1 = await shape(p, 100, 100), i2 = await shape(p, 300, 100), out1 = await shape(p, 700, 500)
await select(p, [i1, i2]); await E(p, () => window.__voidEditor.getState().groupSelected())
const gid = (await L(p, i1)).groupId
await E(p, id => window.__voidEditor.getState().setActive(id), i1)
await p.keyboard.press('Escape'); await p.waitForTimeout(80)
ok('escape: from a layer up to its group', (await E(p, () => window.__voidEditor.getState().selectedIds.length)) === 2)
await p.keyboard.press('Enter'); await p.waitForTimeout(80)
ok('enter: from a group to its top layer', (await E(p, () => window.__voidEditor.getState().selectedIds)).join() === i2)
await E(p, g => window.__voidEditor.getState().setIsolated(g), gid); await p.waitForTimeout(150)
ok('on its own: the pill shows', await p.locator('[data-isolation-pill]').isVisible())
const oc = await toScreen(p, 760, 560)
await p.mouse.click(oc.x, oc.y); await p.waitForTimeout(120)
ok('on its own: layers outside the group cannot be picked', (await E(p, () => window.__voidEditor.getState().activeId)) !== out1)
const ic = await toScreen(p, 160, 160)
await p.mouse.click(ic.x, ic.y); await p.waitForTimeout(120)
ok('on its own: a click picks one layer inside, not the whole group', (await E(p, () => window.__voidEditor.getState().selectedIds)).join() === i1)
await p.keyboard.press('Escape'); await p.keyboard.press('Escape'); await p.waitForTimeout(120)
ok('on its own: Escape leaves it', !(await E(p, () => window.__voidEditor.getState().isolatedGroupId)))
await rulesHold(p, 'groups')

// ── Groups as objects: a click picks the whole group, a double click goes in, align moves groups whole
await fresh(p, 'Group objects')
const o1 = await shape(p, 100, 100, 100, 100), o2 = await shape(p, 250, 150, 100, 100), o3 = await shape(p, 700, 400, 100, 100)
await select(p, [o1, o2]); await E(p, () => window.__voidEditor.getState().groupSelected())
await E(p, () => window.__voidEditor.getState().setActive(null))
const oc1 = await toScreen(p, 150, 150)
await p.mouse.click(oc1.x, oc1.y); await p.waitForTimeout(120)
ok('group click: picks the whole group', (await E(p, () => window.__voidEditor.getState().selectedIds.length)) === 2)
await p.mouse.dblclick(oc1.x, oc1.y); await p.waitForTimeout(150)
ok('group double click: goes inside to the layer', (await E(p, () => window.__voidEditor.getState().selectedIds)).join() === o1)
const oc2 = await toScreen(p, 300, 200)
await p.mouse.click(oc2.x, oc2.y); await p.waitForTimeout(120)
ok('group: once inside, a click picks a sibling', (await E(p, () => window.__voidEditor.getState().selectedIds)).join() === o2)
await E(p, () => window.__voidEditor.getState().setActive(null))
await p.mouse.click(oc1.x, oc1.y); await p.keyboard.down('Shift'); const oc3 = await toScreen(p, 750, 450); await p.mouse.click(oc3.x, oc3.y); await p.keyboard.up('Shift'); await p.waitForTimeout(120)
await E(p, () => window.__voidEditor.getState().align('top'))
const ot = await Promise.all([o1, o2, o3].map(id => L(p, id)))
ok('align: a group moves as one and keeps its layout', ot[0].y === 100 && ot[1].y === 150 && ot[2].y === 100, JSON.stringify(ot.map(x => x.y)))
await E(p, () => window.__voidEditor.getState().setActive(null))
await p.mouse.click(oc1.x, oc1.y); await p.waitForTimeout(80)
await E(p, () => window.__voidEditor.getState().align('left'))
ok('align: one group on its own aligns to the page, whole', (await L(p, o1)).x === 0 && (await L(p, o2)).x === 150)
await rulesHold(p, 'group objects')

// Nested groups: each double click goes one level further in
await fresh(p, 'Nested')
const n1 = await shape(p, 100, 100), n2 = await shape(p, 300, 100), n3 = await shape(p, 500, 100)
await select(p, [n1, n2]); await E(p, () => window.__voidEditor.getState().groupSelected())
await select(p, [n1, n2, n3]); await E(p, () => window.__voidEditor.getState().groupSelected())
await E(p, () => window.__voidEditor.getState().setActive(null))
const nc = await toScreen(p, 160, 160)
await p.mouse.click(nc.x, nc.y); await p.waitForTimeout(100)
ok('nested: a click picks the outer group', (await E(p, () => window.__voidEditor.getState().selectedIds.length)) === 3)
await p.mouse.dblclick(nc.x, nc.y); await p.waitForTimeout(150)
ok('nested: a double click picks the inner group', (await E(p, () => window.__voidEditor.getState().selectedIds.length)) === 2)
await p.mouse.dblclick(nc.x, nc.y); await p.waitForTimeout(150)
ok('nested: another double click picks the layer', (await E(p, () => window.__voidEditor.getState().selectedIds)).join() === n1)
await p.keyboard.press('Escape'); await p.waitForTimeout(60)
ok('nested: Escape goes back up to the inner group', (await E(p, () => window.__voidEditor.getState().selectedIds.length)) === 2)
await rulesHold(p, 'nested')

// ── Turning around a corner
await fresh(p, 'Pivot')
const pv = await shape(p, 400, 300, 200, 100)
await E(p, id => window.__voidEditor.getState().setActive(id), pv); await p.waitForTimeout(150)
const pos0 = p.locator('[data-section="Position"]')
if (!(await pos0.locator('input[aria-label="Rotation in degrees"]').count())) await pos0.locator('button:has-text("Position")').click()
await pos0.locator('button[aria-label="Turn around the top left corner"]').click()
const rf = pos0.locator('input[aria-label="Rotation in degrees"]')
await rf.click(); await rf.fill('90'); await rf.press('Enter'); await p.waitForTimeout(100)
const tlc = await E(p, id => { const s = window.__voidEditor.getState(); const l = s.layers.find(l => l.id === id); const w = l.w * l.scaleX, h = l.h * l.scaleY; const cx = l.x + w / 2, cy = l.y + h / 2; const c = Math.cos(l.rotation), sn = Math.sin(l.rotation); return { x: cx + (-w / 2) * c - (-h / 2) * sn, y: cy + (-w / 2) * sn + (-h / 2) * c } }, pv)
ok('pivot: the top left corner stays put', Math.abs(tlc.x - 400) < 0.5 && Math.abs(tlc.y - 300) < 0.5, JSON.stringify(tlc))
await pos0.locator('button[aria-label="Turn around the centre"]').click()

// ── Combinations from the brief
await fresh(p, 'Combinations')
// Select, move, undo
const cb1 = await shape(p, 100, 100)
await drag(p, await toScreen(p, 150, 150), await toScreen(p, 400, 180))
await p.keyboard.press('Control+z'); await p.waitForTimeout(80)
ok('select, move, undo: back where it was', (await L(p, cb1)).x === 100 && (await L(p, cb1)).y === 100)
// Group, effect, ungroup
const cb2 = await shape(p, 300, 100)
await select(p, [cb1, cb2]); await p.keyboard.press('Control+g'); await p.waitForTimeout(60)
await E(p, () => window.__voidEditor.getState().addAdjustment('blur')); await p.waitForTimeout(100)
await select(p, [cb1]); await p.keyboard.press('Control+Shift+g'); await p.waitForTimeout(80)
const preservedGroupEffects = await E(p, ids => {
  const s = window.__voidEditor.getState()
  return ids.every(id => s.layers.find(l => l.id === id)?.effects?.some(e => e.kind === 'blur'))
}, [cb1, cb2])
ok('group, effect, ungroup: both layers retain their targeted blur', (await count(p)) === 2 && !(await L(p, cb1)).groupId && preservedGroupEffects)
await rulesHold(p, 'group, effect, ungroup')
// Duplicate, transform, duplicate again
await select(p, [cb2])
await p.keyboard.press('Control+j'); await p.waitForTimeout(60)
const dj = await E(p, () => window.__voidEditor.getState().activeId)
await E(p, id => { const s = window.__voidEditor.getState(); s.updateLayer(id, { rotation: Math.PI / 6 }); s.commit('Rotate') }, dj)
await p.keyboard.press('Control+j'); await p.waitForTimeout(60)
const dj2 = await E(p, () => window.__voidEditor.getState().active())
ok('duplicate, transform, duplicate: the second copy keeps the turn', Math.abs(dj2.rotation - Math.PI / 6) < 1e-6 && dj2.id !== dj)
// Copy, paste, paste again
await select(p, [cb1]); await p.keyboard.press('Control+c'); await p.waitForTimeout(300)
const n0 = await count(p)
const before = await E(p, () => window.__voidEditor.getState().layers.map(l => l.id))
await p.keyboard.press('Control+v'); await p.waitForTimeout(250); await p.keyboard.press('Control+v'); await p.waitForTimeout(250)
const all = await E(p, () => window.__voidEditor.getState().layers.map(l => ({ id: l.id, name: l.name })))
const added = all.filter(l => !before.includes(l.id)).map(l => l.name)
ok('copy, paste, paste: two copies with names of their own', (await count(p)) === n0 + 2 && new Set(added).size === 2 && added.every(n => all.filter(l => l.name === n).length === 1), added.join())
// Lock, then try to move
await select(p, [cb1]); await E(p, id => { const s = window.__voidEditor.getState(); s.updateLayer(id, { locked: true }, 'Lock') }, cb1)
await E(p, id => window.__voidEditor.getState().setActive(id), cb1)
await p.keyboard.press('ArrowRight'); await p.waitForTimeout(50)
const lc = await toScreen(p, 150, 150)
await drag(p, lc, { x: lc.x + 120, y: lc.y })
ok('lock, then move: the layer stays', (await L(p, cb1)).x === 100)
// Export straight after an edit, then undo
await E(p, id => { const s = window.__voidEditor.getState(); s.updateLayer(id, { fill: '#123456' }); s.commit('Fill') }, cb2)
await E(p, () => window.dispatchEvent(new CustomEvent('vc:open', { detail: 'export' }))); await p.waitForTimeout(900)
const [dl] = await Promise.all([p.waitForEvent('download'), p.click('button:has-text("Download")')])
ok('export after an edit: downloads a file', !!dl.suggestedFilename())
await p.keyboard.press('Escape'); await p.waitForTimeout(200)
ok('export after an edit: the file has the edit', await E(p, id => window.__voidEditor.getState().layers.find(l => l.id === id).fill === '#123456', cb2))
await p.keyboard.press('Control+z'); await p.waitForTimeout(80)
ok('undo after export: still works', (await L(p, cb2)).fill !== '#123456')
await rulesHold(p, 'combinations')

// ── Appearance and select same
await fresh(p, 'Appearance')
const ap1 = await shape(p, 100, 100, 100, 100, '#00ff00', { stroke: '#000000', strokeWidth: 4 }), ap2 = await shape(p, 300, 100, 100, 100, '#0000ff'), ap3 = await shape(p, 500, 100, 100, 100, '#00ff00')
const run = (id) => E(p, id => window.__vcRun?.(id), id)
{
  await select(p, [ap1]); await run('style.copyAppearance')
  await select(p, [ap2]); await run('style.pasteAppearance'); await p.waitForTimeout(80)
  const ap = await L(p, ap2)
  ok('appearance: fill and outline copied', ap.fill === '#00ff00' && ap.stroke === '#000000', JSON.stringify(ap))
  ok('appearance: size and place kept', ap.x === 300 && ap.w === 100)
  await select(p, [ap3]); await run('sel.sameFill'); await p.waitForTimeout(80)
  ok('select same fill: finds all three green layers', (await E(p, () => window.__voidEditor.getState().selectedIds.length)) === 3)
}
await rulesHold(p, 'appearance')

// ── Number fields: maths, board-relative positions, rotation, keep proportions, several layers
await fresh(p, 'Fields')
await E(p, () => { const s = window.__voidEditor.getState(); s.addFrame({ name: 'A', width: 600, height: 600 }); s.addFrame({ name: 'B', width: 600, height: 600 }) })
const fb = await E(p, () => window.__voidEditor.getState().doc.frames.map(f => ({ id: f.id, x: f.x, y: f.y })))
await E(p, id => window.__voidEditor.getState().setActiveFrame(id), fb[1].id)
const nf = await shape(p, fb[1].x + 50, fb[1].y + 60, 100, 80)
await E(p, id => window.__voidEditor.getState().setActive(id), nf); await p.waitForTimeout(150)
const pos = p.locator('[data-section="Position"]')
if (!(await pos.locator('input[aria-label^="X"]').count())) await pos.locator('button:has-text("Position")').click()
const fx = pos.locator('input[aria-label^="X"]')
ok('fields: X is measured from the board', (await fx.inputValue()) === '50', await fx.inputValue())
await fx.click(); await fx.fill('+10'); await fx.press('Enter'); await p.waitForTimeout(100)
ok('fields: "+10" moves ten pixels', (await L(p, nf)).x === fb[1].x + 60)
const fw = pos.locator('input[aria-label="Width"]')
await fw.click(); await fw.fill('*2'); await fw.press('Enter'); await p.waitForTimeout(100)
let nl = await L(p, nf)
ok('fields: "*2" doubles the width', Math.round(nl.w * nl.sx) === 200 && Math.round(nl.h * nl.sy) === 80)
await pos.locator('button[aria-label^="Width and height change"]').click()
await fw.click(); await fw.fill('100'); await fw.press('Enter'); await p.waitForTimeout(100)
nl = await L(p, nf)
ok('fields: keeping proportions changes the height too', Math.round(nl.w * nl.sx) === 100 && Math.round(nl.h * nl.sy) === 40, JSON.stringify(nl))
await pos.locator('button[aria-label^="Width and height change"]').click()
const fr = pos.locator('input[aria-label="Rotation in degrees"]')
await fr.click(); await fr.fill('45'); await fr.press('Enter'); await p.waitForTimeout(100)
ok('fields: rotation in degrees', Math.abs((await L(p, nf)).r - Math.PI / 4) < 1e-3)
h0 = await hist(p)
await fx.click(); await fx.press('Escape'); await p.waitForTimeout(50)
await fx.click(); await fx.press('Tab'); await p.waitForTimeout(50)
ok('fields: leaving a field unchanged adds no undo step', (await hist(p)).n === h0.n)
await fx.click(); await fx.fill('abc'); await fx.press('Enter'); await p.waitForTimeout(50)
ok('fields: nonsense keeps the value', (await hist(p)).n === h0.n)
// Several layers
const nf2 = await shape(p, fb[1].x + 300, fb[1].y + 300, 100, 100, '#00ff00', { opacity: 0.5 })
await select(p, [nf, nf2]); await p.waitForTimeout(150)
ok('several: opacity shows Mixed', await p.locator('[data-section="Layer"]:has-text("Mixed")').first().isVisible())
await p.locator('[data-section="Layer"] select').first().selectOption('multiply'); await p.waitForTimeout(80)
ok('several: blend mode set on both', await E(p, ids => ids.every(id => window.__voidEditor.getState().layers.find(l => l.id === id).blend === 'multiply'), [nf, nf2]))
await rulesHold(p, 'fields')

// ── Spacing: equal gaps, and a typed gap
await fresh(p, 'Spacing')
const s1 = await shape(p, 100, 100, 100, 100), s2 = await shape(p, 260, 100, 100, 100), s3 = await shape(p, 700, 100, 100, 100)
await select(p, [s1, s2, s3]); await p.waitForTimeout(150)
const gapH = p.locator('input[aria-label="Space between them, across"]')
await gapH.click(); await gapH.fill('20'); await gapH.press('Enter'); await p.waitForTimeout(100)
const sx = await Promise.all([s1, s2, s3].map(id => L(p, id)))
ok('spacing: a typed gap of 20', sx[1].x === 220 && sx[2].x === 340, JSON.stringify(sx.map(x => x.x)))
await rulesHold(p, 'spacing')

// ── Layers panel: Escape cancels a rename, several rows move together, move into a group
await fresh(p, 'Panel')
const q1 = await shape(p, 100, 100), q2 = await shape(p, 300, 100), q3 = await shape(p, 500, 100), q4 = await shape(p, 700, 100)
await E(p, id => window.dispatchEvent(new CustomEvent('vc:rename', { detail: id })), q1); await p.waitForTimeout(100)
const ren = p.locator('[role=listbox][aria-label=Layers] input').first()
await ren.fill('Changed my mind'); await ren.press('Escape'); await p.waitForTimeout(80)
ok('rename: Escape keeps the old name', (await L(p, q1)).name === 'Rectangle')
await E(p, id => window.dispatchEvent(new CustomEvent('vc:rename', { detail: id })), q1); await p.waitForTimeout(100)
await p.locator('[role=listbox][aria-label=Layers] input').first().fill('Logo'); await p.keyboard.press('Enter'); await p.waitForTimeout(80)
ok('rename: Enter keeps the new name', (await L(p, q1)).name === 'Logo')
await E(p, ([a, b]) => { const s = window.__voidEditor.getState(); s.setActive(a); s.toggleSelect(b); s.moveLayers([a, b], 3) }, [q1, q2])
ok('several rows: move together to the top', (await E(p, () => window.__voidEditor.getState().layers.map(l => l.id))).join() === [q3, q4, q1, q2].join())
await select(p, [q3, q4]); await E(p, () => window.__voidEditor.getState().groupSelected())
const qg = (await L(p, q3)).groupId
await E(p, ([id, g]) => window.__voidEditor.getState().moveToGroup([id], g), [q1, qg])
ok('move into group: joins it', (await L(p, q1)).groupId === qg)
await E(p, id => window.__voidEditor.getState().moveToGroup([id], null), q1)
ok('move out of group: leaves it', (await L(p, q1)).groupId === null)
await rulesHold(p, 'layers panel')

// ── No empty undo steps: a slider click, a text box opened and closed
await fresh(p, 'Quiet')
await E(p, () => { const s = window.__voidEditor.getState(); s.addText(300, 300); window.__voidEditor.setState({ editingTextId: null }); const t = window.__voidEditor.getState().active(); s.updateLayer(t.id, { text: 'Hello' }, 'Edit text') })
const tid = await E(p, () => window.__voidEditor.getState().activeId)
h0 = await hist(p)
await E(p, id => window.__voidEditor.setState({ editingTextId: id }), tid); await p.waitForTimeout(150)
await p.keyboard.press('Escape'); await p.waitForTimeout(150)
ok('text: opening and closing without typing adds no undo step', (await hist(p)).n === h0.n, JSON.stringify([h0, await hist(p)]))

// ── Pasting plain text makes a text layer
await p.evaluate(() => { const dt = new DataTransfer(); dt.setData('text/plain', 'Summer sale\nThis weekend'); window.dispatchEvent(new ClipboardEvent('paste', { clipboardData: dt })) }); await p.waitForTimeout(200)
const pt = await E(p, () => { const l = window.__voidEditor.getState().active(); return { type: l.type, text: l.text, name: l.name } })
ok('paste text: becomes a text layer', pt.type === 'text' && pt.text === 'Summer sale\nThis weekend' && pt.name === 'Summer sale', JSON.stringify(pt))
{
// ── Text grows from where it is aligned (2 Oct)
await fresh(p, 'Text anchor')
const anchor = async (patch, change) => E(p, ([patch, change]) => {
  const s = window.__voidEditor.getState(); s.addText(300, 300); window.__voidEditor.setState({ editingTextId: null })
  const id = window.__voidEditor.getState().activeId
  window.__voidEditor.getState().updateLayer(id, { text: 'Night', fontSize: 80, ...patch }, 'Set up')
  const before = window.__voidEditor.getState().layers.find(x => x.id === id)
  window.__voidEditor.getState().updateLayer(id, change, 'Change')
  const after = window.__voidEditor.getState().layers.find(x => x.id === id)
  return { before: { x: before.x, y: before.y }, after: { x: after.x, y: after.y }, id }
}, [patch, change])
const al = await anchor({ align: 'left' }, { text: 'Night session' })
ok('text anchor: left-aligned text keeps its left edge', Math.abs(al.after.x - al.before.x) < 0.01 && Math.abs(al.after.y - al.before.y) < 0.01, JSON.stringify(al))
const ac = await anchor({ align: 'center' }, { text: 'Night session' })
ok('text anchor: centred text grows both ways from its middle', ac.after.x < ac.before.x - 40 && Math.abs(ac.after.y - ac.before.y) < 0.01, JSON.stringify(ac))
const ar = await anchor({ align: 'right' }, { fontSize: 120 })
ok('text anchor: right-aligned text grows to the left when its size goes up', ar.after.x < ar.before.x - 40 && Math.abs(ar.after.y - ar.before.y) < 0.01, JSON.stringify(ar))
await E(p, id => { const s = window.__voidEditor.getState(); s.updateLayer(id, { text: 'Night session, late', x: 10 }, 'Both'); return s.layers.find(x => x.id === id) ?? window.__voidEditor.getState().layers.find(x => x.id === id) }, ac.id)
ok('text anchor: a change that places the text itself is left alone', (await E(p, id => window.__voidEditor.getState().layers.find(x => x.id === id).x, ac.id)) === 10)
// Turned text keeps its anchor too (it used to drift as it grew).
const rot = await E(p, () => {
  const s = window.__voidEditor.getState(); s.addText(500, 400); window.__voidEditor.setState({ editingTextId: null }); const id = window.__voidEditor.getState().activeId
  s.updateLayer(id, { text: 'Turn', fontSize: 60, rotation: Math.PI / 4, align: 'left' }, 'Set up')
  const corner = () => { const l = window.__voidEditor.getState().layers.find(x => x.id === id); const w = window.__vcLayerSize(l); const cx = l.x + w.w / 2, cy = l.y + w.h / 2, c = Math.cos(l.rotation), sn = Math.sin(l.rotation); const dx = -w.w / 2, dy = -w.h / 2; return { x: cx + dx * c - dy * sn, y: cy + dx * sn + dy * c } }
  const a = corner(); s.updateLayer(id, { text: 'Turn it round' }, 'Type'); const b2 = corner()
  return { a, b: b2 }
})
ok('text anchor: turned text keeps its top-left corner as it grows', Math.abs(rot.a.x - rot.b.x) < 0.6 && Math.abs(rot.a.y - rot.b.y) < 0.6, JSON.stringify(rot))
await rulesHold(p, 'text anchor')

// ── Sizes in print units (2 Oct)
await fresh(p, 'Units')
await E(p, () => window.dispatchEvent(new CustomEvent('vc:open', { detail: 'canvasSize' }))); await p.waitForSelector('[role=dialog]:has-text("Canvas size")')
await p.selectOption('[role=dialog] select[aria-label="Units"]', 'mm')
await p.fill('[role=dialog] input[aria-label="Resolution"]', '300')
await p.fill('[role=dialog] input[aria-label="Width"]', '210'); await p.fill('[role=dialog] input[aria-label="Height"]', '297')
ok('units: millimetres turn into pixels at the resolution', /2480 × 3508 px at 300 dpi/.test(await p.textContent('[role=dialog] [data-size-px]')), await p.textContent('[role=dialog] [data-size-px]'))
await p.fill('[role=dialog] input[aria-label="Width"]', '21.'); ok('units: a decimal point can be typed', (await p.inputValue('[role=dialog] input[aria-label="Width"]')) === '21.')
await p.fill('[role=dialog] input[aria-label="Width"]', '210')
await p.click('[role=dialog] button:has-text("Apply")'); await p.waitForTimeout(300)
const du = await E(p, () => { const d = window.__voidEditor.getState().doc; return { w: d.width, h: d.height, dpi: d.dpi } })
ok('units: the canvas is A4 at 300 dpi', du.w === 2480 && du.h === 3508 && du.dpi === 300, JSON.stringify(du))
await E(p, () => window.dispatchEvent(new CustomEvent('vc:open', { detail: 'imageSize' }))); await p.waitForSelector('[role=dialog]:has-text("Image size")')
ok('units: Image size remembers the unit and shows the size in it', (await p.inputValue('[role=dialog] select[aria-label="Units"]')) === 'mm' && (await p.inputValue('[role=dialog] input[aria-label="Width"]')) === '210', await p.inputValue('[role=dialog] input[aria-label="Width"]'))
await p.keyboard.press('Escape'); await p.waitForTimeout(200)
await E(p, () => window.__voidEditor.getState().closeDoc()); await p.waitForTimeout(600)
await p.selectOption('[data-custom-size] select[aria-label="Units"]', 'cm')
await p.fill('[data-custom-size] input[aria-label="Width (cm)"]', '10'); await p.fill('[data-custom-size] input[aria-label="Height (cm)"]', '15')
ok('units: a custom size in centimetres', /1181 × 1772 px at 300 dpi/.test(await p.textContent('[data-size-px]')), await p.textContent('[data-size-px]'))
await p.click('[data-custom-size] button:has-text("Create design")'); await p.waitForTimeout(500)
const dn = await E(p, () => { const d = window.__voidEditor.getState().doc; return { w: d.width, h: d.height, dpi: d.dpi } })
ok('units: the new design has that size and resolution', dn.w === 1181 && dn.h === 1772 && dn.dpi === 300, JSON.stringify(dn))
await E(p, () => localStorage.removeItem('vc-size-unit'))
}

await rulesHold(p, 'end')

ok('no page errors', errors.length === 0, errors.join(' | '))
console.log(out.join('\n'))
await b.close()
