import type { Article } from '../types'

// Tier 3 long-tail problem pages: one search, one answer, under 600 words, one CTA. Each links up to the guide that
// covers the subject in depth. Facts checked against the guides they link to and the editor source.

const D = '2026-09-27'

export const articles: Article[] = [
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'fix-a-blurry-image',
    title: 'How to fix a blurry image, and when you cannot',
    seoTitle: 'How to fix a blurry image (and when you cannot)',
    summary: 'Three kinds of blur, one of which can be fixed. How to tell them apart in ten seconds, what sharpening does and does not do, and the honest answer about upscaling.',
    description: 'Fix a blurry image: soft focus and light compression respond to sharpening; too few pixels do not. How to tell which you have, the Editor steps, and why upscaling cannot add detail.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Sharpen, Image size',
    goals: ['edit-a-photo'],
    answers: ['how to fix a blurry image', 'image is blurry how to fix', 'make a blurry picture clear', 'unblur an image', 'fix blurry photo online free', 'why is my image blurry', 'how to make image resolution higher', 'can you increase image resolution', 'sharpen a blurry photo'],
    related: ['image-resolution-explained', 'printed-design-looks-blurry', 'crop-and-canvas', 'texture-effects'],
    keywords: 'blurry image fix sharpen unblur resolution upscale pixels soft focus compression artefacts',
    guide: { before: ['image-resolution-explained'], next: ['pixelated-or-blurry'], also: [{ when: 'it is a print that came out blurry', slug: 'printed-design-looks-blurry' }, { when: 'you need it bigger', slug: 'resize-an-image-without-losing-quality' }] },
    body: [
      { t: 'answer', text: 'It depends which blur you have. **Slightly soft** (focus a touch off, or a small photo shown a bit too big): sharpening helps, and a Sharpen filter at a low amount is the fix. **Compressed** (blocky edges, smeared colour from a screenshot or a messaged JPG): a little sharpening plus a little noise hides it, but the detail is gone. **Too few pixels** (a 400 px image on a 1080 px post): nothing recovers it. Upscaling makes it bigger, not sharper; it invents pixels by blending the ones next to them. The real fix is the original file at its full size, so ask for it before you spend time on the copy.' },
      { t: 'h', text: 'Which blur is it' },
      { t: 'table', head: ['Look at it at 100 per cent', 'What you see', 'Fixable?'], rows: [
        ['Edges are soft but detail is there', 'Focus or slight enlargement', 'Yes, with Sharpen'],
        ['Blocky squares, halos around text, smeared colour', 'JPG compression, often repeated', 'Partly: sharpen a little, add grain, never re-save as JPG'],
        ['Each pixel is a visible square when you zoom', 'Too few pixels for the size', 'No. Get the original or use it smaller'],
        ['Sharp on your phone, soft when placed in a design', 'Placed at a size larger than its pixels', 'Use it at its own size or smaller'],
      ] },
      { t: 'h', text: 'Sharpen it in the Editor' },
      { t: 'steps', items: [
        'Open the image and press {{Ctrl+1}} to see it at 100 per cent. Judge only at this zoom; every other zoom lies.',
        'Choose **Filter, Enhance, Sharpen**. It arrives as a filter layer. Set **Amount** low, 20 to 40, and look at an edge. Stop before halos appear.',
        'For compression damage, add **Filter, Enhance, Noise** at a small amount as well. Fine noise breaks up the blocks and reads as texture rather than damage.',
        'Export as PNG, or JPG at 90 per cent or higher. Every JPG save loses a little more.',
      ] },
      { t: 'p', text: 'Sharpen raises contrast along edges. It makes an image look crisper; it does not add detail that was not captured. Use it once, at the output size, as the last step.' },
      { t: 'h', text: 'About making the resolution higher' },
      { t: 'p', text: '**Image, Image size…** can set a bigger pixel size, and the result is a bigger blurry image. Resampling averages neighbouring pixels to fill the gaps; no new information appears. That is true of every upscaler, including AI ones, which guess plausible detail rather than recover real detail. For a poster, use a photo that has the pixels; [Pixels, dpi and soft images](/learn/image-resolution-explained) has the numbers, and [Why your printed design looks blurry](/learn/printed-design-looks-blurry) the one-minute check.' },
      { t: 'product', text: 'The Sharpen and Noise filters are non-destructive layers, the 100 per cent view is one key, and the Image size dialog tells you the truth about how many pixels you have.', label: 'Open the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Can I unblur a photo?', a: 'Slight softness, yes, with sharpening. Motion blur, missed focus and low pixel counts, no; the detail was never recorded. Ask for the original file.' },
        { q: 'Does Voidcanvas have an AI upscaler?', a: 'No. Its AI tools select, cut out and fill; none of them invents detail in a photo. Upscaling makes an image larger, not sharper, so the guide says so rather than offering a button that pretends otherwise.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'psd-will-not-open',
    title: 'PSD will not open: the five causes and what to ask for',
    seoTitle: 'PSD will not open? The five causes and the fix for each',
    summary: 'A PSD that will not open is usually one of five things: the wrong kind of file, a huge file, an old or unusual save mode, a broken download, or a tool that does not read PSD at all. How to tell, and what to ask the sender for.',
    description: 'PSD not opening: check it is really a PSD, its size, the colour mode and bit depth it was saved in, and whether the download completed. What to ask the sender for, and how to open it in the browser.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Import',
    goals: ['work-with-psd'],
    answers: ['psd not opening', 'psd file will not open', 'cannot open psd file', 'psd file corrupted', 'psd won\'t open in photoshop', 'how to open a psd that will not open', 'psb file open', 'psd opens blank'],
    related: ['open-a-psd-file-online-free', 'import-psd-and-pdf', 'edit-a-psd-without-photoshop', 'troubleshooting'],
    keywords: 'psd not opening corrupted psb large file cmyk 16 bit 32 bit download incomplete compatibility maximize',
    guide: { before: ['open-a-psd-file-online-free'], next: ['import-psd-and-pdf'], also: [{ when: 'it opened but the fonts are wrong', slug: 'missing-fonts-in-a-psd' }] },
    body: [
      { t: 'answer', text: 'Work through five causes in order. **1. It is not a PSD**: a .psb (large document format), an .ai or .indd renamed, or a PSD inside a zip. **2. It is very large**: a multi-gigabyte file or one over 30,000 px on a side can exhaust memory in a browser or a laptop. **3. It was saved in an unusual mode**: CMYK, Lab, Duotone, 16- or 32-bit, or without "Maximize compatibility", which many readers need. **4. The download did not finish**: compare the size on disk with the size the sender sees. **5. The tool does not read PSD**: previewers and some editors show only the flattened preview or nothing. In the Voidcanvas Editor, drop the file on the start screen; if it opens with a report, read the report; if it does not open, the message says which of these it hit.' },
      { t: 'h', text: 'Check each one' },
      { t: 'table', head: ['Cause', 'How to tell', 'Fix or ask for'], rows: [
        ['Not really a PSD', 'Extension is .psb, .ai, .indd, .zip; or the icon is wrong', 'Ask for a PSD (or, for .psb, a version under 30,000 px saved as PSD). Unzip first.'],
        ['Too large', 'Hundreds of MB or more; thousands of layers; very large canvas', 'Ask for a flattened copy plus the layers you need, or a version at a smaller pixel size.'],
        ['Unusual mode', 'Opens blank, wrong colours, or an error about mode or depth', 'Ask for RGB, 8-bit, with Maximize compatibility on. The Editor opens 16-bit as 8-bit and converts CMYK, but 32-bit and Lab need converting first.'],
        ['Incomplete download', 'File size smaller than expected; error mentions end of file', 'Download again; use a link rather than an email attachment for big files.'],
        ['Tool cannot read it', 'Every PSD fails, not just this one', 'Use an editor that reads PSD layers: the Voidcanvas Editor opens them in the browser.'],
      ] },
      { t: 'h', text: 'Open it in the browser' },
      { t: 'steps', items: [
        'Go to [the Editor](/editor) and drop the file on **Open a photo**, or press {{Ctrl+O}}.',
        'If it opens, an **Opened** report may list what was kept, changed or left out. That report is the answer to "what happened to my file".',
        'If it does not open, note the message and the file size, and send the sender the row from the table above that matches.',
      ] },
      { t: 'product', text: 'The Editor reads PSD layers on your device and tells you what it changed, instead of failing silently. If it cannot open a file, the message says why.', label: 'Try the file in the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'How do I open a PSB file?', a: 'PSB is the large-document variant and most tools outside Photoshop do not read it. Ask for the file saved as PSD; if it is over 30,000 px on a side, ask for a smaller version or a flattened copy plus the layers you need.' },
        { q: 'The PSD opens but everything is on one layer. Why?', a: 'It was saved without Maximize compatibility, or your tool only reads the flattened preview. Ask for a re-save with compatibility on, and open it in an editor that reads layers.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'convert-psd-to-png',
    title: 'Convert a PSD to PNG (with transparency) without Photoshop',
    seoTitle: 'PSD to PNG with transparency, free, in the browser',
    summary: 'Open the PSD, hide what you do not want, export a PNG. Transparency is kept if the design has no background. The steps, the one setting that matters, and how to get single layers out.',
    description: 'Convert PSD to PNG without Photoshop: open it in the browser, hide the background layer, export a PNG with transparency at 1×, 2× or a custom size. Single layers too. Nothing is uploaded.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Export',
    goals: ['work-with-psd'],
    answers: ['psd to png', 'convert psd to png', 'psd to png with transparency', 'psd to jpg', 'export png from psd without photoshop', 'save psd as png online', 'extract layers from psd'],
    related: ['open-a-psd-file-online-free', 'export-for-screen', 'make-a-transparent-png', 'file-formats'],
    keywords: 'psd to png convert transparency export layers jpg webp online free no photoshop',
    guide: { before: ['open-a-psd-file-online-free'], next: ['export-for-screen'], also: [{ when: 'you need to edit it first', slug: 'edit-a-psd-without-photoshop' }] },
    body: [
      { t: 'answer', text: 'Open the PSD in [the Editor](/editor) (drop it on the start screen), hide any layer you do not want in the PNG, press {{Ctrl+E}}, choose **PNG**, pick a size and download. If the design has no background colour, the empty areas are transparent; if it has one, tick **Leave out the background colour** to drop it. JPG and WebP are in the same dialog. Nothing is uploaded and there is no account.' },
      { t: 'h', text: 'Steps' },
      { t: 'steps', items: [
        'Drop the PSD on **Open a photo** in [the Editor](/editor), or press {{Ctrl+O}}. Read the **Opened** report if one appears.',
        'In the Layers panel, click the eye next to any layer or group you want left out, such as a white background layer or a mockup.',
        'Press {{Ctrl+E}}. Choose **PNG**. Choose **1×** for the file at its own pixel size, **2×** for double, or a custom width. Text and shapes are redrawn sharp at any size; photos are resampled.',
        'If the dialog shows **Leave out the background colour**, tick it for a transparent PNG.',
        'Press **Download**. A version named Exported is saved, so you can always find the state you sent.',
      ] },
      { t: 'h', text: 'Single layers and variations' },
      { t: 'list', items: [
        '**One layer as its own PNG:** hide everything else and export. For a tight crop, choose **Image, Trim transparent edges** first.',
        '**Several versions:** export, change the visible layers, export again. Each download is a version, so nothing is lost.',
        '**JPG for photos:** same dialog, choose JPG, quality 80 to 90. JPG has no transparency; empty areas become white.',
        '**Smaller for the web:** WebP keeps transparency at a smaller size than PNG.',
      ] },
      { t: 'product', text: 'Open, hide, export. PNG with transparency, JPG and WebP, at any size, from any PSD the Editor can open, with the file staying on your device.', label: 'Open a PSD in the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Why is my PNG background white instead of transparent?', a: 'The PSD has a filled background layer or the design has a background colour. Hide the layer, or tick Leave out the background colour in the export dialog. JPG can never be transparent.' },
        { q: 'Can I export every layer as a separate PNG at once?', a: 'Not in one click. Hide and export per layer, or copy a layer into a new design and export that. Resize to every format is for one design in many sizes, not one design into its layers.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'missing-fonts-in-a-psd',
    title: 'Missing fonts in a PSD: replace them or load the file',
    seoTitle: 'Missing fonts in a PSD: replace, substitute or load the file',
    summary: 'When a PSD uses a font your computer does not have, the text still opens but looks wrong. What the dialog offers, where to get the font, how to choose a stand-in that keeps the layout, and how the font travels with the design afterwards.',
    description: 'Missing fonts in a PSD: the Editor lists each one and how many layers use it. Load the font file (.ttf, .otf, .woff, .woff2), pick a Google Font with a similar width, or keep a stand-in. The file is saved inside the design.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Character panel',
    goals: ['work-with-psd'],
    answers: ['psd missing fonts', 'missing font in psd', 'font substitution psd', 'psd fonts not showing', 'how to add a font to a psd', 'replace missing font', 'font missing when opening file'],
    related: ['import-psd-and-pdf', 'type', 'edit-a-psd-without-photoshop', 'typography-fundamentals'],
    keywords: 'missing fonts psd replace substitute add font file ttf otf woff google fonts stand-in layout width',
    guide: { before: ['open-a-psd-file-online-free'], next: ['type'], also: [{ when: 'you want to pick a good pairing', slug: 'typography-fundamentals' }] },
    body: [
      { t: 'answer', text: 'When you open a PSD that uses a font this device cannot find, **Some fonts are missing** lists each font and how many text layers use it. Three ways out: **Add font file** loads the real font from your computer (.ttf, .otf, .woff or .woff2) and saves it inside the design so it travels with it; **pick a replacement** from Google Fonts, choosing one of similar width so lines do not rewrap; or **keep a stand-in** for now and fix it later from the Character panel. Ask the sender for the font files first; the layout was set in that font and any substitute changes it a little.' },
      { t: 'h', text: 'Which option when' },
      { t: 'table', head: ['Situation', 'Do'], rows: [
        ['You have, or can get, the font file', 'Add font file. Exact result; the file is stored in the design. Check the licence allows use on this project.'],
        ['The font is on Google Fonts', 'Pick it from the list. Many commercial fonts have close Google relatives (Helvetica to Inter or Arimo, Futura to Jost, Garamond to EB Garamond).'],
        ['You only need to export the design as is', 'Keep the stand-in and check every text layer at 100 per cent before exporting. Lines may wrap differently.'],
        ['You will hand the file back to someone with the font', 'Keep the stand-in and do not touch the text layers; the font name is preserved in the layer.'],
      ] },
      { t: 'h', text: 'Choose a stand-in that keeps the layout' },
      { t: 'list', items: [
        'Match **width** before style. A wider substitute pushes text to a new line; a narrower one leaves gaps.',
        'Match **x-height** for body text so the blocks stay the same visual size.',
        'Match **weight**: a bold headline needs a family with a 700 weight.',
        'After substituting, walk through each text layer at 100 per cent and fix wraps by nudging size or tracking, not by retyping.',
      ] },
      { t: 'h', text: 'Fix it later' },
      { t: 'p', text: 'Select a text layer, open the **Character** panel (Window menu) and choose the font, or press **Add a font file from this device**. A font file added once is available to every text layer in that design and is saved inside it, so the design opens correctly on another device. It is never requested from Google.' },
      { t: 'product', text: 'The missing-fonts dialog names each font and its layer count, takes a font file in one click, and keeps that file inside the design. Google Fonts are there when you do not have the file.', label: 'Open the PSD in the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Where do I get the missing font?', a: 'From whoever made the PSD, since they had it. Otherwise from the foundry that sells it, or a Google Font that is close. Fonts are licensed; a file from a random download site is a legal and often a quality problem.' },
        { q: 'Will the substitute change the design?', a: 'Slightly, always. Different fonts have different widths, so lines wrap and blocks grow or shrink. Match width first and check each text layer at 100 per cent.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'crop-an-image-into-a-circle',
    title: 'Crop an image into a circle (transparent PNG)',
    seoTitle: 'Crop an image into a circle and export a transparent PNG',
    summary: 'A circle crop is an ellipse selection turned into a mask, then a PNG export with transparency. Four steps, plus how to get a soft edge, a border, or a perfectly centred circle.',
    description: 'Crop an image into a circle: Ellipse select with Shift, Mask from selection, Trim transparent edges, export PNG. Add a stroke for a border or feather for a soft edge. Free, in the browser.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Selections, Masks',
    goals: ['edit-a-photo', 'social-content'],
    answers: ['crop image into circle', 'crop photo into a circle', 'circle crop online', 'round profile picture maker', 'make an image round', 'circular crop transparent png', 'how to crop a picture in a circle'],
    related: ['selections', 'masks', 'make-a-transparent-png', 'export-for-screen'],
    keywords: 'circle crop round image ellipse select mask transparent png profile picture border stroke feather',
    guide: { next: ['masks', 'make-a-transparent-png'], also: [{ when: 'you want the background gone as well', slug: 'remove-background' }] },
    body: [
      { t: 'answer', text: 'Open the image, press {{Shift+M}} for **Ellipse select**, hold Shift and drag a circle over the part you want, then click **Mask from selection** in Properties. Choose **Image, Trim transparent edges** to cut the canvas to the circle, press {{Ctrl+E}}, choose **PNG** and download. The corners are transparent. Nothing is uploaded.' },
      { t: 'h', text: 'Steps' },
      { t: 'steps', items: [
        'Open the photo in [the Editor](/editor). If it is the background layer, it is already a normal layer here; nothing to unlock.',
        'Press {{M}} then {{Shift+M}} to reach **Ellipse select**. Start dragging, then hold **Shift** to keep it a circle. Release when the face or subject sits inside; if it is off, draw it again, or move the photo under it later with the Move tool.',
        'In Properties under **Mask**, click **Mask from selection**. The outside is hidden, not deleted, so you can move the photo inside the circle with the Move tool while the mask stays put.',
        'Choose **Image, Trim transparent edges** so the canvas fits the circle exactly.',
        'Press {{Ctrl+E}}, choose **PNG**, download. JPG would fill the corners with white.',
      ] },
      { t: 'h', text: 'Variations' },
      { t: 'list', items: [
        '**Perfectly centred circle:** after masking, select the layer and use **Layer, Align** to centre it on the canvas, or read the X, Y, W and H boxes in Properties and set them by hand.',
        '**Soft edge:** set **Feather** in the options bar to 10 to 30 px before drawing the selection, or **Select, Modify, Feather…** after.',
        '**Border:** add a **Stroke** layer style to the masked layer (Layer styles, Stroke, position Inside) in the colour you want. It follows the circle.',
        '**Exact size for a profile picture:** after trimming, **Image, Image size…** to 400 × 400 or whatever the platform wants. Most platforms crop to a circle themselves, so a square export with the subject centred is often enough.',
      ] },
      { t: 'product', text: 'Ellipse select, a mask that hides rather than deletes, trim to content and a transparent PNG export. The photo stays movable inside the circle until you export.', label: 'Open the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Why are the corners white, not transparent?', a: 'You exported a JPG, or the design has a background colour. Export PNG and, if the checkbox appears, tick Leave out the background colour.' },
        { q: 'Can I change which part of the photo shows?', a: 'Yes. The mask hides the outside; it does not crop the pixels. Select the layer, unlink the mask if needed, and drag the photo with the Move tool.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'make-a-transparent-png',
    title: 'Make a transparent PNG',
    seoTitle: 'Make a transparent PNG: remove the background and export',
    summary: 'Transparent means no background layer and a PNG or WebP export. How to get there from a photo, a logo on white, or a design with a background colour, and why the checkerboard sometimes still exports white.',
    description: 'Make a transparent PNG: remove or hide the background, then export PNG (or WebP) rather than JPG. For a logo on white use Remove background or Magic wand; for a design tick Leave out the background colour.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Remove background, Export',
    goals: ['edit-a-photo', 'build-a-brand'],
    answers: ['transparent png', 'make a transparent png', 'how to make background transparent', 'remove white background from logo', 'png transparent background online', 'export with transparent background', 'why is my png not transparent'],
    related: ['remove-background', 'export-for-screen', 'crop-an-image-into-a-circle', 'file-formats'],
    keywords: 'transparent png background remove white logo checkerboard export webp jpg magic wand',
    guide: { before: ['remove-background'], next: ['export-for-screen'], also: [{ when: 'it is a photo of a person or product', slug: 'remove-background' }] },
    body: [
      { t: 'answer', text: 'Two things make a PNG transparent: **nothing behind the subject** in the design, and **PNG or WebP** as the export type (JPG cannot be transparent). For a photo, **Layer, Remove background** hides the background with a mask, on your device. For a logo on white, the **Magic wand** ({{W}}, then click the white) plus **Mask hiding the selection** does it in two clicks. For a design that has a background colour, press {{Ctrl+E}}, choose PNG and tick **Leave out the background colour**. The checkerboard on the canvas means transparent; white means a layer or a colour is still there.' },
      { t: 'h', text: 'Three starting points' },
      { t: 'table', head: ['You have', 'Do', 'Notes'], rows: [
        ['A photo of a person, product or animal', '**Layer, Remove background** (or the button in Properties)', 'A model runs in your browser; the first use downloads it once. Use the any-subject model for objects. Tidy the mask with a brush if needed.'],
        ['A logo or graphic on a plain white background', 'Magic wand ({{W}}), click the white, Shift-click any leftover patches, then Layer, Layer mask, **Mask hiding the selection**', 'Lower Tolerance if the wand eats into the logo. Anti-aliased edges keep a faint white fringe; Select, Modify, Contract by 1 px before masking removes it.'],
        ['A design with a background colour', 'Nothing in the design; at export tick **Leave out the background colour**', 'Or set the design\'s background to none in Properties with no layer selected.'],
      ] },
      { t: 'h', text: 'Export' },
      { t: 'steps', items: [
        'Press {{Ctrl+E}}. Choose **PNG** (or **WebP** for a smaller web file). Not JPG.',
        'If **Leave out the background colour** is shown, tick it.',
        'Optionally **Image, Trim transparent edges** first, so the file is no bigger than the subject.',
        'Download. Open the file on a dark page to check; a white fringe means the mask needs contracting by a pixel.',
      ] },
      { t: 'product', text: 'Background removal runs on your device, the magic wand handles logos, and the export dialog says plainly which formats keep transparency.', label: 'Open the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Why is my PNG still white?', a: 'Either a background layer is still visible, the design has a background colour and the checkbox was not ticked, or you exported JPG. Check the canvas shows the checkerboard, then export PNG.' },
        { q: 'Does removing the background upload my photo?', a: 'No. The model is downloaded to your browser once and runs there. You can do it with Wi-Fi off after the first time.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'outline-text',
    title: 'Outline text so it reads on any photo',
    seoTitle: 'Outline text so it reads on any photo (and hollow text)',
    summary: 'Two ways to outline text, when to use each, the width that reads without looking like a meme, and hollow outlined letters with Fill at zero.',
    description: 'Outline text in the browser: the quick Outline in Properties, or a Stroke layer style with position and colour control. Widths that read, hollow text with Fill 0, and the alternatives to an outline.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Type, Layer styles',
    goals: ['social-content', 'learn-design'],
    answers: ['how to outline text', 'outline text online', 'add a border to text', 'stroke text', 'hollow text outline', 'text outline for thumbnail', 'make text stand out on a photo', 'white outline around text'],
    related: ['type', 'layer-styles', 'typography-fundamentals', 'designing-for-social'],
    keywords: 'outline text stroke border hollow fill opacity thumbnail readable photo width',
    guide: { before: ['type'], next: ['layer-styles'], also: [{ when: 'the real problem is the photo behind it', slug: 'designing-for-social' }] },
    body: [
      { t: 'answer', text: 'Select the text layer and, in Properties, click **Add** next to **Outline**, pick a colour and set **Outline width**. That is the quick way. For control over where the stroke sits, use a **Stroke** layer style instead: position **Outside** keeps the letter shapes intact, **Inside** keeps the text the same size, and the style follows the text when you retype it. For hollow letters, add a Stroke and set **Fill opacity** to 0. Outlines read best at 2 to 4 per cent of the text size (a 100 px headline takes a 2 to 4 px stroke); thicker starts to look like a meme, so before going thicker try a darker photo or a band behind the text.' },
      { t: 'h', text: 'Two methods' },
      { t: 'table', head: ['Method', 'Where', 'Good for', 'Limits'], rows: [
        ['Outline in Properties', 'Text layer, Properties, Outline: Add', 'Quick captions and labels', 'One colour, centred on the edge, no position control'],
        ['Stroke layer style', 'Layer styles, Stroke: colour, width, position Inside, Centre or Outside', 'Headlines, thumbnails, hollow text, stacking with a shadow', 'Slightly more clicks'],
      ] },
      { t: 'h', text: 'Steps with a layer style' },
      { t: 'steps', items: [
        'Select the text layer. Open **Layer styles** (Properties, or double-click the layer in the Layers panel).',
        'Add **Stroke**. Set the colour (white or black almost always), the width, and **Position: Outside** so the letterforms are not eaten.',
        'For more separation from the photo, add **Drop shadow** as well: small distance, size 10 to 20, opacity 40 to 60.',
        'For hollow text, under **Blending options** set **Fill opacity** to 0 per cent. The letters vanish and the stroke stays.',
        'Retype or resize the text at any point; the style follows.',
      ] },
      { t: 'h', text: 'Before you outline, consider' },
      { t: 'list', items: [
        'Darken the photo under the text with a **Curves** or **Black and white** adjustment layer clipped to a rectangle, or a **Gradient overlay** on a shape behind the text.',
        'Put the text on a flat band or box. It reads at any size and looks designed rather than defended.',
        'Move the text to the quietest part of the photo. Outlines fix contrast; they do not fix a busy background.',
      ] },
      { t: 'product', text: 'Outline and shadow on every text layer in Properties, and full layer styles (Stroke with position, Drop shadow, glows) that follow the text as you edit. The Outline and Sticker presets are one click.', label: 'Open the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'How thick should a text outline be?', a: 'About 2 to 4 per cent of the text size: 2 to 4 px on a 100 px headline, 1 px on 30 px captions. If that is not enough, the fix is the photo behind the text, not a thicker stroke.' },
        { q: 'How do I make hollow outlined text?', a: 'Add a Stroke layer style, then set Fill opacity to 0 in Blending options. The stroke stays at full strength while the letters go transparent.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'put-text-on-a-path',
    title: 'Put text on a curve or a path',
    seoTitle: 'Put text on a curve or a path in the browser',
    summary: 'Text along a circle, an arc or any curve: draw the path, click it with the Type tool, then adjust the start, the lift and the side. Three common shapes and the spacing fix that makes curved text readable.',
    description: 'Put text on a path: draw a circle or a curve with the Shape or Pen tools, click the outline with the Type tool, then set Start along the path, Lift off the path and Flip side. Badge, arc and wave examples.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Type on a path',
    goals: ['learn-design', 'build-a-brand'],
    answers: ['how to make text on a path', 'curved text', 'text in a circle', 'text on a curve online', 'arc text', 'type on a path', 'wrap text around a circle', 'circular text for a logo'],
    related: ['type', 'shapes-and-pen', 'design-a-poster-with-no-photo', 'layer-styles'],
    keywords: 'text on a path curved text circle arc wave badge logo type tool pen curvature start lift flip tracking',
    guide: { before: ['type'], next: ['shapes-and-pen'], also: [{ when: 'it is for a whole poster', slug: 'design-a-poster-with-no-photo' }] },
    body: [
      { t: 'answer', text: 'Draw the path first, then type on it. For a circle: press {{U}}, choose **Ellipse**, Shift-drag a circle, and click **Remove** next to **Fill** in Properties so it is invisible. For a curve: press {{P}}, choose the **Curvature pen** with {{Shift+P}}, set the options bar to **Path**, and click a few points. Then press {{T}} and click on the shape\'s outline or the selected path; the text flows along it. Properties gains **Start along the path**, **Lift off the path**, **Flip side**, **Edit the path** and **Release from path**. Widen the tracking a little: letters on a curve crowd on the inside.' },
      { t: 'h', text: 'Three shapes' },
      { t: 'table', head: ['You want', 'Path', 'Settings'], rows: [
        ['A badge: words around the top of a circle, more around the bottom', 'A circle (Ellipse, Shift-drag, Fill removed)', 'Type the top words; set Start so they are centred at the top. Duplicate the text layer for the bottom words and Flip side so they read the right way up. Lift the top text slightly off the path.'],
        ['An arc over a headline', 'A wide, shallow curve with the Curvature pen (three clicks)', 'Centre with Start; keep the arc shallow, under about 20 degrees of bend, or the letters lean visibly.'],
        ['A wave', 'An S-curve with the Curvature pen (four or five clicks)', 'Keep the waves long and gentle; short waves make letters collide.'],
      ] },
      { t: 'h', text: 'Steps' },
      { t: 'steps', items: [
        'Draw the path with the Shape tool ({{U}}) or the Pen family ({{P}}, {{Shift+P}} to cycle to the Curvature pen) in **Path** mode.',
        'Press {{T}} and click exactly on the outline or path. The cursor changes when it is over it.',
        'Type. Set font and size in the **Character** panel. Add 20 to 60 units of **Tracking** so the inside of the curve does not jam.',
        'In Properties, drag **Start along the path** to slide the text, **Lift off the path** to raise it above or below the line, **Flip side** to put it on the other side of the path.',
        '**Edit the path** reshapes the curve with the text following; **Release from path** turns it back into straight text.',
      ] },
      { t: 'product', text: 'Type on any shape or pen path, with start, lift and side as sliders and the path still editable afterwards. The text stays editable text.', label: 'Open the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Why does the text sit inside the circle instead of outside?', a: 'Flip side. It moves the text to the other side of the path, and the baseline faces the other way.' },
        { q: 'Can I make the bottom text read left to right too?', a: 'Yes: use a second text layer for the bottom words and Flip side on that one, then slide it with Start along the path. That is how badges are set.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'youtube-thumbnail-size',
    title: 'YouTube thumbnail size and the three legibility rules',
    seoTitle: 'YouTube thumbnail size (1280 × 720) and the 3 rules that work',
    summary: '1280 × 720, 16:9, under 2 MB. The number is easy; the thumbnail is seen at 200 px wide, which is where most fail. Three rules with numbers, the preset, and the export settings.',
    description: 'YouTube thumbnail size is 1280 × 720 px (16:9), JPG or PNG under 2 MB. Design for 200 px wide: three words, one face, one bright colour, text at 120 px or larger. Preset and export settings.',
    category: 'craft', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · YouTube preset',
    goals: ['social-content'],
    answers: ['youtube thumbnail size', 'youtube thumbnail dimensions', 'thumbnail size for youtube 2026', 'youtube thumbnail text size', 'how to make a youtube thumbnail', 'best photoshop alternative for youtube thumbnails', 'youtube thumbnail maker free no watermark', 'thumbnail resolution'],
    related: ['size-presets', 'social-media-sizes-and-safe-zones', 'outline-text', 'remove-background'],
    keywords: 'youtube thumbnail size 1280 720 16:9 2mb legibility 200px face text size preset export jpg',
    guide: { before: ['social-media-sizes-and-safe-zones'], next: ['outline-text', 'remove-background'], also: [{ when: 'you want every size in one place', slug: 'size-presets' }] },
    body: [
      { t: 'answer', text: '**1280 × 720 px**, 16:9, JPG or PNG under 2 MB. That is the file. The design problem is that it is shown at about 200 to 400 px wide in a list next to twenty others, so: **three words maximum**, set at 120 px or larger on the 1280 px canvas with an outline or a band; **one face or one object**, big, cut out and placed on a flat or blurred background; **one bright colour** that the competing thumbnails are not using. The duration badge covers the bottom right corner. Test by shrinking the canvas to the size of a postage stamp; if the words still read, publish.' },
      { t: 'h', text: 'The three rules, with numbers' },
      { t: 'table', head: ['Rule', 'Number', 'Why'], rows: [
        ['Three words', 'Headline 120 to 200 px tall on the 1280 canvas, heavy weight, outline or band', 'At 200 px wide the canvas is shrunk 6×; 120 px becomes 19 px, which is the smallest that reads in a list.'],
        ['One face or object', 'Filling at least a third of the height; eyes in the upper half', 'Faces get clicks; small faces get nothing. Cut it out so it pops off the background.'],
        ['One bright colour', 'Background or a band in a colour the neighbours are not using; text in white or black', 'The list is the competition. Contrast with it, not within it.'],
      ] },
      { t: 'h', text: 'Make it' },
      { t: 'steps', items: [
        'Open the [YouTube preset](/editor?preset=yt) (1280 × 720).',
        'Place the photo ({{Ctrl+Shift+P}}), then **Layer, Remove background**. Scale the cut-out large, to one side, with **Free transform** ({{Ctrl+T}}).',
        'Fill the background with a flat colour or a blurred, darkened copy of the photo (duplicate, **Filter, Enhance, Blur**, then a **Curves** adjustment to darken).',
        'Type the three words. Character panel, size 140 px, weight 800. Add a **Stroke** layer style, 6 px, Outside, or put the words on a flat band.',
        'Keep the bottom right 200 × 80 px clear for the duration. Zoom out until the canvas is stamp-sized and check the words.',
        'Press {{Ctrl+E}}, choose **JPG** at 90 per cent (or PNG if the file stays under 2 MB), size 1×, download.',
      ] },
      { t: 'product', text: 'A YouTube preset, on-device background removal, layer styles for the outline and a JPG export at the right size. No watermark, no account.', label: 'Start a thumbnail', href: '/editor?preset=yt' },
      { t: 'faq', items: [
        { q: 'Should a thumbnail be 1280 × 720 or 1920 × 1080?', a: '1280 × 720 is what YouTube asks for and is displayed at a fraction of that. 1920 × 1080 is accepted and resized down; it gains nothing except file size. Stay under 2 MB either way.' },
        { q: 'What text size is readable on a thumbnail?', a: 'On the 1280 px canvas, 120 px or larger for the main words. Anything under 80 px disappears in the list view on a phone.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor?preset=yt' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'file-naming-and-versioning-for-design-work',
    title: 'File naming and versioning for design work',
    seoTitle: 'File naming and versioning for design work (no more final_v3)',
    summary: 'One naming pattern, one rule for when a number goes up, and one place versions live. The scheme, why it is in that order, what to do with client edits, and how Studio applies it for you.',
    description: 'A file naming and versioning scheme for designers: client_job_format_version, lower case, hyphens; the version goes up on every send; versions live with the design, not in the file name.',
    category: 'studio', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Studio · Deliver',
    goals: ['client-project', 'work-faster'],
    answers: ['file naming convention for designers', 'design file versioning', 'how to name design files', 'versioning explained', 'how designers organise files', 'final final v2 naming', 'version control for graphic design', 'naming convention for deliverables'],
    related: ['delivering-files', 'templates-and-versions', 'run-a-client-design-project', 'get-client-feedback-you-can-act-on'],
    keywords: 'file naming versioning convention client job format version lowercase hyphens final v2 deliverables',
    guide: { before: ['run-a-client-design-project'], next: ['delivering-files', 'templates-and-versions'], also: [{ when: 'the versions are for client rounds', slug: 'get-client-feedback-you-can-act-on' }] },
    body: [
      { t: 'answer', text: 'Name every file **client_job_format_version**, all lower case, spaces as hyphens, underscores between the four parts: `lekki-nights_launch_a3-poster_v2.pdf`. The version number goes up **every time anything leaves you**, whether to the client or the printer, and never goes back down. "Final" is not a version. Versions themselves live with the design (restore points you can go back to), not as copies of the file with longer names. Studio names delivered files this way for you and uses the review version number, so the client, the printer and you are all talking about the same v3.' },
      { t: 'h', text: 'The pattern, and why that order' },
      { t: 'table', head: ['Part', 'Example', 'Why it is there, and in this position'], rows: [
        ['client', 'lekki-nights', 'Sorts every job for one client together in any folder or search.'],
        ['job', 'launch', 'Inside a client, sorts by job. Short: the folder can hold the long name.'],
        ['format', 'a3-poster, instagram-post, story', 'The deliverable. A person opening the zip knows what each file is without opening it.'],
        ['version', 'v2', 'Last, so files of one format sort in order. Two digits (v02) if you expect more than nine sends.'],
        ['extension', '.pdf, .png, .jpg', 'The file type does the rest; do not put "print" or "web" in the name when the extension and format already say it.'],
      ] },
      { t: 'p', text: 'Lower case and hyphens survive email, WhatsApp, Windows, macOS, web servers and printers\' upload forms. Spaces, capitals, ampersands and accents do not always.' },
      { t: 'h', text: 'When the number goes up' },
      { t: 'list', items: [
        'On every send. If the client saw v2, the next thing they see is v3, even if the change was one comma. Otherwise two different files share a name and the wrong one gets printed.',
        'Not while you work. Internal saves are versions inside the design, not new file names.',
        'Client edits after approval start a new version and, if they are more than a typo, a new round.',
        'Delivered files carry the version that was approved. If v3 was approved, the print PDF is v3.',
      ] },
      { t: 'h', text: 'Where versions live' },
      { t: 'p', text: 'A version is a restore point for one design. Keep them inside the tool, where they carry a thumbnail, a date and a label, and restore or branch from any of them. In the Editor, **File, Save a version** ({{Ctrl+Alt+S}}) makes one, exports make one automatically, and **File, Version history…** lists them. In Studio, the **Review** tab holds one numbered version per round with what changed and the client\'s reply. Copies of files named `poster-final-FINAL-2.psd` are versions without any of that information.' },
      { t: 'product', text: 'Studio names every delivered file client_job_format_version from the job itself and the approved review version, zips them with a delivery note, and keeps the review versions numbered. The Editor keeps restore points inside each design.', label: 'Open Studio', href: '/studio' },
      { t: 'faq', items: [
        { q: 'Should I put the date in the file name?', a: 'Only when several deliveries of the same format happen on different dates with no version change, which the version number already prevents. Dates belong in the delivery note; the version is what people quote back to you.' },
        { q: 'What about internal drafts?', a: 'They are versions inside the design, saved with a label, not files. When one goes out, it gets the next version number.' },
      ] },
      { t: 'try', label: 'Open Studio', href: '/studio' },
    ],
  },

  // ── Batch 2 of Tier 3: resolution and effects ─────────────────────
  {
    slug: 'resize-an-image-without-losing-quality',
    title: 'Resize an image without losing quality: what is possible',
    seoTitle: 'Resize an image without losing quality: what really works',
    summary: 'Making an image smaller is always safe. Making it bigger never adds detail. How to do both well, the one habit that quietly ruins photos, and the way Voidcanvas keeps a layer\'s original pixels while you try sizes.',
    description: 'Resize an image without losing quality: shrink freely, enlarge as little as possible, resize once from the original, and keep text as text. How the Editor keeps a layer\'s pixels while you try sizes.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Image size, Move tool',
    goals: ['edit-a-photo'],
    answers: ['resize image without losing quality', 'how to resize an image without losing quality', 'make an image bigger without losing quality', 'enlarge photo without pixelation', 'resize photo online free', 'scale image up without blur', 'does resizing reduce quality'],
    related: ['fix-a-blurry-image', 'image-resolution-explained', 'crop-and-canvas', 'export-for-screen'],
    keywords: 'resize image without losing quality enlarge upscale downscale resample image size scale layer transform once original',
    guide: { before: ['image-resolution-explained'], next: ['crop-and-canvas'], also: [{ when: 'it is already blurry', slug: 'fix-a-blurry-image' }] },
    body: [
      { t: 'answer', text: '**Smaller is always safe**: shrinking throws away pixels you did not need, and the result looks as sharp or sharper. **Bigger never adds detail**: enlarging invents pixels by blending the ones next to them, so it looks softer, and no tool changes that. So: work from the **original** file, resize **once** to the final size, keep text and logos as **text and shapes** (they redraw sharp at any size), and enlarge photos as little as you can get away with. In the Voidcanvas Editor, resizing a photo layer with the Move tool\'s handles or the W and H boxes keeps its original pixels, so you can try sizes and go back without loss.' },
      { t: 'h', text: 'What happens to the pixels' },
      { t: 'table', head: ['You', 'What happens', 'Quality'], rows: [
        ['Shrink a photo', 'Pixels are averaged together', 'Same or better'],
        ['Enlarge a photo up to about 1.5×', 'New pixels blended from neighbours', 'Slightly soft; fine for screens and posters seen from a distance'],
        ['Enlarge a photo 2× or more', 'Most pixels are invented', 'Visibly soft; edges smear'],
        ['Resize text, shapes, layer styles', 'Redrawn from their outlines', 'Sharp at any size'],
        ['Resize the same photo several times', 'Each resize blends again', 'Softer every time'],
        ['Save as JPG after each resize', 'Compression on top of compression', 'Blocky around edges and text'],
      ] },
      { t: 'h', text: 'In the Editor' },
      { t: 'list', items: [
        '**One layer:** drag the Move tool\'s corner handles, or type a new **W** or **H** in the Position section of Properties. The layer keeps its original pixels and only stores the new size, so shrinking it and then enlarging it back is lossless, up to the size it arrived at.',
        '**Free transform** ({{Ctrl+T}}) redraws the pixels when you press Enter. Use it once, for rotation, skew or warp, not for trying sizes.',
        '**The whole design:** **Image, Image size…** ({{Ctrl+Alt+I}}) scales every layer. Text and shapes are redrawn; photos are resampled. The Editor saves a version before a large resize so you can go back.',
        '**Exports:** 2× and 3× exports redraw text and shapes at the larger size, so a 1080 px design exports a crisp 2160 px file. Photos in it are only as sharp as their own pixels.',
      ] },
      { t: 'h', text: 'When you need it bigger than it is' },
      { t: 'p', text: 'Ask for the original. A photo from a phone, a camera or a stock site is almost always larger than the copy that was emailed, messaged or screenshotted. If there is no original, use the image smaller than you planned, crop less, or make it a background element under a colour or a texture, where softness reads as intentional. A little **Film Grain** on top also hides mild softness better than sharpening does.' },
      { t: 'product', text: 'Layers keep their source pixels while you size them, text and shapes are redrawn at every size, and 2× exports are real 2× for everything that is vector.', label: 'Open the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Does resizing reduce quality?', a: 'Shrinking does not, in any way you can see. Enlarging always does, a little at 1.5× and clearly at 2× or more. Repeated resizing and repeated JPG saves reduce it further.' },
        { q: 'Can AI upscalers enlarge without losing quality?', a: 'They produce a sharper-looking result by inventing plausible detail. It is not the real detail, and on faces, text and logos the inventions can be wrong. Use the original when accuracy matters.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'check-if-an-image-is-big-enough-to-print',
    title: 'How to check whether an image is big enough to print',
    seoTitle: 'Is my image big enough to print? The one-minute check',
    summary: 'Find the pixel size, divide by the dpi you need, and you have the largest print that will look sharp. Where to find the pixel size on any device, the table for common sizes, and how to check a photo already placed in a design.',
    description: 'Check if an image is big enough to print: find its pixel size, divide by 300 for close viewing or 150 for posters. Where to find the size on Windows, Mac, phones and in the Editor, with a table.',
    category: 'craft', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Image size, status bar',
    goals: ['prepare-for-print', 'make-a-poster'],
    answers: ['how to check image resolution', 'is my image big enough to print', 'how big can i print this photo', 'image resolution checker', 'is my image high resolution', 'what size can i print a photo', 'how to find image pixel size'],
    related: ['image-resolution-explained', 'what-dpi-should-a-poster-be', 'printed-design-looks-blurry', 'fix-a-blurry-image'],
    keywords: 'check image resolution pixel size big enough print dpi 300 150 dimensions properties get info status bar placed photo enlarged',
    guide: { before: ['image-resolution-explained'], next: ['what-dpi-should-a-poster-be', 'printed-design-looks-blurry'] },
    body: [
      { t: 'answer', text: 'Divide the pixel size by the dpi the print needs. **Largest sharp print (inches) = pixels ÷ 300** for anything read up close, **÷ 150** for posters read from a metre or more; multiply inches by 25.4 for millimetres. A 3000 × 2000 px photo prints sharp at 10 × 6.7 in (254 × 169 mm) at 300 dpi, or 20 × 13.3 in at 150. The dpi number saved in the file does not matter; only the pixels do. Find the pixels in the file\'s details on your computer or phone, or open the image on its own in the Editor and read the status bar.' },
      { t: 'h', text: 'Find the pixel size' },
      { t: 'table', head: ['Where', 'How'], rows: [
        ['Windows', 'Right-click the file, Properties, Details tab: Dimensions.'],
        ['Mac', 'Select the file in Finder, File, Get Info, More Info: Dimensions. Or open it in Preview, Tools, Show Inspector.'],
        ['iPhone', 'Photos, open the image, swipe up or tap the info button: the pixel size shows under the camera details.'],
        ['Android', 'Gallery or Photos, open the image, Details or swipe up.'],
        ['Voidcanvas Editor', 'Open the image on its own with {{Ctrl+O}}. The status bar at the bottom shows W × H px. Images over 4096 px on the long side are scaled to 4096 on import, so check very large files in the file details instead.'],
      ] },
      { t: 'h', text: 'What it will print at' },
      { t: 'table', head: ['Print', 'Needs at 300 dpi', 'Needs at 150 dpi'], rows: [
        ['6 × 4 in photo', '1800 × 1200 px', 'not recommended up close'],
        ['A5 flyer', '1748 × 2480 px', 'not recommended up close'],
        ['A4', '2480 × 3508 px', '1240 × 1754 px'],
        ['A3', '3508 × 4961 px', '1754 × 2480 px'],
        ['A2 poster', '4961 × 7016 px', '2480 × 3508 px'],
        ['18 × 24 in poster', '5400 × 7200 px', '2700 × 3600 px'],
      ] },
      { t: 'p', text: 'The photo only needs to fill the part of the page it covers. A photo filling half an A4 page needs half of A4\'s pixels in that direction.' },
      { t: 'h', text: 'A photo already placed in a design' },
      { t: 'steps', items: [
        'Select the photo layer. In Properties, the **Position** section shows its **W** and **H** in document pixels.',
        'Compare W with the photo\'s own width from the table above. If W is larger, the photo has been enlarged; the ratio is how much.',
        'Up to about 1.2× is invisible in print; 1.5× is fine on a poster seen from a distance; 2× or more shows at arm\'s length.',
        'Press {{Ctrl+1}} for 100 per cent and look at an edge. What you see there is roughly what 300 dpi ink shows.',
      ] },
      { t: 'product', text: 'The status bar shows the document\'s pixel size and dpi, the Image size dialog shows the print size in centimetres at any dpi, and Properties shows how large each layer has been placed.', label: 'Open the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'My photo says 72 dpi. Is it too low for print?', a: 'The number alone means nothing. Check the pixels: a 4000 px wide photo at 72 dpi is the same image as one labelled 300 dpi, and prints sharp up to about 13 in wide.' },
        { q: 'Why is the photo smaller in the Editor than on my computer?', a: 'Imports are capped at 4096 px on the long side. For the true size of a very large photo, read it from the file details.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'social-images-blurry-after-upload',
    title: 'Why social images look blurry after upload, and how to export them',
    seoTitle: 'Why your image looks blurry on Instagram or Facebook (and the fix)',
    summary: 'Sharp on your computer, soft on the feed. Platforms resize anything that is not their size and recompress every upload. How to give them less to damage: the right size, the right format, and the setting on your phone.',
    description: 'Images look blurry after upload because platforms resize and recompress them. Export at the exact platform size, PNG for text graphics, JPG at 90 for photos, never a screenshot, and check your app\'s upload quality setting.',
    category: 'craft', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Presets, Export',
    goals: ['social-content'],
    answers: ['facebook cover image looks blurry', 'instagram photo blurry after upload', 'why is my image blurry on instagram', 'why does my picture look blurry on facebook', 'image quality lost after upload', 'linkedin banner blurry', 'best export settings for instagram'],
    related: ['social-media-sizes-and-safe-zones', 'export-for-screen', 'size-presets', 'fix-a-blurry-image'],
    keywords: 'blurry after upload instagram facebook linkedin compression resize export settings png jpg quality platform size screenshot data saver',
    guide: { before: ['social-media-sizes-and-safe-zones'], next: ['export-for-screen'], also: [{ when: 'it was already soft before upload', slug: 'fix-a-blurry-image' }] },
    body: [
      { t: 'answer', text: 'Every platform **resizes** an image that is not its display size and **recompresses** every upload. Give it as little to change as possible: design at the platform\'s exact size (Instagram post 1080 × 1350, story 1080 × 1920, Facebook cover 1640 × 624, LinkedIn banner 1584 × 396), export at **1×**, use **PNG** for graphics with text and flat colour and **JPG at 90 per cent** for photos, upload the exported file rather than a screenshot, and turn off any data-saver or low-quality upload setting in the app. Text smaller than about 36 px on a 1080 px canvas softens badly whatever you do.' },
      { t: 'h', text: 'The causes, most common first' },
      { t: 'table', head: ['Cause', 'What you see', 'Fix'], rows: [
        ['Wrong size', 'Soft all over, especially text', 'Start from the platform preset; export at 1×'],
        ['JPG on top of JPG', 'Blocks and halos around text and edges', 'PNG for graphics; one JPG save only, at 90 per cent or higher'],
        ['Screenshot or messaged copy', 'Soft and slightly off in colour', 'Upload the exported file itself'],
        ['Small text', 'Letters smear into each other', '36 px minimum on a 1080 px canvas; 48 px or more for anything important'],
        ['App upload setting', 'Everything uploaded from the phone is soft', 'Turn off data saver; turn on the highest upload quality if the app offers it'],
        ['Photo was upscaled into the design', 'Photo soft, text sharp', 'Use a larger original; see the resolution check'],
      ] },
      { t: 'h', text: 'Export for a feed' },
      { t: 'steps', items: [
        'Start from the preset for the platform on the Editor start screen, or check the design size in the status bar.',
        'Press {{Ctrl+E}}. Choose **PNG** if the design is mostly text, shapes and flat colour; **JPG** if it is mostly photo. Set JPG quality to 90 or more.',
        'Choose **1×**. Larger exports are resized down by the platform, which softens text more than a correct size does.',
        'Send the file to your phone as a file (AirDrop, a cloud folder, email to yourself as an attachment), not through a chat app, which recompresses it first.',
      ] },
      { t: 'note', text: 'Platforms change their sizes and compression without notice. The presets match the current published sizes; check before a paid placement.' },
      { t: 'product', text: 'Presets at platform size, a 1× export that is exactly that size, PNG for sharp text and a JPG quality slider. The sizes are in Social media sizes and safe zones.', label: 'Start a social post', href: '/editor?preset=ig-post' },
      { t: 'faq', items: [
        { q: 'Should I upload at 2× for a sharper result?', a: 'Usually not. The platform resizes it down to its own size, and its resizer is tuned for speed rather than for your text. Exact size at 1× is the safest.' },
        { q: 'Why is my Facebook cover blurry but my posts are fine?', a: 'Covers are shown at different sizes on desktop and phone and are resized for each. Use a 1640 × 624 PNG with large text away from the edges, so the resize has little fine detail to smear.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor?preset=ig-post' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'pixelated-or-blurry',
    title: 'Pixelated or blurry? What each look tells you about the image',
    seoTitle: 'Pixelated vs blurry vs compressed: what each look means',
    summary: 'Square blocks, soft edges, smeared patches and stripes in a gradient are four different problems with four different fixes. How to tell them apart at 100 per cent, and what to do about each.',
    description: 'Pixelated means visible square pixels from too few pixels; blurry means soft edges; compressed means blocks and halos; banding means stripes in gradients. How to tell them apart and fix each one.',
    category: 'craft', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · 100 per cent view',
    goals: ['edit-a-photo', 'learn-design'],
    answers: ['image looks pixelated and blurry', 'pixelated vs blurry', 'why is my image pixelated', 'difference between pixelated and blurry', 'jpeg artifacts', 'banding in gradients', 'why does my gradient have stripes'],
    related: ['fix-a-blurry-image', 'image-resolution-explained', 'resize-an-image-without-losing-quality', 'add-film-grain'],
    keywords: 'pixelated blurry compressed jpeg artefacts banding gradient stripes square pixels soft edges diagnose fix',
    guide: { before: ['image-resolution-explained'], next: ['fix-a-blurry-image'], also: [{ when: 'the problem is a gradient', slug: 'add-film-grain' }] },
    body: [
      { t: 'answer', text: 'Look at the image at 100 per cent and match what you see. **Pixelated** means hard square steps along edges: too few pixels, enlarged without smoothing. **Blurry** means soft edges with no steps: out of focus, or enlarged with smoothing. **Compressed** means blocky 8-pixel patches in flat areas and halos around text: saved as JPG, often several times. **Banding** means stripes across a smooth gradient: too few tones. Only blur from slight softness and banding can be improved much; the other two need a better source file.' },
      { t: 'h', text: 'Tell them apart' },
      { t: 'table', head: ['Look', 'At 100 per cent you see', 'Cause', 'Fix'], rows: [
        ['Pixelated', 'Staircase edges, square blocks of one colour', 'A small image enlarged, or a tiny icon or GIF', 'Get the original; or make it deliberate with the Pixelate effect'],
        ['Blurry', 'Soft edges, no squares', 'Focus, motion, or smooth enlargement', 'Light sharpening if slight; otherwise a better source'],
        ['Compressed', 'Blocks in flat areas, halos and ringing round text', 'JPG at low quality or saved repeatedly', 'Re-export from the original as PNG, or JPG at 90 or more; a little noise hides mild damage'],
        ['Banding', 'Visible steps or stripes in a sky or gradient', 'Too few tones, often after compression', 'Add Film Grain or Noise at a low amount; export PNG'],
      ] },
      { t: 'h', text: 'Checking at the right zoom' },
      { t: 'p', text: 'Every zoom other than 100 per cent lies: zoomed out, problems hide; zoomed in past 100, even a perfect photo looks soft. Press {{Ctrl+1}} in the Editor and pan with Space. For a print, 100 per cent on screen is close to what 300 dpi ink shows at arm\'s length; for a phone post, hold the phone at a normal distance instead.' },
      { t: 'h', text: 'Fixes in the Editor' },
      { t: 'list', items: [
        '**Slight blur:** **Filter, Enhance, Sharpen** at a low amount, checked at 100 per cent. See [How to fix a blurry image](/learn/fix-a-blurry-image).',
        '**Banding:** **Filter, Enhance, Film Grain** with Amount 5 to 15 over the gradient. Fine grain breaks the steps up. See [Add film grain that looks like film](/learn/add-film-grain).',
        '**Mild compression:** a little Noise or Film Grain hides the blocks; export PNG so you do not add more.',
        '**Pixelated on purpose:** **Filter, Stylize, Pixelate** gives even, deliberate squares for a retro look.',
      ] },
      { t: 'product', text: 'One key for the honest 100 per cent view, Sharpen, Noise and Film Grain as filter layers you can fade and mask, and PNG export so the fix is not compressed again.', label: 'Open the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Can a pixelated image be fixed?', a: 'Not truly. Smoothing turns the squares into blur, and AI upscalers guess new detail. The fix is the original file, or using the image smaller.' },
        { q: 'Why does my gradient look stripy only after export?', a: 'JPG compression and 8-bit colour reduce the number of tones in a slow gradient. Add a little grain before exporting and use PNG.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'make-a-newspaper-photo-effect',
    title: 'The newspaper photo effect: halftone, grain and a warm paper tint',
    seoTitle: 'Newspaper photo effect: halftone, paper tint and grain',
    summary: 'A newspaper photo is a fine halftone in dark grey ink on off-white paper, a little soft, with flat contrast. Four layers make it, in the Editor or in Effects, with a live halftone to set the dots.',
    description: 'Make a newspaper photo effect: black and white with faded contrast, a fine halftone on Multiply, an off-white paper tint and light grain. Step by step in the browser, with a live halftone example.',
    category: 'effects', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Effects · Halftone, Film Grain',
    goals: ['design-effects'],
    answers: ['how to make newspaper effect in canva', 'newspaper photo effect', 'newspaper print effect', 'make a photo look like a newspaper', 'old newspaper effect', 'newsprint halftone effect', 'newspaper texture photo'],
    related: ['make-a-halftone-portrait', 'make-a-comic-book-effect', 'texture-effects', 'filters-in-the-editor'],
    keywords: 'newspaper effect newsprint halftone paper tint grain faded black and white old newspaper photo',
    guide: { before: ['make-a-halftone-portrait'], next: ['filters-in-the-editor'], also: [{ when: 'you want it in colour and louder', slug: 'make-a-comic-book-effect' }] },
    body: [
      { t: 'answer', text: 'A newspaper photo has four traits: it is **black and white**, its **contrast is flat** (newsprint cannot hold deep blacks or clean whites), it is made of a **fine halftone** (newspapers print at about 85 to 100 lines per inch), and it sits on **off-white paper**. Recreate each as a layer: a Black and white adjustment, Curves with the **Faded film** preset, a Halftone filter with small dots set to Multiply, and a cream colour layer on Multiply at the top, then a little Film Grain. The dots should be just visible at arm\'s length, not the big pop-art dots of a comic.' },
      { t: 'demo', kind: 'effect', effect: 'halftone', caption: 'Pull Dot size down to about 20 to 30 for newsprint. Big dots read as comic or pop art; small ones as a newspaper.' },
      { t: 'h', text: 'The recipe in the Editor' },
      { t: 'steps', items: [
        'Open the photo. From the Layers panel\'s adjustment menu add **Black and white**, then **Curves** and click the **Faded film** preset in Properties. The blacks lift and the whites dim, like ink on newsprint.',
        'Add **Filter, Artistic, Halftone**. Set **Dot Size** to 20 to 30 and **Contrast** to about 45. Set the filter layer\'s blend mode to **Multiply** so its white disappears and only the dots print.',
        'Add a new layer ({{Ctrl+Shift+N}}), fill it with an off-white such as #E9E3D3 using **Edit, Fill…**, drag it to the top and set it to **Multiply**. The whites become paper.',
        'Add **Filter, Enhance, Film Grain** at Amount 10 to 20, and optionally **Filter, Enhance, Blur** at the lowest radius, lowered to 30 per cent opacity, for the softness of cheap paper.',
        'Headline in a condensed serif or a heavy grotesque, set in the same dark grey, and it reads as a clipping.',
      ] },
      { t: 'tip', text: 'For an old, yellowed clipping, make the paper colour warmer (#E4D6B5) and add **Filter, Colour, Sepia** at a low intensity below the halftone. For fresh newsprint, keep the paper nearly grey.' },
      { t: 'h', text: 'Common mistakes' },
      { t: 'list', items: [
        '**Dots too big.** That is a comic or a pop-art print. Newsprint dots are barely visible.',
        '**Pure black and pure white.** Newsprint never had either. The Faded film curve and the paper layer fix both.',
        '**Halftone on Normal.** The dots then sit on white, and the paper tint cannot show through. Multiply.',
      ] },
      { t: 'product', text: 'Halftone, Film Grain, Sepia and Blur as filter layers, the Faded film curve as a preset, and a Multiply colour layer for the paper. Everything stays editable until you export.', label: 'Open the Halftone tool', href: '/tools/halftone' },
      { t: 'faq', items: [
        { q: 'What dot size looks like a newspaper?', a: 'Small: on a 1080 px image, a dot cell of 3 to 4 px, which is Dot Size 20 to 30 in the Editor. At print size, newspapers use about 85 to 100 lines per inch.' },
        { q: 'Can I do it in one click?', a: 'The Halftone tool does the dots in one click and downloads a PNG. The paper tint and the flat contrast take two more layers in the Editor, which is what makes it read as newsprint rather than a halftone.' },
      ] },
      { t: 'try', label: 'Open Effects', href: '/effects?effect=halftone' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'make-a-vintage-photo-effect',
    title: 'The vintage photo effect: fade, grain, warmth, vignette',
    seoTitle: 'Vintage photo effect: fade, grain, warmth and vignette',
    summary: 'Old photos look old for four reasons: lifted blacks, a warm or shifted colour cast, grain, and darker corners. The one-click Vintage effect does the first, second and fourth; the Editor recipe adds grain, light leaks and a print border.',
    description: 'Make a vintage photo effect: faded blacks, a warm cast, film grain and a vignette. One click with the Vintage effect, or a layered recipe in the Editor with light leaks and a print border. Live example.',
    category: 'effects', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Effects · Vintage, Film Grain, Film Burn',
    goals: ['design-effects', 'edit-a-photo'],
    answers: ['vintage photo effect', 'make a photo look old', 'retro photo effect', 'film look photo online', '70s photo effect', 'faded film look', 'polaroid effect', 'old photo filter free'],
    related: ['colour-effects', 'texture-effects', 'add-film-grain', 'adjustment-layers'],
    keywords: 'vintage photo effect retro faded film look old photo warm cast grain vignette light leak film burn polaroid border sepia',
    guide: { before: ['effects-overview'], next: ['add-film-grain', 'colour-effects'], also: [{ when: 'you want black and white newsprint instead', slug: 'make-a-newspaper-photo-effect' }] },
    body: [
      { t: 'answer', text: 'Old prints fade in predictable ways: **blacks lift** to a soft charcoal, **colour shifts warm** (blue fades first), **grain** shows, and **corners darken** from the lens. The **Vintage** effect does the fade, the warmth and the corners in one slider. Add **Film Grain** at a low amount for texture, and **Film Burn** at half opacity if you want light leaks. Keep it subtle: the best vintage looks could pass for a real old print, not a filter.' },
      { t: 'demo', kind: 'effect', effect: 'vintage', caption: 'The Vintage effect: one Intensity slider controls the fade, the warm cast and the corner darkening together.' },
      { t: 'h', text: 'By decade, roughly' },
      { t: 'table', head: ['Look', 'Recipe'], rows: [
        ['1920s to 40s print', 'Black and white adjustment, Sepia at 40 to 60, Film Grain, Vignette'],
        ['1970s colour print', 'Vintage at 60 to 80, Colour balance towards yellow and red, Film Grain'],
        ['1990s snapshot', 'Vintage at 30 to 40, slightly more contrast with Curves, Film Burn at 40 per cent opacity'],
        ['Instant print', 'Vintage at 40, Faded film curve, a white border wider at the bottom'],
      ] },
      { t: 'h', text: 'The layered version in the Editor' },
      { t: 'steps', items: [
        'Open the photo. Add **Curves** and click **Faded film**: the blacks lift and the highlights soften.',
        'Add **Filter, Colour, Vintage** and set Intensity to taste. For more control over the cast, add **Colour balance** and push the shadows towards blue-green and the highlights towards yellow.',
        'Add **Filter, Enhance, Film Grain**: Amount 15 to 25, a small Grain Size. See [Add film grain that looks like film](/learn/add-film-grain).',
        'Optional light leak: **Filter, Enhance, Film Burn**, then lower the filter layer\'s opacity to 40 to 60 per cent.',
        'Optional instant-print border: **Image, Canvas size…**, tick Relative, add 80 px to the width and 260 to the height with the anchor in the top-centre square, then add a new layer, **Edit, Fill…** with an off-white, and drag it to the bottom of the stack.',
      ] },
      { t: 'product', text: 'Vintage, Sepia, Film Grain, Film Burn and Vignette as effects you can try in one click, then stack as filter layers with the Faded film curve underneath.', label: 'Open Vintage in Effects', href: '/effects?effect=vintage' },
      { t: 'faq', items: [
        { q: 'What makes a photo look vintage?', a: 'Lifted blacks, a colour cast (usually warm), grain and darker corners. Soft focus and light leaks help. Heavy scratches and dust usually look like a filter rather than a print.' },
        { q: 'Should I add a sepia tone?', a: 'For anything before about 1950, yes, on a black and white image. Colour photos from the 60s to 90s faded warm rather than brown; use Vintage or Colour balance instead.' },
      ] },
      { t: 'try', label: 'Open Effects', href: '/effects?effect=vintage' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'turn-a-photo-into-a-sketch',
    title: 'Turn a photo into a pencil sketch',
    seoTitle: 'Turn a photo into a pencil sketch, free, in the browser',
    summary: 'Pencil Sketch draws the edges of a photo as grey lines on white. What kind of photo works, how to get clean lines rather than noise, the pen-and-ink alternatives, and how to keep the colour underneath.',
    description: 'Turn a photo into a pencil sketch: raise contrast, soften noise, apply Pencil Sketch, then set it to Multiply to keep colour. Crosshatch and Stipple for pen-and-ink looks. Live example, free, nothing uploaded.',
    category: 'effects', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Effects · Pencil Sketch, Crosshatch, Stipple',
    goals: ['design-effects'],
    answers: ['photo to sketch', 'turn photo into pencil sketch', 'photo to line drawing', 'sketch effect online free', 'convert image to drawing', 'pencil drawing from photo', 'photo to colouring page'],
    related: ['artistic-effects', 'filters-in-the-editor', 'make-a-comic-book-effect', 'adjustment-layers'],
    keywords: 'photo to sketch pencil sketch line drawing edges crosshatch stipple pen ink colouring page multiply contrast noise',
    guide: { before: ['effects-overview'], next: ['artistic-effects'], also: [{ when: 'you want bold ink outlines instead', slug: 'make-a-comic-book-effect' }] },
    body: [
      { t: 'answer', text: 'Apply **Pencil Sketch**: it finds the edges in the photo and draws them as grey lines on white, with flat areas left blank. **Line strength** sets how dark the lines are and how much texture comes through. For clean lines, give it a photo with clear edges and a plain background, raise the contrast first, and soften fine noise (skin texture, grass, fabric) with a slight blur so it does not turn into scribble. For a pen-and-ink look use **Crosshatch** or **Stipple** instead. To keep colour, set the sketch filter layer to **Multiply** over the photo.' },
      { t: 'demo', kind: 'effect', effect: 'sketch', caption: 'Pencil Sketch on a portrait. Low Line strength gives an outline; high brings in hair and fabric texture.' },
      { t: 'h', text: 'What works' },
      { t: 'list', items: [
        '**Clear subjects on plain backgrounds:** products, buildings, portraits against a wall. Busy backgrounds become busy drawings.',
        '**Contrast between parts:** a face lit from one side sketches well; flat, even light gives faint lines.',
        '**Large originals:** Pencil Sketch works pixel by pixel, so a large photo gives finer lines on download than the preview shows.',
      ] },
      { t: 'h', text: 'Clean lines in the Editor' },
      { t: 'steps', items: [
        'Open the photo. Remove a busy background with **Layer, Remove background** and put a white layer underneath if it helps.',
        'Add **Curves**, click **More contrast**. Add a **Blur** adjustment at a low radius to soften skin and fabric texture.',
        'Add **Filter, Artistic, Pencil Sketch**. Adjust **Line strength** until the outlines are there and the texture is not.',
        'For colour under the lines, set the sketch filter layer to **Multiply**. For a colouring page, keep it on Normal and export PNG.',
        'For paper, add a new layer filled with an off-white on Multiply at the top, and a little Film Grain.',
      ] },
      { t: 'h', text: 'Other drawing looks' },
      { t: 'table', head: ['Effect', 'Looks like', 'Setting'], rows: [
        ['Pencil Sketch', 'Grey pencil outlines on white', 'Line strength'],
        ['Crosshatch', 'Ink lines on cream paper, more directions in darker areas', 'Line spacing: tight for fine pen, wide for bold'],
        ['Stipple', 'Tiny ink dots, dense in shadows', 'Dot density, Cell size'],
        ['Edge Detect, inverted', 'Crisp black outlines only', 'Threshold; see the comic book recipe'],
      ] },
      { t: 'product', text: 'Pencil Sketch, Crosshatch, Stipple and Edge Detect run on your device, preview live, and stack as filter layers over the original photo.', label: 'Open Pencil Sketch in Effects', href: '/effects?effect=sketch' },
      { t: 'faq', items: [
        { q: 'Why is my sketch full of scribbles?', a: 'The photo has fine texture (skin pores, grass, fabric) that the edge finder draws. Blur slightly before the sketch filter and lower Line strength.' },
        { q: 'Can I make a colouring page?', a: 'Yes: Pencil Sketch at a medium strength on a photo with a plain background, then a Threshold adjustment above it to make every line solid black on white. Export PNG and print.' },
      ] },
      { t: 'try', label: 'Open Effects', href: '/effects?effect=sketch' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'pixel-sorting-explained',
    title: 'What pixel sorting is and how to use it',
    seoTitle: 'Pixel sorting explained, with a live example',
    summary: 'Pixel sorting rearranges runs of bright pixels by brightness, turning highlights into streaks. What the threshold does, which photos work, how to sort vertically, and how to limit it to one part of the image.',
    description: 'Pixel sorting sorts runs of pixels brighter than a threshold from dark to light, so highlights melt into streaks. What the threshold does, photos that work, vertical sorting and masking it. Live example.',
    category: 'effects', level: 'Intermediate', updated: D, published: D, role: 'supporting',
    feature: 'Effects · Pixel Sort',
    goals: ['design-effects'],
    answers: ['pixel sort', 'pixel sorting effect', 'what is pixel sorting', 'pixel sort online free', 'pixel sort vertical', 'glitch pixel sort', 'pixel sorting generator'],
    related: ['distortion-effects', 'glitch-effect-explained', 'filters-in-the-editor', 'masks'],
    keywords: 'pixel sort sorting glitch art threshold streaks brightness horizontal vertical rotate mask sky',
    guide: { before: ['glitch-effect-explained'], next: ['distortion-effects'], also: [{ when: 'you want the effect only in part of the image', slug: 'masks' }] },
    body: [
      { t: 'answer', text: 'Pixel sorting takes each row of the image, finds runs of pixels brighter than a **threshold**, and sorts each run from dark to light. Bright areas melt into horizontal streaks; dark areas stay as they are. **Lower the threshold** and more of the image sorts, with longer streaks; **raise it** and only the highlights move. Photos with a bright sky, lights, smoke or a light background next to a dark subject work best, because the dark subject survives while the brightness around it flows.' },
      { t: 'demo', kind: 'effect', effect: 'pixelSort', caption: 'Pixel Sort on a stage photo. Drop the threshold and the smoke streaks across the frame; raise it and only the sparks move.' },
      { t: 'h', text: 'Choosing the threshold' },
      { t: 'table', head: ['Threshold', 'Result', 'Good for'], rows: [
        ['70 to 90', 'Only highlights streak; the photo stays readable', 'A subtle glitch on portraits and products'],
        ['45 to 70', 'Skies and light backgrounds melt; the subject survives', 'Posters, album art'],
        ['Under 45', 'Most of the image becomes streaks', 'Abstract backgrounds, textures'],
      ] },
      { t: 'h', text: 'Sort vertically' },
      { t: 'p', text: 'The effect always sorts left to right. For vertical streaks (dripping, falling light), turn the image first and bake the result before turning it back, because a filter layer re-runs on whatever is below it:' },
      { t: 'steps', items: [
        '**Image, Image rotation, Rotate 90° clockwise.**',
        'Add **Filter, Distort, Pixel Sort** and set the threshold.',
        'Select the filter layer and **Layer, Merge down** so the sort becomes pixels.',
        '**Image, Image rotation, Rotate 90° anticlockwise.** The streaks now run vertically.',
      ] },
      { t: 'h', text: 'Sort only part of the image' },
      { t: 'p', text: 'A filter layer can take a mask. Add the Pixel Sort filter, then add a layer mask to it and paint black over the parts that should stay untouched, such as a face. Or select the subject first with **Select, Subject** and use **Mask hiding the selection** on the filter layer, so everything except the subject sorts.' },
      { t: 'product', text: 'Pixel Sort runs on your device with a live threshold, and as a filter layer it can be masked, faded and stacked with RGB Shift or Glitch.', label: 'Open Pixel Sort in Effects', href: '/effects?effect=pixelSort' },
      { t: 'faq', items: [
        { q: 'Why does nothing happen on my photo?', a: 'The threshold is above the brightest part of the image. Lower it until the highlights start to move.' },
        { q: 'Does Randomize change the sort?', a: 'Not in the current version. Pixel sorting is deterministic: the same image and threshold always give the same result.' },
      ] },
      { t: 'try', label: 'Open Effects', href: '/effects?effect=pixelSort' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'add-film-grain',
    title: 'Add film grain that looks like film',
    seoTitle: 'Add film grain that looks like film, not noise',
    summary: 'Grain makes digital images feel printed and hides banding and mild softness. How much to use, why grain size matters more than amount, where to put it in the layer stack, and why it must be judged at the output size.',
    description: 'Add realistic film grain: Film Grain at Amount 10 to 25 with a small grain size, on top of the stack, judged at 100 per cent and output size. Why grain beats noise, and how it fixes banding. Live example.',
    category: 'effects', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Effects · Film Grain, Noise',
    goals: ['design-effects', 'edit-a-photo'],
    answers: ['film grain effect', 'add film grain to photo', 'grain effect online', 'how to add grain to an image', 'grain texture overlay', 'film grain vs noise', 'fix gradient banding with grain'],
    related: ['texture-effects', 'make-a-vintage-photo-effect', 'pixelated-or-blurry', 'filters-in-the-editor'],
    keywords: 'film grain effect add grain texture noise banding analogue print amount grain size randomize output size',
    guide: { before: ['texture-effects'], next: ['make-a-vintage-photo-effect'], also: [{ when: 'a gradient has stripes', slug: 'pixelated-or-blurry' }] },
    body: [
      { t: 'answer', text: 'Use **Film Grain** rather than Noise: grain comes in small clumps like silver in film, where Noise is single-pixel speckle that reads as a digital sensor. Keep **Amount at 10 to 25** and **Grain Size small**; grain that is visible from across the room is too much. Put it **at the top of the stack**, over the photo and over flat colour areas, so everything shares the same texture, and judge it at **100 per cent** at the size you will export. Grain also hides gradient banding and mild softness, which is why printed designs often carry a little on purpose.' },
      { t: 'demo', kind: 'effect', effect: 'grain', caption: 'Film Grain. Randomize changes the pattern without changing its strength; useful when two images side by side should not share a pattern.' },
      { t: 'h', text: 'How much' },
      { t: 'table', head: ['Use', 'Amount', 'Grain size'], rows: [
        ['Hide banding in a gradient or sky', '5 to 10', 'Smallest'],
        ['A tactile finish on flat graphics', '10 to 15', 'Small'],
        ['Film look on a photo', '15 to 25', 'Small to medium'],
        ['Pushed film, gritty poster', '30 to 50', 'Medium to large'],
      ] },
      { t: 'h', text: 'In the Editor' },
      { t: 'steps', items: [
        'Select the top layer, then choose **Filter, Enhance, Film Grain**. It arrives as a filter layer that affects everything below it.',
        'Set Amount and Grain Size from the table. Press {{Ctrl+1}} and check at 100 per cent.',
        'To keep grain off some areas (a logo, a face), add a mask to the filter layer and paint those areas black.',
        'Export PNG or JPG at 90 or more. At low JPG quality, compression smooths the grain back out.',
      ] },
      { t: 'note', text: 'Filter layers re-render at the export size, and settings measured in pixels scale with it, so grain looks the same on a 1× and a 2× export, only finer. Judge it at the size people will see.' },
      { t: 'product', text: 'Film Grain and Noise as filter layers you can mask and fade, with a Randomize control for a fresh pattern, rendered again at the full export size.', label: 'Open Film Grain in Effects', href: '/effects?effect=grain' },
      { t: 'faq', items: [
        { q: 'Film grain or noise?', a: 'Film Grain for a film or print look; its clumps look analogue. Noise for a digital sensor texture or to dither a gradient very finely.' },
        { q: 'Does grain survive Instagram?', a: 'Heavy grain gets smeared by compression and can look like dirt. Keep it light, export at the exact size, and check on a phone.' },
      ] },
      { t: 'try', label: 'Open Effects', href: '/effects?effect=grain' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'make-a-crt-effect',
    title: 'The CRT and scanline look',
    seoTitle: 'CRT and scanline effect: old TV look in the browser',
    summary: 'An old tube screen bulges, has dark scanlines, shows red, green and blue stripes and fades at the edges. The CRT effect does all four; add colour fringing, glow and a vignette for the full broadcast look.',
    description: 'Make a CRT effect: barrel distortion, scanlines, RGB stripes and dark edges in one effect, plus RGB Shift, Bloom and a vignette for the full old-TV look. Flat scanlines without the bulge too. Live example.',
    category: 'effects', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Effects · CRT, Scanlines, RGB Shift',
    goals: ['design-effects'],
    answers: ['crt effect', 'crt filter online', 'old tv effect', 'scanlines effect', 'retro monitor effect', 'vhs effect', '80s tv screen effect', 'crt overlay'],
    related: ['distortion-effects', 'texture-effects', 'glitch-effect-explained', 'filters-in-the-editor'],
    keywords: 'crt effect old tv scanlines barrel distortion rgb stripes vhs retro monitor bloom rgb shift vignette',
    guide: { before: ['glitch-effect-explained'], next: ['distortion-effects'], also: [{ when: 'you want the VHS tracking glitch too', slug: 'glitch-effect-explained' }] },
    body: [
      { t: 'answer', text: 'The **CRT** effect bulges the image outward (**Barrel distortion**), lays dark **scanlines** across it (**Scanline gap** sets their spacing), adds red, green and blue stripes in the columns, and fades the edges to black, which is most of what makes a tube screen read as a tube. For the full broadcast look add a small **RGB Shift** for colour fringing, **Bloom** so the highlights glow, and a **Vignette**. For scanlines on a flat modern display, use the **Scanlines** effect instead, which draws the lines without the bulge.' },
      { t: 'demo', kind: 'effect', effect: 'crt', caption: 'CRT. Barrel distortion at 0 keeps the picture flat; the scanlines and RGB stripes stay.' },
      { t: 'h', text: 'Build the full look in the Editor' },
      { t: 'steps', items: [
        'Open the image. Add **Filter, Distort, RGB Shift** with a small amount (5 to 15) for colour fringing on edges.',
        'Add **Filter, Enhance, Bloom**: a high Brightness cutoff so only the highlights glow.',
        'Add **Filter, Distort, CRT** on top. Barrel distortion 20 to 50, Scanline gap to taste: denser for a small TV, wider for a big one.',
        'Optional: **Filter, Enhance, Vignette** for a deeper tube edge, and a slight **Film Grain** for signal noise.',
        'For text on the screen, put the text layer below the CRT filter so it bends and gets scanlines too.',
      ] },
      { t: 'h', text: 'Related looks' },
      { t: 'table', head: ['Look', 'Effects'], rows: [
        ['Arcade screen', 'CRT with high barrel distortion, Bloom, saturated colours'],
        ['Security camera', 'Black and white adjustment, Scanlines, Noise, a timestamp in a monospace font'],
        ['VHS tape', 'RGB Shift, Glitch at low offset, Film Grain, a slightly washed-out Curves'],
        ['Flat LCD scanlines', 'Scanlines only, Darkness low, Line spacing small'],
      ] },
      { t: 'product', text: 'CRT, Scanlines, RGB Shift, Bloom and Vignette run on your device and stack as filter layers, so you can build the screen once and drop any image or text underneath.', label: 'Open CRT in Effects', href: '/effects?effect=crt' },
      { t: 'faq', items: [
        { q: 'How do I get scanlines without the curve?', a: 'Use the Scanlines effect (in Enhance) instead of CRT, or set CRT\'s Barrel distortion to 0, which keeps the stripes and the dark edges but flattens the picture.' },
        { q: 'Why are the scanlines finer in my download?', a: 'Filter layers re-render at the export size and scale their pixel settings, so the lines keep their look but are drawn with more pixels. Check at 100 per cent at the output size.' },
      ] },
      { t: 'try', label: 'Open Effects', href: '/effects?effect=crt' },
    ],
  },
]
