import type { Article } from '../types'

// Tier 3 long-tail problem pages: one search, one answer, under 600 words, one CTA. Each links up to the guide that
// covers the subject in depth. Facts checked against the guides they link to and the editor source.

const D = '2026-09-27'

export const articles: Article[] = [
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'fix-a-blurry-image',
    title: 'How to fix a blurry image, and when you cannot',
    seoTitle: 'How to fix a blurry image (and when you cannot)',
    summary: 'Three kinds of blur, one of which can be fixed. How to tell them apart in ten seconds, what sharpening does and does not do, and the honest answer about upscaling.',
    description: 'Fix a blurry image: soft focus and light compression respond to sharpening; too few pixels do not. How to tell which you have, the Editor steps, and why upscaling cannot add detail.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Sharpen, Image size',
    goals: ['edit-a-photo'],
    answers: ['how to fix a blurry image', 'image is blurry how to fix', 'make a blurry picture clear', 'unblur an image', 'fix blurry photo online free', 'why is my image blurry', 'how to make image resolution higher', 'can you increase image resolution', 'sharpen a blurry photo'],
    related: ['image-resolution-explained', 'printed-design-looks-blurry', 'crop-and-canvas', 'texture-effects'],
    keywords: 'blurry image fix sharpen unblur resolution upscale pixels soft focus compression artefacts',
    guide: { before: ['image-resolution-explained'], also: [{ when: 'it is a print that came out blurry', slug: 'printed-design-looks-blurry' }] },
    body: [
      { t: 'answer', text: 'It depends which blur you have. **Slightly soft** (focus a touch off, or a small photo shown a bit too big): sharpening helps, and a Sharpen filter at a low amount is the fix. **Compressed** (blocky edges, smeared colour from a screenshot or a messaged JPG): a little sharpening plus a little noise hides it, but the detail is gone. **Too few pixels** (a 400 px image on a 1080 px post): nothing recovers it. Upscaling makes it bigger, not sharper; it invents pixels by blending the ones next to them. The real fix is the original file at its full size, so ask for it before you spend time on the copy.' },
      { t: 'h', text: 'Which blur is it' },
      { t: 'table', head: ['Look at it at 100 per cent', 'What you see', 'Fixable?'], rows: [
        ['Edges are soft but detail is there', 'Focus or slight enlargement', 'Yes, with Sharpen'],
        ['Blocky squares, halos around text, smeared colour', 'JPG compression, often repeated', 'Partly: sharpen a little, add grain, never re-save as JPG'],
        ['Each pixel is a visible square when you zoom', 'Too few pixels for the size', 'No. Get the original or use it smaller'],
        ['Sharp on your phone, soft when placed in a design', 'Placed at a size larger than its pixels', 'Use it at its own size or smaller'],
      ] },
      { t: 'h', text: 'Sharpen it in the Editor' },
      { t: 'steps', items: [
        'Open the image and press {{Ctrl+1}} to see it at 100 per cent. Judge only at this zoom; every other zoom lies.',
        'Choose **Filter, Enhance, Sharpen**. It arrives as a filter layer. Set **Amount** low, 20 to 40, and look at an edge. Stop before halos appear.',
        'For compression damage, add **Filter, Enhance, Noise** at a small amount as well. Fine noise breaks up the blocks and reads as texture rather than damage.',
        'Export as PNG, or JPG at 90 per cent or higher. Every JPG save loses a little more.',
      ] },
      { t: 'p', text: 'Sharpen raises contrast along edges. It makes an image look crisper; it does not add detail that was not captured. Use it once, at the output size, as the last step.' },
      { t: 'h', text: 'About making the resolution higher' },
      { t: 'p', text: '**Image, Image size…** can set a bigger pixel size, and the result is a bigger blurry image. Resampling averages neighbouring pixels to fill the gaps; no new information appears. That is true of every upscaler, including AI ones, which guess plausible detail rather than recover real detail. For a poster, use a photo that has the pixels; [Pixels, dpi and soft images](/learn/image-resolution-explained) has the numbers, and [Why your printed design looks blurry](/learn/printed-design-looks-blurry) the one-minute check.' },
      { t: 'product', text: 'The Sharpen and Noise filters are non-destructive layers, the 100 per cent view is one key, and the Image size dialog tells you the truth about how many pixels you have.', label: 'Open the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Can I unblur a photo?', a: 'Slight softness, yes, with sharpening. Motion blur, missed focus and low pixel counts, no; the detail was never recorded. Ask for the original file.' },
        { q: 'Does Voidcanvas have an AI upscaler?', a: 'No. Its AI tools select, cut out and fill; none of them invents detail in a photo. Upscaling makes an image larger, not sharper, so the guide says so rather than offering a button that pretends otherwise.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'psd-will-not-open',
    title: 'PSD will not open: the five causes and what to ask for',
    seoTitle: 'PSD will not open? The five causes and the fix for each',
    summary: 'A PSD that will not open is usually one of five things: the wrong kind of file, a huge file, an old or unusual save mode, a broken download, or a tool that does not read PSD at all. How to tell, and what to ask the sender for.',
    description: 'PSD not opening: check it is really a PSD, its size, the colour mode and bit depth it was saved in, and whether the download completed. What to ask the sender for, and how to open it in the browser.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Import',
    goals: ['work-with-psd'],
    answers: ['psd not opening', 'psd file will not open', 'cannot open psd file', 'psd file corrupted', 'psd won\'t open in photoshop', 'how to open a psd that will not open', 'psb file open', 'psd opens blank'],
    related: ['open-a-psd-file-online-free', 'import-psd-and-pdf', 'edit-a-psd-without-photoshop', 'troubleshooting'],
    keywords: 'psd not opening corrupted psb large file cmyk 16 bit 32 bit download incomplete compatibility maximize',
    guide: { before: ['open-a-psd-file-online-free'], next: ['import-psd-and-pdf'], also: [{ when: 'it opened but the fonts are wrong', slug: 'missing-fonts-in-a-psd' }] },
    body: [
      { t: 'answer', text: 'Work through five causes in order. **1. It is not a PSD**: a .psb (large document format), an .ai or .indd renamed, or a PSD inside a zip. **2. It is very large**: a multi-gigabyte file or one over 30,000 px on a side can exhaust memory in a browser or a laptop. **3. It was saved in an unusual mode**: CMYK, Lab, Duotone, 16- or 32-bit, or without "Maximize compatibility", which many readers need. **4. The download did not finish**: compare the size on disk with the size the sender sees. **5. The tool does not read PSD**: previewers and some editors show only the flattened preview or nothing. In the Voidcanvas Editor, drop the file on the start screen; if it opens with a report, read the report; if it does not open, the message says which of these it hit.' },
      { t: 'h', text: 'Check each one' },
      { t: 'table', head: ['Cause', 'How to tell', 'Fix or ask for'], rows: [
        ['Not really a PSD', 'Extension is .psb, .ai, .indd, .zip; or the icon is wrong', 'Ask for a PSD (or, for .psb, a version under 30,000 px saved as PSD). Unzip first.'],
        ['Too large', 'Hundreds of MB or more; thousands of layers; very large canvas', 'Ask for a flattened copy plus the layers you need, or a version at a smaller pixel size.'],
        ['Unusual mode', 'Opens blank, wrong colours, or an error about mode or depth', 'Ask for RGB, 8-bit, with Maximize compatibility on. The Editor opens 16-bit as 8-bit and converts CMYK, but 32-bit and Lab need converting first.'],
        ['Incomplete download', 'File size smaller than expected; error mentions end of file', 'Download again; use a link rather than an email attachment for big files.'],
        ['Tool cannot read it', 'Every PSD fails, not just this one', 'Use an editor that reads PSD layers: the Voidcanvas Editor opens them in the browser.'],
      ] },
      { t: 'h', text: 'Open it in the browser' },
      { t: 'steps', items: [
        'Go to [the Editor](/editor) and drop the file on **Open a photo**, or press {{Ctrl+O}}.',
        'If it opens, an **Opened** report may list what was kept, changed or left out. That report is the answer to "what happened to my file".',
        'If it does not open, note the message and the file size, and send the sender the row from the table above that matches.',
      ] },
      { t: 'product', text: 'The Editor reads PSD layers on your device and tells you what it changed, instead of failing silently. If it cannot open a file, the message says why.', label: 'Try the file in the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'How do I open a PSB file?', a: 'PSB is the large-document variant and most tools outside Photoshop do not read it. Ask for the file saved as PSD; if it is over 30,000 px on a side, ask for a smaller version or a flattened copy plus the layers you need.' },
        { q: 'The PSD opens but everything is on one layer. Why?', a: 'It was saved without Maximize compatibility, or your tool only reads the flattened preview. Ask for a re-save with compatibility on, and open it in an editor that reads layers.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'convert-psd-to-png',
    title: 'Convert a PSD to PNG (with transparency) without Photoshop',
    seoTitle: 'PSD to PNG with transparency, free, in the browser',
    summary: 'Open the PSD, hide what you do not want, export a PNG. Transparency is kept if the design has no background. The steps, the one setting that matters, and how to get single layers out.',
    description: 'Convert PSD to PNG without Photoshop: open it in the browser, hide the background layer, export a PNG with transparency at 1×, 2× or a custom size. Single layers too. Nothing is uploaded.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Export',
    goals: ['work-with-psd'],
    answers: ['psd to png', 'convert psd to png', 'psd to png with transparency', 'psd to jpg', 'export png from psd without photoshop', 'save psd as png online', 'extract layers from psd'],
    related: ['open-a-psd-file-online-free', 'export-for-screen', 'make-a-transparent-png', 'file-formats'],
    keywords: 'psd to png convert transparency export layers jpg webp online free no photoshop',
    guide: { before: ['open-a-psd-file-online-free'], next: ['export-for-screen'], also: [{ when: 'you need to edit it first', slug: 'edit-a-psd-without-photoshop' }] },
    body: [
      { t: 'answer', text: 'Open the PSD in [the Editor](/editor) (drop it on the start screen), hide any layer you do not want in the PNG, press {{Ctrl+E}}, choose **PNG**, pick a size and download. If the design has no background colour, the empty areas are transparent; if it has one, tick **Leave out the background colour** to drop it. JPG and WebP are in the same dialog. Nothing is uploaded and there is no account.' },
      { t: 'h', text: 'Steps' },
      { t: 'steps', items: [
        'Drop the PSD on **Open a photo** in [the Editor](/editor), or press {{Ctrl+O}}. Read the **Opened** report if one appears.',
        'In the Layers panel, click the eye next to any layer or group you want left out, such as a white background layer or a mockup.',
        'Press {{Ctrl+E}}. Choose **PNG**. Choose **1×** for the file at its own pixel size, **2×** for double, or a custom width. Text and shapes are redrawn sharp at any size; photos are resampled.',
        'If the dialog shows **Leave out the background colour**, tick it for a transparent PNG.',
        'Press **Download**. A version named Exported is saved, so you can always find the state you sent.',
      ] },
      { t: 'h', text: 'Single layers and variations' },
      { t: 'list', items: [
        '**One layer as its own PNG:** hide everything else and export. For a tight crop, choose **Image, Trim transparent edges** first.',
        '**Several versions:** export, change the visible layers, export again. Each download is a version, so nothing is lost.',
        '**JPG for photos:** same dialog, choose JPG, quality 80 to 90. JPG has no transparency; empty areas become white.',
        '**Smaller for the web:** WebP keeps transparency at a smaller size than PNG.',
      ] },
      { t: 'product', text: 'Open, hide, export. PNG with transparency, JPG and WebP, at any size, from any PSD the Editor can open, with the file staying on your device.', label: 'Open a PSD in the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Why is my PNG background white instead of transparent?', a: 'The PSD has a filled background layer or the design has a background colour. Hide the layer, or tick Leave out the background colour in the export dialog. JPG can never be transparent.' },
        { q: 'Can I export every layer as a separate PNG at once?', a: 'Not in one click. Hide and export per layer, or copy a layer into a new design and export that. Resize to every format is for one design in many sizes, not one design into its layers.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'missing-fonts-in-a-psd',
    title: 'Missing fonts in a PSD: replace them or load the file',
    seoTitle: 'Missing fonts in a PSD: replace, substitute or load the file',
    summary: 'When a PSD uses a font your computer does not have, the text still opens but looks wrong. What the dialog offers, where to get the font, how to choose a stand-in that keeps the layout, and how the font travels with the design afterwards.',
    description: 'Missing fonts in a PSD: the Editor lists each one and how many layers use it. Load the font file (.ttf, .otf, .woff, .woff2), pick a Google Font with a similar width, or keep a stand-in. The file is saved inside the design.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Character panel',
    goals: ['work-with-psd'],
    answers: ['psd missing fonts', 'missing font in psd', 'font substitution psd', 'psd fonts not showing', 'how to add a font to a psd', 'replace missing font', 'font missing when opening file'],
    related: ['import-psd-and-pdf', 'type', 'edit-a-psd-without-photoshop', 'typography-fundamentals'],
    keywords: 'missing fonts psd replace substitute add font file ttf otf woff google fonts stand-in layout width',
    guide: { before: ['open-a-psd-file-online-free'], next: ['type'], also: [{ when: 'you want to pick a good pairing', slug: 'typography-fundamentals' }] },
    body: [
      { t: 'answer', text: 'When you open a PSD that uses a font this device cannot find, **Some fonts are missing** lists each font and how many text layers use it. Three ways out: **Add font file** loads the real font from your computer (.ttf, .otf, .woff or .woff2) and saves it inside the design so it travels with it; **pick a replacement** from Google Fonts, choosing one of similar width so lines do not rewrap; or **keep a stand-in** for now and fix it later from the Character panel. Ask the sender for the font files first; the layout was set in that font and any substitute changes it a little.' },
      { t: 'h', text: 'Which option when' },
      { t: 'table', head: ['Situation', 'Do'], rows: [
        ['You have, or can get, the font file', 'Add font file. Exact result; the file is stored in the design. Check the licence allows use on this project.'],
        ['The font is on Google Fonts', 'Pick it from the list. Many commercial fonts have close Google relatives (Helvetica to Inter or Arimo, Futura to Jost, Garamond to EB Garamond).'],
        ['You only need to export the design as is', 'Keep the stand-in and check every text layer at 100 per cent before exporting. Lines may wrap differently.'],
        ['You will hand the file back to someone with the font', 'Keep the stand-in and do not touch the text layers; the font name is preserved in the layer.'],
      ] },
      { t: 'h', text: 'Choose a stand-in that keeps the layout' },
      { t: 'list', items: [
        'Match **width** before style. A wider substitute pushes text to a new line; a narrower one leaves gaps.',
        'Match **x-height** for body text so the blocks stay the same visual size.',
        'Match **weight**: a bold headline needs a family with a 700 weight.',
        'After substituting, walk through each text layer at 100 per cent and fix wraps by nudging size or tracking, not by retyping.',
      ] },
      { t: 'h', text: 'Fix it later' },
      { t: 'p', text: 'Select a text layer, open the **Character** panel (Window menu) and choose the font, or press **Add a font file from this device**. A font file added once is available to every text layer in that design and is saved inside it, so the design opens correctly on another device. It is never requested from Google.' },
      { t: 'product', text: 'The missing-fonts dialog names each font and its layer count, takes a font file in one click, and keeps that file inside the design. Google Fonts are there when you do not have the file.', label: 'Open the PSD in the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Where do I get the missing font?', a: 'From whoever made the PSD, since they had it. Otherwise from the foundry that sells it, or a Google Font that is close. Fonts are licensed; a file from a random download site is a legal and often a quality problem.' },
        { q: 'Will the substitute change the design?', a: 'Slightly, always. Different fonts have different widths, so lines wrap and blocks grow or shrink. Match width first and check each text layer at 100 per cent.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'crop-an-image-into-a-circle',
    title: 'Crop an image into a circle (transparent PNG)',
    seoTitle: 'Crop an image into a circle and export a transparent PNG',
    summary: 'A circle crop is an ellipse selection turned into a mask, then a PNG export with transparency. Four steps, plus how to get a soft edge, a border, or a perfectly centred circle.',
    description: 'Crop an image into a circle: Ellipse select with Shift, Mask from selection, Trim transparent edges, export PNG. Add a stroke for a border or feather for a soft edge. Free, in the browser.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Selections, Masks',
    goals: ['edit-a-photo', 'social-content'],
    answers: ['crop image into circle', 'crop photo into a circle', 'circle crop online', 'round profile picture maker', 'make an image round', 'circular crop transparent png', 'how to crop a picture in a circle'],
    related: ['selections', 'masks', 'make-a-transparent-png', 'export-for-screen'],
    keywords: 'circle crop round image ellipse select mask transparent png profile picture border stroke feather',
    guide: { next: ['masks', 'make-a-transparent-png'], also: [{ when: 'you want the background gone as well', slug: 'remove-background' }] },
    body: [
      { t: 'answer', text: 'Open the image, press {{Shift+M}} for **Ellipse select**, hold Shift and drag a circle over the part you want, then click **Mask from selection** in Properties. Choose **Image, Trim transparent edges** to cut the canvas to the circle, press {{Ctrl+E}}, choose **PNG** and download. The corners are transparent. Nothing is uploaded.' },
      { t: 'h', text: 'Steps' },
      { t: 'steps', items: [
        'Open the photo in [the Editor](/editor). If it is the background layer, it is already a normal layer here; nothing to unlock.',
        'Press {{M}} then {{Shift+M}} to reach **Ellipse select**. Start dragging, then hold **Shift** to keep it a circle. Release when the face or subject sits inside; if it is off, draw it again, or move the photo under it later with the Move tool.',
        'In Properties under **Mask**, click **Mask from selection**. The outside is hidden, not deleted, so you can move the photo inside the circle with the Move tool while the mask stays put.',
        'Choose **Image, Trim transparent edges** so the canvas fits the circle exactly.',
        'Press {{Ctrl+E}}, choose **PNG**, download. JPG would fill the corners with white.',
      ] },
      { t: 'h', text: 'Variations' },
      { t: 'list', items: [
        '**Perfectly centred circle:** after masking, select the layer and use **Layer, Align** to centre it on the canvas, or read the X, Y, W and H boxes in Properties and set them by hand.',
        '**Soft edge:** set **Feather** in the options bar to 10 to 30 px before drawing the selection, or **Select, Modify, Feather…** after.',
        '**Border:** add a **Stroke** layer style to the masked layer (Layer styles, Stroke, position Inside) in the colour you want. It follows the circle.',
        '**Exact size for a profile picture:** after trimming, **Image, Image size…** to 400 × 400 or whatever the platform wants. Most platforms crop to a circle themselves, so a square export with the subject centred is often enough.',
      ] },
      { t: 'product', text: 'Ellipse select, a mask that hides rather than deletes, trim to content and a transparent PNG export. The photo stays movable inside the circle until you export.', label: 'Open the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Why are the corners white, not transparent?', a: 'You exported a JPG, or the design has a background colour. Export PNG and, if the checkbox appears, tick Leave out the background colour.' },
        { q: 'Can I change which part of the photo shows?', a: 'Yes. The mask hides the outside; it does not crop the pixels. Select the layer, unlink the mask if needed, and drag the photo with the Move tool.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'make-a-transparent-png',
    title: 'Make a transparent PNG',
    seoTitle: 'Make a transparent PNG: remove the background and export',
    summary: 'Transparent means no background layer and a PNG or WebP export. How to get there from a photo, a logo on white, or a design with a background colour, and why the checkerboard sometimes still exports white.',
    description: 'Make a transparent PNG: remove or hide the background, then export PNG (or WebP) rather than JPG. For a logo on white use Remove background or Magic wand; for a design tick Leave out the background colour.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Remove background, Export',
    goals: ['edit-a-photo', 'build-a-brand'],
    answers: ['transparent png', 'make a transparent png', 'how to make background transparent', 'remove white background from logo', 'png transparent background online', 'export with transparent background', 'why is my png not transparent'],
    related: ['remove-background', 'export-for-screen', 'crop-an-image-into-a-circle', 'file-formats'],
    keywords: 'transparent png background remove white logo checkerboard export webp jpg magic wand',
    guide: { before: ['remove-background'], next: ['export-for-screen'], also: [{ when: 'it is a photo of a person or product', slug: 'remove-background' }] },
    body: [
      { t: 'answer', text: 'Two things make a PNG transparent: **nothing behind the subject** in the design, and **PNG or WebP** as the export type (JPG cannot be transparent). For a photo, **Layer, Remove background** hides the background with a mask, on your device. For a logo on white, the **Magic wand** ({{W}}, then click the white) plus **Mask hiding the selection** does it in two clicks. For a design that has a background colour, press {{Ctrl+E}}, choose PNG and tick **Leave out the background colour**. The checkerboard on the canvas means transparent; white means a layer or a colour is still there.' },
      { t: 'h', text: 'Three starting points' },
      { t: 'table', head: ['You have', 'Do', 'Notes'], rows: [
        ['A photo of a person, product or animal', '**Layer, Remove background** (or the button in Properties)', 'A model runs in your browser; the first use downloads it once. Use the any-subject model for objects. Tidy the mask with a brush if needed.'],
        ['A logo or graphic on a plain white background', 'Magic wand ({{W}}), click the white, Shift-click any leftover patches, then Layer, Layer mask, **Mask hiding the selection**', 'Lower Tolerance if the wand eats into the logo. Anti-aliased edges keep a faint white fringe; Select, Modify, Contract by 1 px before masking removes it.'],
        ['A design with a background colour', 'Nothing in the design; at export tick **Leave out the background colour**', 'Or set the design\'s background to none in Properties with no layer selected.'],
      ] },
      { t: 'h', text: 'Export' },
      { t: 'steps', items: [
        'Press {{Ctrl+E}}. Choose **PNG** (or **WebP** for a smaller web file). Not JPG.',
        'If **Leave out the background colour** is shown, tick it.',
        'Optionally **Image, Trim transparent edges** first, so the file is no bigger than the subject.',
        'Download. Open the file on a dark page to check; a white fringe means the mask needs contracting by a pixel.',
      ] },
      { t: 'product', text: 'Background removal runs on your device, the magic wand handles logos, and the export dialog says plainly which formats keep transparency.', label: 'Open the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Why is my PNG still white?', a: 'Either a background layer is still visible, the design has a background colour and the checkbox was not ticked, or you exported JPG. Check the canvas shows the checkerboard, then export PNG.' },
        { q: 'Does removing the background upload my photo?', a: 'No. The model is downloaded to your browser once and runs there. You can do it with Wi-Fi off after the first time.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'outline-text',
    title: 'Outline text so it reads on any photo',
    seoTitle: 'Outline text so it reads on any photo (and hollow text)',
    summary: 'Two ways to outline text, when to use each, the width that reads without looking like a meme, and hollow outlined letters with Fill at zero.',
    description: 'Outline text in the browser: the quick Outline in Properties, or a Stroke layer style with position and colour control. Widths that read, hollow text with Fill 0, and the alternatives to an outline.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Type, Layer styles',
    goals: ['social-content', 'learn-design'],
    answers: ['how to outline text', 'outline text online', 'add a border to text', 'stroke text', 'hollow text outline', 'text outline for thumbnail', 'make text stand out on a photo', 'white outline around text'],
    related: ['type', 'layer-styles', 'typography-fundamentals', 'designing-for-social'],
    keywords: 'outline text stroke border hollow fill opacity thumbnail readable photo width',
    guide: { before: ['type'], next: ['layer-styles'], also: [{ when: 'the real problem is the photo behind it', slug: 'designing-for-social' }] },
    body: [
      { t: 'answer', text: 'Select the text layer and, in Properties, click **Add** next to **Outline**, pick a colour and set **Outline width**. That is the quick way. For control over where the stroke sits, use a **Stroke** layer style instead: position **Outside** keeps the letter shapes intact, **Inside** keeps the text the same size, and the style follows the text when you retype it. For hollow letters, add a Stroke and set **Fill opacity** to 0. Outlines read best at 2 to 4 per cent of the text size (a 100 px headline takes a 2 to 4 px stroke); thicker starts to look like a meme, so before going thicker try a darker photo or a band behind the text.' },
      { t: 'h', text: 'Two methods' },
      { t: 'table', head: ['Method', 'Where', 'Good for', 'Limits'], rows: [
        ['Outline in Properties', 'Text layer, Properties, Outline: Add', 'Quick captions and labels', 'One colour, centred on the edge, no position control'],
        ['Stroke layer style', 'Layer styles, Stroke: colour, width, position Inside, Centre or Outside', 'Headlines, thumbnails, hollow text, stacking with a shadow', 'Slightly more clicks'],
      ] },
      { t: 'h', text: 'Steps with a layer style' },
      { t: 'steps', items: [
        'Select the text layer. Open **Layer styles** (Properties, or double-click the layer in the Layers panel).',
        'Add **Stroke**. Set the colour (white or black almost always), the width, and **Position: Outside** so the letterforms are not eaten.',
        'For more separation from the photo, add **Drop shadow** as well: small distance, size 10 to 20, opacity 40 to 60.',
        'For hollow text, under **Blending options** set **Fill opacity** to 0 per cent. The letters vanish and the stroke stays.',
        'Retype or resize the text at any point; the style follows.',
      ] },
      { t: 'h', text: 'Before you outline, consider' },
      { t: 'list', items: [
        'Darken the photo under the text with a **Curves** or **Black and white** adjustment layer clipped to a rectangle, or a **Gradient overlay** on a shape behind the text.',
        'Put the text on a flat band or box. It reads at any size and looks designed rather than defended.',
        'Move the text to the quietest part of the photo. Outlines fix contrast; they do not fix a busy background.',
      ] },
      { t: 'product', text: 'Outline and shadow on every text layer in Properties, and full layer styles (Stroke with position, Drop shadow, glows) that follow the text as you edit. The Outline and Sticker presets are one click.', label: 'Open the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'How thick should a text outline be?', a: 'About 2 to 4 per cent of the text size: 2 to 4 px on a 100 px headline, 1 px on 30 px captions. If that is not enough, the fix is the photo behind the text, not a thicker stroke.' },
        { q: 'How do I make hollow outlined text?', a: 'Add a Stroke layer style, then set Fill opacity to 0 in Blending options. The stroke stays at full strength while the letters go transparent.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'put-text-on-a-path',
    title: 'Put text on a curve or a path',
    seoTitle: 'Put text on a curve or a path in the browser',
    summary: 'Text along a circle, an arc or any curve: draw the path, click it with the Type tool, then adjust the start, the lift and the side. Three common shapes and the spacing fix that makes curved text readable.',
    description: 'Put text on a path: draw a circle or a curve with the Shape or Pen tools, click the outline with the Type tool, then set Start along the path, Lift off the path and Flip side. Badge, arc and wave examples.',
    category: 'editor', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · Type on a path',
    goals: ['learn-design', 'build-a-brand'],
    answers: ['how to make text on a path', 'curved text', 'text in a circle', 'text on a curve online', 'arc text', 'type on a path', 'wrap text around a circle', 'circular text for a logo'],
    related: ['type', 'shapes-and-pen', 'design-a-poster-with-no-photo', 'layer-styles'],
    keywords: 'text on a path curved text circle arc wave badge logo type tool pen curvature start lift flip tracking',
    guide: { before: ['type'], next: ['shapes-and-pen'], also: [{ when: 'it is for a whole poster', slug: 'design-a-poster-with-no-photo' }] },
    body: [
      { t: 'answer', text: 'Draw the path first, then type on it. For a circle: press {{U}}, choose **Ellipse**, Shift-drag a circle, and click **Remove** next to **Fill** in Properties so it is invisible. For a curve: press {{P}}, choose the **Curvature pen** with {{Shift+P}}, set the options bar to **Path**, and click a few points. Then press {{T}} and click on the shape\'s outline or the selected path; the text flows along it. Properties gains **Start along the path**, **Lift off the path**, **Flip side**, **Edit the path** and **Release from path**. Widen the tracking a little: letters on a curve crowd on the inside.' },
      { t: 'h', text: 'Three shapes' },
      { t: 'table', head: ['You want', 'Path', 'Settings'], rows: [
        ['A badge: words around the top of a circle, more around the bottom', 'A circle (Ellipse, Shift-drag, Fill removed)', 'Type the top words; set Start so they are centred at the top. Duplicate the text layer for the bottom words and Flip side so they read the right way up. Lift the top text slightly off the path.'],
        ['An arc over a headline', 'A wide, shallow curve with the Curvature pen (three clicks)', 'Centre with Start; keep the arc shallow, under about 20 degrees of bend, or the letters lean visibly.'],
        ['A wave', 'An S-curve with the Curvature pen (four or five clicks)', 'Keep the waves long and gentle; short waves make letters collide.'],
      ] },
      { t: 'h', text: 'Steps' },
      { t: 'steps', items: [
        'Draw the path with the Shape tool ({{U}}) or the Pen family ({{P}}, {{Shift+P}} to cycle to the Curvature pen) in **Path** mode.',
        'Press {{T}} and click exactly on the outline or path. The cursor changes when it is over it.',
        'Type. Set font and size in the **Character** panel. Add 20 to 60 units of **Tracking** so the inside of the curve does not jam.',
        'In Properties, drag **Start along the path** to slide the text, **Lift off the path** to raise it above or below the line, **Flip side** to put it on the other side of the path.',
        '**Edit the path** reshapes the curve with the text following; **Release from path** turns it back into straight text.',
      ] },
      { t: 'product', text: 'Type on any shape or pen path, with start, lift and side as sliders and the path still editable afterwards. The text stays editable text.', label: 'Open the Editor', href: '/editor' },
      { t: 'faq', items: [
        { q: 'Why does the text sit inside the circle instead of outside?', a: 'Flip side. It moves the text to the other side of the path, and the baseline faces the other way.' },
        { q: 'Can I make the bottom text read left to right too?', a: 'Yes: use a second text layer for the bottom words and Flip side on that one, then slide it with Start along the path. That is how badges are set.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'youtube-thumbnail-size',
    title: 'YouTube thumbnail size and the three legibility rules',
    seoTitle: 'YouTube thumbnail size (1280 × 720) and the 3 rules that work',
    summary: '1280 × 720, 16:9, under 2 MB. The number is easy; the thumbnail is seen at 200 px wide, which is where most fail. Three rules with numbers, the preset, and the export settings.',
    description: 'YouTube thumbnail size is 1280 × 720 px (16:9), JPG or PNG under 2 MB. Design for 200 px wide: three words, one face, one bright colour, text at 120 px or larger. Preset and export settings.',
    category: 'craft', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Editor · YouTube preset',
    goals: ['social-content'],
    answers: ['youtube thumbnail size', 'youtube thumbnail dimensions', 'thumbnail size for youtube 2026', 'youtube thumbnail text size', 'how to make a youtube thumbnail', 'best photoshop alternative for youtube thumbnails', 'youtube thumbnail maker free no watermark', 'thumbnail resolution'],
    related: ['size-presets', 'social-media-sizes-and-safe-zones', 'outline-text', 'remove-background'],
    keywords: 'youtube thumbnail size 1280 720 16:9 2mb legibility 200px face text size preset export jpg',
    guide: { before: ['social-media-sizes-and-safe-zones'], next: ['outline-text', 'remove-background'], also: [{ when: 'you want every size in one place', slug: 'size-presets' }] },
    body: [
      { t: 'answer', text: '**1280 × 720 px**, 16:9, JPG or PNG under 2 MB. That is the file. The design problem is that it is shown at about 200 to 400 px wide in a list next to twenty others, so: **three words maximum**, set at 120 px or larger on the 1280 px canvas with an outline or a band; **one face or one object**, big, cut out and placed on a flat or blurred background; **one bright colour** that the competing thumbnails are not using. The duration badge covers the bottom right corner. Test by shrinking the canvas to the size of a postage stamp; if the words still read, publish.' },
      { t: 'h', text: 'The three rules, with numbers' },
      { t: 'table', head: ['Rule', 'Number', 'Why'], rows: [
        ['Three words', 'Headline 120 to 200 px tall on the 1280 canvas, heavy weight, outline or band', 'At 200 px wide the canvas is shrunk 6×; 120 px becomes 19 px, which is the smallest that reads in a list.'],
        ['One face or object', 'Filling at least a third of the height; eyes in the upper half', 'Faces get clicks; small faces get nothing. Cut it out so it pops off the background.'],
        ['One bright colour', 'Background or a band in a colour the neighbours are not using; text in white or black', 'The list is the competition. Contrast with it, not within it.'],
      ] },
      { t: 'h', text: 'Make it' },
      { t: 'steps', items: [
        'Open the [YouTube preset](/editor?preset=yt) (1280 × 720).',
        'Place the photo ({{Ctrl+Shift+P}}), then **Layer, Remove background**. Scale the cut-out large, to one side, with **Free transform** ({{Ctrl+T}}).',
        'Fill the background with a flat colour or a blurred, darkened copy of the photo (duplicate, **Filter, Enhance, Blur**, then a **Curves** adjustment to darken).',
        'Type the three words. Character panel, size 140 px, weight 800. Add a **Stroke** layer style, 6 px, Outside, or put the words on a flat band.',
        'Keep the bottom right 200 × 80 px clear for the duration. Zoom out until the canvas is stamp-sized and check the words.',
        'Press {{Ctrl+E}}, choose **JPG** at 90 per cent (or PNG if the file stays under 2 MB), size 1×, download.',
      ] },
      { t: 'product', text: 'A YouTube preset, on-device background removal, layer styles for the outline and a JPG export at the right size. No watermark, no account.', label: 'Start a thumbnail', href: '/editor?preset=yt' },
      { t: 'faq', items: [
        { q: 'Should a thumbnail be 1280 × 720 or 1920 × 1080?', a: '1280 × 720 is what YouTube asks for and is displayed at a fraction of that. 1920 × 1080 is accepted and resized down; it gains nothing except file size. Stay under 2 MB either way.' },
        { q: 'What text size is readable on a thumbnail?', a: 'On the 1280 px canvas, 120 px or larger for the main words. Anything under 80 px disappears in the list view on a phone.' },
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor?preset=yt' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'file-naming-and-versioning-for-design-work',
    title: 'File naming and versioning for design work',
    seoTitle: 'File naming and versioning for design work (no more final_v3)',
    summary: 'One naming pattern, one rule for when a number goes up, and one place versions live. The scheme, why it is in that order, what to do with client edits, and how Studio applies it for you.',
    description: 'A file naming and versioning scheme for designers: client_job_format_version, lower case, hyphens; the version goes up on every send; versions live with the design, not in the file name.',
    category: 'studio', level: 'Beginner', updated: D, published: D, role: 'supporting',
    feature: 'Studio · Deliver',
    goals: ['client-project', 'work-faster'],
    answers: ['file naming convention for designers', 'design file versioning', 'how to name design files', 'versioning explained', 'how designers organise files', 'final final v2 naming', 'version control for graphic design', 'naming convention for deliverables'],
    related: ['delivering-files', 'templates-and-versions', 'run-a-client-design-project', 'get-client-feedback-you-can-act-on'],
    keywords: 'file naming versioning convention client job format version lowercase hyphens final v2 deliverables',
    guide: { before: ['run-a-client-design-project'], next: ['delivering-files', 'templates-and-versions'], also: [{ when: 'the versions are for client rounds', slug: 'get-client-feedback-you-can-act-on' }] },
    body: [
      { t: 'answer', text: 'Name every file **client_job_format_version**, all lower case, spaces as hyphens, underscores between the four parts: `lekki-nights_launch_a3-poster_v2.pdf`. The version number goes up **every time anything leaves you**, whether to the client or the printer, and never goes back down. "Final" is not a version. Versions themselves live with the design (restore points you can go back to), not as copies of the file with longer names. Studio names delivered files this way for you and uses the review version number, so the client, the printer and you are all talking about the same v3.' },
      { t: 'h', text: 'The pattern, and why that order' },
      { t: 'table', head: ['Part', 'Example', 'Why it is there, and in this position'], rows: [
        ['client', 'lekki-nights', 'Sorts every job for one client together in any folder or search.'],
        ['job', 'launch', 'Inside a client, sorts by job. Short: the folder can hold the long name.'],
        ['format', 'a3-poster, instagram-post, story', 'The deliverable. A person opening the zip knows what each file is without opening it.'],
        ['version', 'v2', 'Last, so files of one format sort in order. Two digits (v02) if you expect more than nine sends.'],
        ['extension', '.pdf, .png, .jpg', 'The file type does the rest; do not put "print" or "web" in the name when the extension and format already say it.'],
      ] },
      { t: 'p', text: 'Lower case and hyphens survive email, WhatsApp, Windows, macOS, web servers and printers\' upload forms. Spaces, capitals, ampersands and accents do not always.' },
      { t: 'h', text: 'When the number goes up' },
      { t: 'list', items: [
        'On every send. If the client saw v2, the next thing they see is v3, even if the change was one comma. Otherwise two different files share a name and the wrong one gets printed.',
        'Not while you work. Internal saves are versions inside the design, not new file names.',
        'Client edits after approval start a new version and, if they are more than a typo, a new round.',
        'Delivered files carry the version that was approved. If v3 was approved, the print PDF is v3.',
      ] },
      { t: 'h', text: 'Where versions live' },
      { t: 'p', text: 'A version is a restore point for one design. Keep them inside the tool, where they carry a thumbnail, a date and a label, and restore or branch from any of them. In the Editor, **File, Save a version** ({{Ctrl+Alt+S}}) makes one, exports make one automatically, and **File, Version history…** lists them. In Studio, the **Review** tab holds one numbered version per round with what changed and the client\'s reply. Copies of files named `poster-final-FINAL-2.psd` are versions without any of that information.' },
      { t: 'product', text: 'Studio names every delivered file client_job_format_version from the job itself and the approved review version, zips them with a delivery note, and keeps the review versions numbered. The Editor keeps restore points inside each design.', label: 'Open Studio', href: '/studio' },
      { t: 'faq', items: [
        { q: 'Should I put the date in the file name?', a: 'Only when several deliveries of the same format happen on different dates with no version change, which the version number already prevents. Dates belong in the delivery note; the version is what people quote back to you.' },
        { q: 'What about internal drafts?', a: 'They are versions inside the design, saved with a label, not files. When one goes out, it gets the next version number.' },
      ] },
      { t: 'try', label: 'Open Studio', href: '/studio' },
    ],
  },
]
