import type { Article } from '../types'

export const articles: Article[] = [
  // ─── Keyboard shortcuts ───────────────────────────────────────────
  {
    slug: 'keyboard-shortcuts',
    title: 'Every keyboard shortcut in Voidcanvas',
    summary: 'Every shortcut in the Editor, grouped by menu, plus tool keys, modifier keys, touch gestures and the keys that work in Effects and Studio.',
    category: 'reference',
    level: 'Beginner',
    updated: '2026-09-25',
    related: ['command-palette-and-menus', 'editor-tour', 'shapes-and-pen', 'designing-on-a-phone'],
    keywords: 'hotkeys keys keyboard cheat sheet shortcuts list photoshop keys mac cmd option tool keys modifier',
    body: [
      { t: 'p', text: 'This page lists every keyboard shortcut Voidcanvas has, taken from the same list the menus and the command palette read. Learn the tool keys and the handful of Ctrl shortcuts you use daily first: they save more time than anything else.' },
      { t: 'note', text: 'On a Mac, use Cmd wherever this page says Ctrl, and Option wherever it says Alt. The menus show the Mac symbols for you.' },
      { t: 'p', text: 'Two ways to look a shortcut up without leaving the Editor: press {{?}} for the shortcut sheet (it has a search box), or press {{Ctrl+K}} to search every action by name. Shortcuts pause while you are typing in a text box or field, so typing a V into a layer name never switches tools.' },
      { t: 'try', label: 'Open the Editor', href: '/editor' },

      { t: 'h', text: 'File' },
      { t: 'keys', rows: [
        ['Ctrl+Alt+N', 'New design (saves the current one first)'],
        ['Ctrl+O', 'Open (images, PSD, PDF and .void files)'],
        ['Ctrl+Shift+P', 'Place image as layer'],
        ['Ctrl+S', 'Save to this device'],
        ['Ctrl+Alt+S', 'Save a version'],
        ['Ctrl+E', 'Export as'],
        ['Ctrl+Alt+W', 'Close the design'],
      ] },
      { t: 'p', text: 'New and Close use Ctrl+Alt because browsers keep Ctrl+N and Ctrl+W for their own windows and tabs.' },

      { t: 'h', text: 'Edit' },
      { t: 'keys', rows: [
        ['Ctrl+Z', 'Undo'],
        ['Ctrl+Shift+Z', 'Redo'],
        ['Ctrl+Y', 'Redo (alternative)'],
        ['Ctrl+X', 'Cut'],
        ['Ctrl+C', 'Copy the selected layer (inside the selection, if there is one)'],
        ['Ctrl+Shift+C', 'Copy merged: everything visible'],
        ['Ctrl+V', 'Paste, including images copied from other apps'],
        ['Ctrl+Shift+V', 'Paste in place: same position it was copied from'],
        ['Shift+F5', 'Fill'],
        ['Ctrl+T', 'Free transform'],
        ['Ctrl+,', 'Preferences'],
      ] },

      { t: 'h', text: 'Image' },
      { t: 'keys', rows: [
        ['Ctrl+Alt+I', 'Image size'],
        ['Ctrl+Alt+C', 'Canvas size'],
      ] },
      { t: 'p', text: 'Adjustments, rotation, crop, trim and flatten live in the Image menu without shortcuts. Find any of them fast with {{Ctrl+K}}.' },

      { t: 'h', text: 'Layer' },
      { t: 'keys', rows: [
        ['Ctrl+Shift+N', 'New layer'],
        ['Ctrl+J', 'Duplicate layer. With a selection active, copies the selected pixels to a new layer instead'],
        ['Delete', 'Delete layer. With a selection active, clears the selected pixels instead'],
        ['Ctrl+G', 'Group layers'],
        ['Ctrl+Shift+G', 'Ungroup'],
        ['Ctrl+Alt+G', 'Create clipping mask (press again to release it)'],
        ['Ctrl+Shift+]', 'Bring to front'],
        ['Ctrl+]', 'Bring forward'],
        ['Ctrl+[', 'Send backward'],
        ['Ctrl+Shift+[', 'Send to back'],
        ['Ctrl+Shift+E', 'Merge visible'],
        ['Ctrl+Alt+Shift+E', 'Stamp visible to new layer'],
      ] },

      { t: 'h', text: 'Select' },
      { t: 'keys', rows: [
        ['Ctrl+A', 'Select all'],
        ['Ctrl+D', 'Deselect'],
        ['Ctrl+Shift+D', 'Reselect the last selection'],
        ['Ctrl+Shift+I', 'Inverse'],
        ['Ctrl+Alt+R', 'Select and mask'],
        ['Shift+F6', 'Feather'],
        ['Ctrl+Enter', 'Load path as selection'],
        ['Q', 'Quick mask mode on or off'],
      ] },

      { t: 'h', text: 'View' },
      { t: 'keys', rows: [
        ['Ctrl++', 'Zoom in (Ctrl+= works too)'],
        ['Ctrl+-', 'Zoom out'],
        ['Ctrl+0', 'Fit on screen'],
        ['Ctrl+1', '100%'],
        ['Shift+1', 'Fit board'],
        ['Shift+2', 'Fit selected layers'],
        ['Ctrl+R', 'Rulers on or off'],
        ['Ctrl+;', 'Guides on or off'],
        ['Ctrl+Alt+;', 'Lock guides'],
        ['Ctrl+Shift+;', 'Snap on or off'],
        ['\\ (hold)', 'Before and after: shows the design without adjustments while held'],
        ['Ctrl+2', 'View the composite (all channels)'],
        ['Ctrl+3', 'View the red channel'],
        ['Ctrl+4', 'View the green channel'],
        ['Ctrl+5', 'View the blue channel'],
      ] },

      { t: 'h', text: 'Help' },
      { t: 'keys', rows: [
        ['Ctrl+K', 'Search every action (command palette)'],
        ['?', 'Keyboard shortcuts sheet'],
      ] },

      { t: 'h', text: 'Tools' },
      { t: 'p', text: 'Each tool has a single-letter key, the same as Photoshop. Tools that share a slot on the tool rail form a family: press Shift with the key to move through the family. From another tool, Shift plus the key jumps to the second tool in the family; press it again to keep cycling.' },
      { t: 'keys', rows: [
        ['V', 'Move and resize'],
        ['M', 'Rectangle select'],
        ['Shift+M', 'Ellipse select'],
        ['L', 'Lasso'],
        ['Shift+L', 'Polygonal lasso'],
        ['W', 'Object select'],
        ['Shift+W', 'Magic wand'],
        ['C', 'Crop'],
        ['I', 'Eyedropper'],
        ['J', 'Spot heal'],
        ['Shift+J', 'Remove object'],
        ['B', 'Brush'],
        ['S', 'Clone stamp'],
        ['E', 'Eraser'],
        ['G', 'Gradient'],
        ['Shift+G', 'Paint bucket'],
        ['O', 'Dodge (lighten)'],
        ['Shift+O', 'Burn (darken), then Sponge (saturation)'],
        ['P', 'Pen'],
        ['Shift+P', 'Curvature pen, then Freeform pen, then Direct select'],
        ['A', 'Direct select (edit paths)'],
        ['T', 'Type'],
        ['U', 'Shape'],
        ['H', 'Hand'],
        ['Z', 'Zoom'],
      ] },
      { t: 'tip', text: 'Right-click a tool slot on the rail, or press and hold it, to see the whole family with each key listed.' },

      { t: 'h', text: 'Quick keys on the canvas' },
      { t: 'p', text: 'These single keys work whenever the canvas has focus and no dialog is open.' },
      { t: 'keys', rows: [
        ['[ and ]', 'Brush size down and up (Brush, Eraser, Clone stamp, Spot heal, Remove object, Dodge, Burn, Sponge). With other tools, moves the layer down or up one place'],
        ['1 to 9, 0', 'Opacity in steps of 10%: 1 is 10%, 5 is 50%, 0 is 100%. Sets the tool opacity for Brush, Eraser, Clone stamp, Paint bucket and Gradient, and the layer opacity with any other tool'],
        ['X', 'Swap main and second colour'],
        ['D', 'Reset colours to near black and white'],
        ['Arrow keys', 'Nudge selected layers 1 px'],
        ['Shift+Arrow keys', 'Nudge selected layers 10 px'],
        ['Enter', 'Edit the selected text layer, apply a crop, finish a polygonal lasso or a path'],
        ['Esc', 'Cancel, in this order: the crop, quick mask, the selection, mask editing, a single-channel view'],
        ['Delete or Backspace', 'Clear selected pixels, or delete the selected layers when nothing is selected'],
      ] },
      { t: 'note', text: 'Brush size steps by about 20% each press, so it changes quickly on big brushes and gently on small ones. The size stays between 1 and 1000 px.' },

      { t: 'h', text: 'Modifier keys while you drag' },
      { t: 'keys', rows: [
        ['Shift+drag (move)', 'Keep the move straight: horizontal or vertical only'],
        ['Alt+drag (move)', 'Move without snapping to guides and other layers'],
        ['Shift+click (move)', 'Add a layer to the selection, or take it out'],
        ['Ctrl+click (move)', 'Pick the layer under the pointer when Auto-select is off'],
        ['Shift+drag a corner handle', 'Resize freely. Corners keep proportions by default'],
        ['Shift+drag the rotate handle', 'Rotate in 15° steps'],
        ['Shift after you start dragging (marquee, ellipse, shape, crop)', 'Keep it square or circular. Shift held before you press adds to the selection instead'],
        ['Shift+drag (selection tools)', 'Add to the selection'],
        ['Alt+drag (selection tools)', 'Subtract from the selection'],
        ['Shift+Alt+drag (selection tools)', 'Intersect with the selection'],
        ['Alt+click (Eyedropper)', 'Pick the second colour instead of the main one'],
        ['Alt+click (Clone stamp)', 'Set the point to copy from'],
        ['Alt+click (Zoom)', 'Zoom out'],
        ['Shift+drag a corner (free transform)', 'Keep proportions'],
        ['Ctrl+drag a corner (free transform)', 'Move one corner on its own (distort)'],
        ['Enter or Esc (free transform)', 'Apply or cancel the transform'],
        ['Ctrl+drag a guide', 'Move a guide that sits over a layer'],
      ] },
      { t: 'p', text: 'Text layers always resize in proportion from a corner, so the type does not squash. Dragging the side handle of a paragraph box changes its width instead.' },

      { t: 'h', text: 'Pen and path editing' },
      { t: 'p', text: 'These follow the Photoshop and Illustrator conventions. See [Shapes, polygons, stars and the Pen tool](/learn/shapes-and-pen) for how paths work.' },
      { t: 'keys', rows: [
        ['Click', 'Corner point'],
        ['Drag', 'Curve point with handles'],
        ['Shift+click or drag', 'Keep the segment or handle at 45° steps'],
        ['Alt+drag a handle', 'Break the handle so each side moves on its own'],
        ['Alt+click a point', 'Switch it between corner and smooth'],
        ['Space while dragging', 'Move the point you are placing'],
        ['Ctrl (hold)', 'Direct select for as long as it is held'],
        ['Enter or Esc', 'Finish the path you are drawing'],
        ['Double-click (Curvature pen)', 'Place a corner, or switch a point between corner and curve'],
        ['Shift+click (Direct select)', 'Add a point to the selection, or take it out'],
        ['Alt+click an outline (Direct select)', 'Pick the whole part and drag it'],
        ['Ctrl+A (path tools)', 'Select every point on the path'],
        ['Arrow keys (path tools)', 'Nudge selected points 1 px, or 10 px with Shift'],
        ['Delete (path tools)', 'Delete the selected points'],
        ['Ctrl+drag a point (path tools)', 'Move it without snapping'],
      ] },

      { t: 'h', text: 'Moving around the canvas' },
      { t: 'keys', rows: [
        ['Space+drag', 'Pan'],
        ['Middle mouse button drag', 'Pan'],
        ['Mouse wheel or trackpad', 'Scroll the canvas'],
        ['Shift+wheel', 'Scroll sideways'],
        ['Ctrl+wheel', 'Zoom at the pointer (trackpad pinch works too)'],
        ['Double-click a text layer', 'Edit its text'],
      ] },

      { t: 'h', text: 'Editing text' },
      { t: 'keys', rows: [
        ['Enter', 'New line'],
        ['Ctrl+Enter', 'Finish editing'],
        ['Esc', 'Finish editing'],
        ['Enter or Esc (type on a path)', 'Finish editing. Text on a path stays on one line'],
      ] },

      { t: 'h', text: 'Menus, dialogs and the command palette' },
      { t: 'keys', rows: [
        ['Alt (press and release)', 'Open the menu bar'],
        ['Left and Right arrows', 'Move between menus'],
        ['Up and Down arrows', 'Move through menu items or palette results'],
        ['Right arrow or Enter', 'Open a submenu'],
        ['Left arrow', 'Close a submenu'],
        ['Enter', 'Run the highlighted command'],
        ['Esc', 'Close the menu, dialog, colour picker or palette'],
      ] },

      { t: 'h', text: 'Touch gestures' },
      { t: 'p', text: 'On a phone or tablet there is no keyboard, so the common shortcuts become gestures. More in [Designing on a phone](/learn/designing-on-a-phone).' },
      { t: 'keys', rows: [
        ['Two-finger tap', 'Undo'],
        ['Three-finger tap', 'Redo'],
        ['Pinch', 'Zoom'],
        ['Two-finger drag', 'Pan'],
        ['Double tap a text layer', 'Edit its text'],
        ['Press and hold a tool slot', 'Show the other tools in its family'],
      ] },
      { t: 'tip', text: 'View, Touch mode (bigger controls) makes buttons and handles larger on a tablet with a keyboard or a touch laptop.' },

      { t: 'h', text: 'Outside the Editor' },
      { t: 'h3', text: 'Effects' },
      { t: 'keys', rows: [
        ['Left and Right arrows', 'Move the compare slider between original and edited (with the slider focused)'],
        ['Home', 'Slider fully to one side'],
        ['End', 'Slider fully to the other side'],
        ['Shift+click Open in Editor', 'Send one flattened image instead of a live filter layer'],
      ] },
      { t: 'h3', text: 'Studio' },
      { t: 'keys', rows: [
        ['Right arrow or Space', 'Next direction when presenting directions'],
        ['Left arrow', 'Previous direction when presenting'],
        ['Esc', 'Stop presenting'],
        ['Delete or Backspace', 'Remove the selected items from a direction board'],
        ['Arrow keys, Page Up, Page Down', 'Previous and next page in the brand guideline preview'],
        ['Arrow keys (mockup corner focused)', 'Nudge a mockup corner. Hold Shift for bigger steps'],
      ] },
      { t: 'p', text: 'The HTML handoff file that the brand guideline builder exports also pages with the Left and Right arrow keys, so a client can click through it like a deck.' },

      { t: 'h', text: 'Good to know' },
      { t: 'list', items: [
        'If a shortcut does nothing, check that you are not typing in a field and that no dialog is open. Click an empty part of the canvas and try again.',
        'Some shortcuts need something to act on: Deselect needs a selection, Ungroup needs a layer in a group, Load path as selection needs a path.',
        'Ctrl+J and Delete change meaning when a selection is active. That matches Photoshop, but catches people out: press Ctrl+D first if you meant the whole layer.',
        'Number keys set opacity for every selected layer at once, and each press is one undo step.',
        'Coming from Photoshop? Tool keys, bracket keys, number keys, X, D, Q and the arrange shortcuts all behave the same way.',
      ] },
    ],
  },

  // ─── Size presets ─────────────────────────────────────────────────
  {
    slug: 'size-presets',
    title: 'Size presets: every format and its pixel size',
    summary: 'Every size preset in the Editor and Studio, with the exact pixel size, what it is for and how the print sizes relate to millimetres and dpi.',
    category: 'reference',
    level: 'Beginner',
    updated: '2026-09-25',
    related: ['resize-to-every-format', 'artboards', 'designing-for-social', 'designing-for-print'],
    keywords: 'canvas size dimensions pixels instagram size story size youtube thumbnail size a4 pixels a5 business card poster banner billboard aspect ratio formats presets',
    body: [
      { t: 'p', text: 'This page lists every size preset in Voidcanvas, with its pixel size and what it is for. Use it when you need to know exactly what you will get before you start, or when a client asks for a size and you want to match it to a preset.' },
      { t: 'p', text: 'The Editor has one list of presets, used on the start screen, in File, Resize for other formats, and in the Boards dialog. Studio has a longer list for the formats a job owes. Most sizes are the same in both; the differences are called out below.' },

      { t: 'h', text: 'Editor presets' },
      { t: 'p', text: 'These appear on the Editor start screen under "What are you making?", grouped as Social, Screen and Print.' },
      { t: 'h3', text: 'Social' },
      { t: 'table', head: ['Preset', 'Pixels', 'Shape', 'Use it for'], rows: [
        ['Instagram post', '1080 × 1350', '4:5 portrait', 'Feed posts. The tallest shape the feed shows, so it takes the most screen space'],
        ['Square post', '1080 × 1080', '1:1', 'Feed posts that also work as profile grids and on most other platforms'],
        ['Story or Reel cover', '1080 × 1920', '9:16 portrait', 'Full-screen phone formats: stories, reel and short-video covers, status posts'],
        ['YouTube thumbnail', '1280 × 720', '16:9', 'Video thumbnails. Read at small sizes, so keep the words few and large'],
        ['LinkedIn banner', '1584 × 396', '4:1', 'The banner behind a LinkedIn profile or page'],
        ['X header', '1500 × 500', '3:1', 'The header image on an X profile'],
      ] },
      { t: 'h3', text: 'Screen' },
      { t: 'table', head: ['Preset', 'Pixels', 'Shape', 'Use it for'], rows: [
        ['Presentation slide', '1920 × 1080', '16:9', 'Slides, screens and video frames at full HD'],
        ['Website hero', '2400 × 1200', '2:1', 'Wide banner images at the top of a web page. The extra width stays sharp on large, high-density screens'],
      ] },
      { t: 'h3', text: 'Print' },
      { t: 'table', head: ['Preset', 'Pixels', 'Printed size', 'Use it for'], rows: [
        ['A4 flyer', '2480 × 3508', '210 × 297 mm at 300 dpi', 'Flyers, posters and documents on A4'],
        ['A5 flyer', '1748 × 2480', '148 × 210 mm at 300 dpi', 'Handouts and leaflets, half of A4'],
        ['Poster 18 × 24 in', '5400 × 7200', '18 × 24 in at 300 dpi', 'Posters on a common US size'],
        ['Business card', '1050 × 600', '3.5 × 2 in at 300 dpi', 'Business cards'],
      ] },
      { t: 'p', text: 'If none of these fit, the start screen has a Custom size form. Width and height can each be anything from 16 to 8000 px.' },
      { t: 'try', label: 'Start a design', href: '/editor' },

      { t: 'h', text: 'Where the Editor presets appear' },
      { t: 'list', items: [
        '**Start screen**: pick a preset to open a blank design at that size, with a white background.',
        '**File, Resize for other formats**: tick the presets you need, then Download them as PNG in a ZIP, or Save as separate designs. Square post, Story or Reel cover and YouTube thumbnail are ticked to begin with, and the preset matching your current size is greyed out as Current size. See [Resize one design to every format](/learn/resize-to-every-format).',
        '**Boards dialog**: the first eight presets (all Social and Screen sizes) are one-click buttons for adding a board. The full list is there for making several boards at once from the active board. See [Boards](/learn/artboards).',
      ] },

      { t: 'h', text: 'Studio formats' },
      { t: 'p', text: 'In a Studio job, the Brief tab has a Formats panel. It suggests formats the brief mentions, and All sizes and custom opens the full list below. Each format you add becomes a board in the key visual design, and a file in the delivery package.' },
      { t: 'h3', text: 'Social' },
      { t: 'table', head: ['Format', 'Pixels', 'Shape', 'Use it for'], rows: [
        ['Instagram post', '1080 × 1350', '4:5', 'Feed posts'],
        ['Square post', '1080 × 1080', '1:1', 'Feed posts on any platform'],
        ['Story / Reel / Status', '1080 × 1920', '9:16', 'Full-screen phone formats'],
        ['X post', '1600 × 900', '16:9', 'Images in X posts'],
        ['Facebook cover', '1640 × 624', 'About 2.6:1', 'The cover image on a Facebook page or profile'],
        ['LinkedIn banner', '1584 × 396', '4:1', 'LinkedIn profile or page banner'],
        ['X header', '1500 × 500', '3:1', 'X profile header'],
        ['YouTube thumbnail', '1280 × 720', '16:9', 'Video thumbnails'],
        ['WhatsApp flyer', '1080 × 1350', '4:5', 'Flyers shared in chats and status, where portrait fills more of the screen'],
      ] },
      { t: 'h3', text: 'Screen' },
      { t: 'table', head: ['Format', 'Pixels', 'Shape', 'Use it for'], rows: [
        ['Presentation slide', '1920 × 1080', '16:9', 'Slides and screens'],
        ['Website hero', '2400 × 1200', '2:1', 'Web page banners'],
        ['Email header', '1200 × 600', '2:1', 'The image at the top of a newsletter or email'],
      ] },
      { t: 'h3', text: 'Print' },
      { t: 'table', head: ['Format', 'Pixels', 'Trim size', 'Resolution'], rows: [
        ['A4 flyer', '2480 × 3508', '210 × 297 mm', '300 dpi'],
        ['A5 flyer', '1748 × 2480', '148 × 210 mm', '300 dpi'],
        ['A3 poster', '3508 × 4961', '297 × 420 mm', '300 dpi'],
        ['Poster 18 × 24 in', '2700 × 3600', '457.2 × 609.6 mm', '150 dpi'],
        ['Business card', '1050 × 600', '89 × 51 mm', '300 dpi'],
        ['Roll-up banner 85 × 200 cm', '2008 × 4724', '850 × 2000 mm', '60 dpi'],
      ] },
      { t: 'h3', text: 'Outdoor' },
      { t: 'table', head: ['Format', 'Pixels', 'Shape', 'Use it for'], rows: [
        ['Billboard 48-sheet', '4800 × 2400', '2:1', 'Standard UK roadside billboards'],
        ['Billboard 40 × 20 ft', '4800 × 2400', '2:1', 'Large-format billboards measured in feet'],
        ['Lamp-post banner', '1200 × 3600', '1:3', 'Tall banners hung on lamp posts'],
      ] },
      { t: 'p', text: 'Studio shows print formats in millimetres in the Formats list, because that is what a printer will ask for. Under Custom size you can add any other width and height.' },

      { t: 'h', text: 'Brand guideline pages' },
      { t: 'p', text: 'The brand guideline builder in Studio lays its pages out in one of two shapes.' },
      { t: 'table', head: ['Layout', 'Page in pixels', 'Print PDF trim'], rows: [
        ['Deck', '1600 × 900', '297 × 167 mm, 16:9'],
        ['Document', '1240 × 1754', 'A4 portrait, 210 × 297 mm'],
      ] },
      { t: 'p', text: 'The print PDF re-renders each page at 300 dpi on that trim size, so the pixel size above only matters for the screen PDF and for opening the pages in the Editor. See [Every brand guideline export](/learn/brand-guideline-exports).' },

      { t: 'h', text: 'Working out print sizes' },
      { t: 'p', text: 'Pixels only become a physical size once you pick a resolution. To go from millimetres to pixels: divide by 25.4 to get inches, then multiply by the dpi. A4 is 210 mm wide: 210 ÷ 25.4 × 300 = 2480 px, which is where the A4 preset comes from.' },
      { t: 'table', head: ['Viewing distance', 'Resolution that looks sharp', 'Examples'], rows: [
        ['In the hand', '300 dpi', 'Flyers, cards, brochures'],
        ['Across a room', '150 dpi', 'Posters on a wall'],
        ['From several metres', '60 to 100 dpi', 'Roll-up banners, exhibition graphics'],
        ['From the road', 'Much lower', 'Billboards'],
      ] },
      { t: 'p', text: 'This is why the two poster presets differ: the Editor preset is 300 dpi for close viewing, the Studio format is 150 dpi, which is plenty on a wall and keeps the file a quarter of the size. More in [Image resolution explained](/learn/image-resolution-explained).' },

      { t: 'h', text: 'Good to know' },
      { t: 'list', items: [
        'Presets are only starting sizes. Change the size later with Image, Canvas size ({{Ctrl+Alt+C}}) or Image size ({{Ctrl+Alt+I}}).',
        'The Export dialog can save at 0.5×, 1×, 2× or 3× the design size, as long as the long side stays at 8192 px or less. A 1080 px post exported at 2× is 2160 px.',
        'When the Editor exports a PDF, it treats designs with a long side over 2000 px as print work at 300 dpi and sizes the page to match. Smaller designs get a 96 dpi page. That means a Business card from the Editor preset (1050 px wide) comes out as a large screen-sized page, not a 3.5 × 2 in card. For print-ready cards with bleed and crop marks, deliver them from a Studio job, which uses the trim size in millimetres.',
        'Platforms change their recommended sizes from time to time. The shapes above are the ones Voidcanvas uses; check the platform if an upload gets cropped.',
      ] },
      { t: 'warn', text: 'The Business card preset is the US size (3.5 × 2 in). The Studio format is 89 × 51 mm, which is close to it. A UK or EU card is usually 85 × 55 mm: use a custom size for that.' },
    ],
  },

  // ─── File formats ────────────────────────────────────────────────
  {
    slug: 'file-formats',
    title: 'File formats you can open and export',
    summary: 'Every file type Voidcanvas opens and saves, across the Editor, Effects, quick tools and Studio, and exactly what each one keeps.',
    category: 'reference',
    level: 'Intermediate',
    updated: '2026-09-25',
    related: ['import-psd-and-pdf', 'export-for-screen', 'export-for-print', 'brand-guideline-exports'],
    keywords: 'file types formats psd pdf png jpg jpeg webp gif avif svg bmp void ase css tailwind json tokens zip import export open save transparency layers',
    body: [
      { t: 'p', text: 'This page covers every format Voidcanvas can open and every format it can save, and what survives the trip. Check it before you send a file to a client or printer, or before you open a colleague’s PSD, so nothing is lost without you knowing.' },
      { t: 'p', text: 'Everything happens in your browser. Files you open are read on your device and files you export are made on your device; nothing is uploaded.' },

      { t: 'h', text: 'Opening files in the Editor' },
      { t: 'p', text: 'Use File, Open ({{Ctrl+O}}), drop files on the start screen or canvas, or paste an image with {{Ctrl+V}}. If no design is open, the first image sets the canvas size. If one is open, each image arrives as a new layer.' },
      { t: 'table', head: ['Format', 'What you get', 'What is kept'], rows: [
        ['PNG, JPG, WebP, GIF, AVIF and other images your browser can read', 'One pixel layer per file', 'Pixels and transparency. Images larger than 4096 px on the long side are scaled down to 4096 px. Animated GIFs open as a single frame'],
        ['SVG', 'One pixel layer', 'How it looks, drawn at its own size. The vector shapes are not editable'],
        ['PSD', 'A layered design', 'Layers, groups, masks, text, adjustments and layer styles, with a report of anything changed. Details below'],
        ['PDF', 'One pixel layer per page', 'How each page looks. Text and vectors become pixels'],
        ['.void and .void.png', 'Your full Voidcanvas project', 'Everything: layers, masks, text, groups, boards, guides, swatches'],
      ] },
      { t: 'tip', text: 'File, Place image as layer ({{Ctrl+Shift+P}}) accepts images only, and always adds them to the current design.' },

      { t: 'h3', text: 'PSD: what comes across' },
      { t: 'p', text: 'Photoshop files open as real layered designs. Anything that cannot be rebuilt exactly is kept as pixels and listed in a report when the file opens, so nothing changes silently. [Open a PSD or PDF](/learn/import-psd-and-pdf) walks through it.' },
      { t: 'table', head: ['Kept and editable', 'Kept, but changed', 'Left out'], rows: [
        ['Pixel layers, positions, opacity, fill and visibility', 'Text with mixed fonts, sizes or colours, warped text and text on a path: kept as pixels', 'Satin effect'],
        ['Groups, including nesting', 'Smart objects: kept as pixels', 'Pattern overlay effect'],
        ['Layer masks', 'Vector shapes and vector masks: kept as pixels', 'Group masks'],
        ['Simple text: font, size, colour, alignment, leading, tracking, paragraph boxes, underline, strikethrough, caps', 'Blend modes Voidcanvas does not have, such as Linear burn or Vivid light: shown as the nearest match', 'Black and white tint'],
        ['Adjustment layers: Brightness/contrast, Levels, Curves, Exposure, Vibrance, Hue/saturation, Colour balance, Black and white, Photo filter, Channel mixer, Invert, Posterize, Threshold, Gradient map', 'Adjustments clipped to one layer: now affect everything below', 'Any other adjustment type'],
        ['Layer styles: drop shadow, inner shadow, outer and inner glow, stroke, colour overlay, gradient overlay, bevel and emboss', 'Gradient or pattern strokes: solid colour. Gradient overlays with more than two colours: first and last colour only', ''],
        ['Clipping masks, locks, colour labels', '16 and 32-bit files: converted to 8-bit. CMYK and other colour modes: converted to RGB', ''],
        ['Artboards: become boards, with their background colour', '', ''],
      ] },
      { t: 'note', text: 'Fonts in a PSD are matched by name. If a font is not on your device or on Google Fonts, the Some fonts are missing dialog lets you pick a replacement or add the font file.' },

      { t: 'h3', text: 'PDF: what comes across' },
      { t: 'list', items: [
        'Each page becomes its own pixel layer, named Page 1, Page 2 and so on. The canvas takes the size of page 1.',
        'Only page 1 is visible when the file opens. Turn the other pages on in the Layers panel.',
        'Pages are drawn at 1× to 2× the PDF’s own size, aiming for about 1600 px wide, so an A4 page comes in at about 1190 px wide. That suits screen work. For large print artwork, go back to the original files if you can.',
        'Password-protected PDFs cannot be opened.',
      ] },

      { t: 'h3', text: 'Other files the Editor reads' },
      { t: 'table', head: ['Format', 'Where', 'What it does'], rows: [
        ['.cube', 'Image, Adjustments, Colour lookup (.cube LUT)', 'Adds a 3D colour lookup as an adjustment layer, for film looks and colour grades'],
        ['TTF, OTF, WOFF, WOFF2', 'Character panel, or the Some fonts are missing dialog', 'Adds a font from your device. It is saved inside each design that uses it, so the design still looks right on another device'],
        ['Images', 'Brand kit, Logos', 'Adds a logo you can place in any design'],
      ] },

      { t: 'h', text: 'Opening files in Effects, quick tools and Studio' },
      { t: 'table', head: ['Where', 'Accepts', 'Limits'], rows: [
        ['Effects', 'PNG, JPG, WebP, GIF, AVIF, BMP, SVG', 'Up to 25 MB per file'],
        ['Quick tools (Halftone, Dither, Glitch)', 'Any image your browser can read', ''],
        ['Studio references and review images', 'Any image your browser can read', ''],
        ['Studio brands and brand guideline logo', 'Images and SVG', 'An SVG logo is also offered as an SVG download in the HTML handoff'],
        ['Brand guideline fonts', 'WOFF2, WOFF, TTF, OTF', ''],
      ] },

      { t: 'h', text: 'Exporting from the Editor' },
      { t: 'p', text: 'File, Export as ({{Ctrl+E}}) opens the Export dialog. Pick a File type and a Size, then Download or Copy image.' },
      { t: 'table', head: ['File type', 'Transparency', 'Quality setting', 'Best for'], rows: [
        ['PNG', 'Yes', 'None, always lossless', 'Graphics, text, logos, anything with sharp edges or see-through parts'],
        ['JPG', 'No: see-through areas become white', '40 to 100%', 'Photos, when file size matters'],
        ['WebP', 'Yes', '40 to 100%', 'Websites: smaller than PNG and keeps transparency'],
        ['PDF', 'No: on white', '40 to 100%, never below 90% inside the PDF', 'Sending to clients and printers'],
      ] },
      { t: 'list', items: [
        '**Size** offers 0.5×, 1×, 2× and 3× the design size, with the pixel result shown on each button. Sizes that would pass 8192 px on the long side are hidden.',
        '**Leave out the background colour** appears for PNG and WebP when the design has a background colour. Tick it for a see-through background.',
        '**PDF** is one page holding the design as a high-quality JPG. Designs with a long side over 2000 px get a 300 dpi page size; smaller ones get 96 dpi. Text in the PDF cannot be selected or edited, and there is no bleed or crop marks. For print PDFs with bleed, see [Export for print](/learn/export-for-print).',
        '**Copy image** puts a PNG on your clipboard to paste into another app.',
        '**Each board as its own PNG (zip)** appears when the design has boards. Every board is saved at 2× as a separate PNG, zipped.',
        '**Save editable file (.void.png, previews as your design, keeps layers)** saves a PNG that looks like your design in any image viewer, with the whole editable project stored inside it. The preview picture is at most 1600 px on the long side; the layers inside are full size.',
        'Download also saves a version of the design, so you can go back to exactly what you sent.',
      ] },
      { t: 'try', label: 'Open the Editor', href: '/editor' },

      { t: 'h3', text: 'Other ways to save from the Editor' },
      { t: 'table', head: ['Command', 'Saves', 'Keeps'], rows: [
        ['File, Download project file (.void)', 'A .void file', 'The whole project in one self-contained file. Use it for backups and moving work between devices'],
        ['File, Resize for other formats', 'A ZIP of PNGs, one per format', 'Flattened pictures at each preset size'],
        ['Layer, Path, Export path as SVG', 'An .svg file', 'The current path as a vector, for Figma, Illustrator or code'],
        ['Layer, Path, Copy path as SVG', 'SVG on the clipboard', 'The same, ready to paste'],
        ['Edit, Copy merged ({{Ctrl+Shift+C}})', 'A PNG on the clipboard', 'Everything visible, or just the selected area'],
        ['Start screen, a design’s menu, Export PNG', 'A PNG', 'A saved design at full size, without opening it'],
      ] },

      { t: 'h', text: 'Exporting from Effects and quick tools' },
      { t: 'table', head: ['Where', 'Formats', 'Size and notes'], rows: [
        ['Effects', 'PNG, JPG, WebP', 'Rendered again at the photo’s own size, up to 8000 px on the long side. JPG and WebP at 95% quality'],
        ['Effects, Open in Editor', 'Live filter layer', 'The photo plus the effect as its own filter layer you can still tune, hide or mask. Shift-click to send one flattened image instead'],
        ['Quick tools, Download PNG', 'PNG', 'Full size, up to 8000 px on the long side'],
        ['Quick tools, Send to Layer Stack', 'Live filter layer', 'Opens in the Editor with the effect still adjustable'],
      ] },

      { t: 'h', text: 'Exporting from Studio' },
      { t: 'h3', text: 'Brand guideline builder' },
      { t: 'p', text: 'The Export tab of the brand guideline builder offers the following. [Every brand guideline export](/learn/brand-guideline-exports) explains when to use each.' },
      { t: 'table', head: ['Export', 'File', 'What it holds'], rows: [
        ['Screen PDF', '.pdf', 'One page per guideline page, for reading on screen and sending by email'],
        ['Print PDF', '.pdf', '300 dpi pages on a real trim size (A4 portrait for Document, 297 × 167 mm for Deck), 3 mm bleed, crop marks, trim and bleed boxes set for the printer'],
        ['HTML handoff', '.html', 'One file the client opens in a browser: pages with arrow-key navigation, logo downloads (full colour, reversed white and dark mono PNG, plus the original SVG when you supplied one) and click-to-copy colours. Fonts are embedded where possible so it works offline'],
        ['Editor', 'Opens in the Editor', 'Each page as a board, with real layers: text stays text, shapes stay shapes, the logo stays an image'],
        ['Tokens: CSS', '-tokens.css', 'Colours, type and spacing as CSS custom properties'],
        ['Tokens: Tailwind', 'tailwind.<name>.js', 'The same values as a Tailwind theme'],
        ['Tokens: JSON', '.tokens.json', 'The same values as JSON design tokens'],
        ['Download .ase', '.ase', 'Adobe Swatch Exchange, grouped by role. Opens in Illustrator, Photoshop and InDesign'],
      ] },
      { t: 'h3', text: 'Jobs' },
      { t: 'table', head: ['Tab', 'Export', 'File'], rows: [
        ['Directions', 'PDF', 'A PDF with one 1920 × 1080 sheet per direction'],
        ['Directions', 'WhatsApp images', 'A ZIP of 1080 × 1350 JPGs, one per direction'],
        ['Review', 'Review pack PDF', 'The version you are showing the client, as a PDF'],
        ['Review', 'WhatsApp images', 'JPGs of the version, one per image (a ZIP when there are several)'],
        ['Review, Mockups', 'Download mockup', 'A JPG of the design placed in the mockup scene'],
        ['Deliver', 'Build the package', 'A ZIP with every format rendered at full size, a delivery note (HTML) and, if you choose, a brand sheet (HTML)'],
      ] },
      { t: 'p', text: 'In the delivery package you choose PNG, JPG, WebP or Print PDF for each format. Print and Outdoor formats start with Print PDF and JPG ticked; the rest start with PNG and JPG. Print PDFs get a 3 mm bleed made by extending the edges, crop marks, and a slug line with the trim size. Files are named client_job_format_v1 and so on, so the client can sort them.' },

      { t: 'h', text: 'Which format keeps what' },
      { t: 'table', head: ['Format', 'Layers', 'Editable text', 'Transparency', 'Vectors'], rows: [
        ['.void / .void.png', 'Yes', 'Yes', 'Yes', 'Paths and shapes stay editable'],
        ['PNG', 'No', 'No', 'Yes', 'No'],
        ['WebP', 'No', 'No', 'Yes', 'No'],
        ['JPG', 'No', 'No', 'No', 'No'],
        ['PDF (any)', 'No', 'No', 'No', 'No, pages are images'],
        ['SVG (path export)', 'No', 'No', 'Yes', 'Yes, one path'],
        ['HTML handoff', 'No', 'Colours and tokens can be copied', 'Logo PNGs yes', 'Only the original SVG logo'],
      ] },

      { t: 'h', text: 'Good to know' },
      { t: 'list', items: [
        'All exports are RGB. Voidcanvas does not write CMYK. Print PDFs say so on the slug line: ask your printer to convert with their profile. More in [Designing for print](/learn/designing-for-print).',
        'Voidcanvas opens PSD files but cannot save them. To hand editable work to someone else using Voidcanvas, send a .void or .void.png file.',
        'A .void.png looks like an ordinary PNG. If someone opens it in another app and saves over it, the project inside may be lost. Keep a copy.',
        'Photos over 4096 px on the long side are scaled down when you open them in the Editor. If you need the full resolution for print, check the size in Image size after opening.',
        'If an export fails on a very large design, pick a smaller Size. Browsers have a limit on how big a single image can be.',
        'Some formats depend on your browser. If a photo from your phone will not open, export it as JPG or PNG from the phone first.',
      ] },
    ],
  },

  // ─── Glossary ────────────────────────────────────────────────────
  {
    slug: 'glossary',
    title: 'Glossary of design and Voidcanvas terms',
    summary: 'Plain-English definitions of the design terms and product names used across Voidcanvas, from adjustment layer to workspace.',
    category: 'reference',
    level: 'Beginner',
    updated: '2026-09-25',
    related: ['editor-tour', 'layers', 'masks', 'blend-modes-and-opacity'],
    keywords: 'glossary definitions terms meaning what is dictionary jargon design vocabulary explain',
    body: [
      { t: 'p', text: 'Short definitions of the words you will meet in Voidcanvas and in design generally. Use it when a menu item, a printer or a client uses a term you are not sure of. Terms in the product are spelled the way the menus spell them.' },

      { t: 'h3', text: 'A' },
      { t: 'list', items: [
        '**Adjustment layer**: a layer that changes the colour or tone of everything below it (Curves, Levels, Hue and saturation and so on) without touching the pixels. Hide it, change it or delete it at any time. See [Adjustment layers](/learn/adjustment-layers).',
        '**Anchor point**: a point on a path. Corner points make sharp turns; smooth points have handles that shape a curve.',
        '**Artboard**: see Board.',
        '**.ase**: Adobe Swatch Exchange, a small file of named colours that Adobe apps can load. The brand guideline builder exports one.',
        '**Aspect ratio**: the shape of a rectangle as width to height, such as 16:9 or 4:5. Two sizes with the same ratio scale into each other without cropping.',
      ] },

      { t: 'h3', text: 'B' },
      { t: 'list', items: [
        '**Bevel and emboss**: a layer style that adds a highlight and a shadow to the edges of a layer, so it looks raised.',
        '**Blend mode**: how a layer’s colours mix with the layers below. Multiply darkens, Screen lightens, Overlay adds contrast. See [Blend modes, opacity and fill](/learn/blend-modes-and-opacity).',
        '**Bleed**: extra artwork past the trim edge of a printed piece, usually 3 mm, so no white shows if the cut is slightly off.',
        '**Board**: a separate page inside one design, with its own size, like an artboard in other apps. Use boards to keep every format of a campaign side by side. See [Boards](/learn/artboards).',
        '**Brand kit**: your colours, fonts and logos saved in the Editor, ready in every design. See [Brand kit](/learn/brand-kit).',
        '**Brief**: what the client wants, in their words. In Studio, pasting the brief is the first step of a job.',
      ] },

      { t: 'h3', text: 'C' },
      { t: 'list', items: [
        '**Canvas size**: the size of the design area. Changing it adds or removes space around the artwork without scaling it. Compare Image size.',
        '**Channel**: one of the red, green and blue parts that make up every colour on screen. View them one at a time with {{Ctrl+3}}, {{Ctrl+4}} and {{Ctrl+5}}.',
        '**Clear space**: the empty margin a logo must keep around it, so nothing crowds it. Set in brand guidelines.',
        '**Clipping mask**: a layer that only shows where the layer below it has pixels. Put a photo above some text and clip it to fill the letters with the photo.',
        '**Clone stamp**: a brush that paints a copy of another part of the image. Alt+click to set where it copies from.',
        '**CMYK**: cyan, magenta, yellow and black, the inks most printers use. Screens use RGB. Voidcanvas works and exports in RGB; printers convert to CMYK.',
        '**Colour lookup (LUT)**: a file (.cube) that maps every colour to a new one. Used for film looks and consistent colour grades.',
        '**Command palette**: the search box that runs any action by name. Open it with {{Ctrl+K}}. See [Command palette and menus](/learn/command-palette-and-menus).',
        '**Contrast ratio**: how different two colours are in lightness, from 1:1 (identical) to 21:1 (black on white). WCAG 2.2 asks for at least 4.5:1 for body text.',
        '**Crop marks**: thin lines outside the page corners of a print PDF showing the printer where to cut.',
        '**Curves**: an adjustment that remaps tones with a curve you drag. Pull the middle up to brighten, make an S shape for more contrast.',
      ] },

      { t: 'h3', text: 'D' },
      { t: 'list', items: [
        '**Direct select**: the tool for moving individual points and handles on a path. Key {{A}}.',
        '**Direction**: in Studio, one creative route for a job: a name, colours, fonts and a board of references. You show the client directions before designing the key visual.',
        '**Dither**: a pattern of dots in a few colours that suggests more tones than it has. It gives the grainy, retro look of old screens and prints.',
        '**Dodge and burn**: tools that lighten (dodge) or darken (burn) where you paint, named after darkroom techniques.',
        '**dpi**: dots per inch. How many pixels are packed into each printed inch. 300 dpi is the usual target for print held in the hand.',
      ] },

      { t: 'h3', text: 'E' },
      { t: 'list', items: [
        '**Effects**: the Voidcanvas module for one-click image effects. Load a photo, pick an effect, tune it and download or send it to the Editor. See [Using Effects](/learn/effects-overview).',
        '**Eyedropper**: a tool that picks a colour from the canvas. Key {{I}}.',
      ] },

      { t: 'h3', text: 'F' },
      { t: 'list', items: [
        '**Feather**: a soft edge on a selection, so whatever you do inside it fades out gradually instead of stopping at a hard line.',
        '**Fill**: in the Layers panel, the opacity of a layer’s own pixels only, leaving its layer styles fully visible. Useful for outlined text with a see-through middle.',
        '**Filter layer**: an effect added as its own layer, so you can tune, hide or mask it later instead of changing the pixels for good.',
        '**Flatten**: merge every layer into one. Use it rarely: once flat, layers cannot be separated again.',
        '**Free transform**: resize, rotate and move a layer with handles. {{Ctrl+T}}.',
      ] },

      { t: 'h3', text: 'G' },
      { t: 'list', items: [
        '**Gradient map**: an adjustment that recolours an image by lightness, mapping darks to one colour and lights to another. Good for duotones.',
        '**Group**: layers kept together in a folder, so they move, hide and fade as one. {{Ctrl+G}}.',
        '**Guides**: lines you place on the canvas to line things up. They never appear in exports.',
      ] },

      { t: 'h3', text: 'H' },
      { t: 'list', items: [
        '**Halftone**: an image made of dots of different sizes, as in newspaper printing. Try it in the Halftone quick tool.',
        '**HTML handoff**: a single web page the brand guideline builder exports for a client, with every page, logo downloads and copyable colours.',
        '**History**: the list of steps you can undo, in the History panel. By default it keeps the last 100 steps; change that in Preferences. See [History and undo](/learn/history-and-undo).',
      ] },

      { t: 'h3', text: 'I' },
      { t: 'list', items: [
        '**Image size**: the pixel dimensions of the whole design. Changing it scales everything up or down (resampling). Compare Canvas size.',
        '**Inbox**: how Voidcanvas passes work between Effects, Studio, the quick tools and the Editor. The file is held in your browser for a moment and picked up when the Editor opens.',
        '**IndexedDB**: the storage built into your browser, where Voidcanvas keeps your designs. It stays on your device. See [Where your designs are saved](/learn/saving-and-your-files).',
      ] },

      { t: 'h3', text: 'J to K' },
      { t: 'list', items: [
        '**JPG**: a photo format with small files and no transparency. It loses a little detail each time it is saved.',
        '**Key visual**: the main design of a campaign, which every other format is adapted from. In a Studio job, the Key visual tab is where you design it and build the formats.',
      ] },

      { t: 'h3', text: 'L' },
      { t: 'list', items: [
        '**Layer**: one item in a design, stacked above or below the others: a photo, a piece of text, a shape or an adjustment. See [Layers](/learn/layers).',
        '**Layer mask**: a greyscale map on a layer that hides parts of it without erasing them. Black hides, white shows. See [Masks](/learn/masks).',
        '**Layer style**: an effect attached to a layer that updates when the layer changes, such as Drop shadow, Stroke or Outer glow. See [Layer styles](/learn/layer-styles).',
        '**Levels**: an adjustment that sets the darkest point, the lightest point and the midtones of an image.',
        '**Lock**: stops a layer from being changed or moved by accident.',
      ] },

      { t: 'h3', text: 'M' },
      { t: 'list', items: [
        '**Magic wand**: selects areas of similar colour with one click. Key {{Shift+W}}.',
        '**Marquee**: a rectangle or ellipse selection. Key {{M}}.',
        '**Master**: the board other formats were made from. Layer, Formats, Update formats from master carries changes from it to the linked formats.',
        '**Merge down**: combine a layer with the one below it into a single layer.',
        '**Mockup**: your design shown on a real object or scene, such as a poster on a wall, to help a client picture it.',
      ] },

      { t: 'h3', text: 'O' },
      { t: 'list', items: [
        '**Object select**: a tool that finds the edges of an object when you drag a box around it, on your device. Key {{W}}.',
        '**OKLCH**: a way of describing colour by lightness, chroma (colourfulness) and hue that matches how people see. Steps in OKLCH look even, so it makes good colour ramps.',
        '**Opacity**: how see-through a layer is, from 0% (invisible) to 100% (solid). Number keys set it in steps of 10%.',
      ] },

      { t: 'h3', text: 'P' },
      { t: 'list', items: [
        '**Path**: a line or outline made of anchor points and curves, drawn with the Pen. Paths stay sharp at any size.',
        '**Pathfinder**: commands that combine shapes: Unite, Minus front, Minus back, Intersect, Exclude, Divide.',
        '**Pixel**: the smallest square of colour in an image. Screens and photos are grids of pixels.',
        '**PNG**: a lossless image format that keeps transparency. Best for graphics, text and logos.',
        '**Posterize**: an adjustment that cuts an image down to a few tones per channel, for a flat, poster-like look.',
        '**Private session**: a mode for shared or public computers. Nothing is written to the device, and everything clears when you close the tab. See [Private session](/learn/private-session).',
      ] },

      { t: 'h3', text: 'Q to R' },
      { t: 'list', items: [
        '**Quick mask**: a way to paint a selection with a brush, shown as a red overlay. Press {{Q}} to go in and out.',
        '**Rasterize**: turn text or a shape into pixels. You can paint on it after, but can no longer edit the words or the outline.',
        '**Resample**: change the number of pixels in an image. Making an image bigger this way cannot add real detail, so it looks soft.',
        '**Review pack**: in Studio, a PDF of the version you are showing the client.',
        '**RGB**: red, green and blue light, the way screens make colour. See also CMYK.',
      ] },

      { t: 'h3', text: 'S' },
      { t: 'list', items: [
        '**Select and mask**: a dialog for refining a selection edge, such as hair or fur. {{Ctrl+Alt+R}}.',
        '**Selection**: the area that painting, filters and copying affect, shown with a moving dotted line. See [Selections](/learn/selections).',
        '**Smart object**: a Photoshop layer that holds another file inside it. Voidcanvas opens these as pixels.',
        '**Snap**: makes layers jump into line with guides, the canvas and other layers as you drag. Toggle with {{Ctrl+Shift+;}}, or hold Alt while dragging.',
        '**Stamp visible**: copy everything you can see into one new layer, keeping the layers underneath. {{Ctrl+Alt+Shift+E}}.',
        '**Studio**: the Voidcanvas module for client work: jobs, briefs, references, directions, review, delivery and brand guidelines. See [Studio overview](/learn/studio-overview).',
        '**Swatch**: a saved colour, ready to reuse. See [Colour and swatches](/learn/colour-and-swatches).',
      ] },

      { t: 'h3', text: 'T' },
      { t: 'list', items: [
        '**Template**: a design saved to start new ones from. Opening a template makes a fresh copy, so the template never changes. See [Templates and versions](/learn/templates-and-versions).',
        '**Tokens**: design decisions (colours, type sizes, spacing) written as named values developers can use, in CSS, Tailwind or JSON.',
        '**Tracking**: the space between all the letters in a line of text. Loosen it for small capitals, tighten it for large headlines.',
        '**Trim**: the final size of a printed piece after cutting. Bleed sits outside the trim; important content sits well inside it.',
        '**Type on path**: text that follows the line of a path, such as around a circle.',
      ] },

      { t: 'h3', text: 'V' },
      { t: 'list', items: [
        '**Vector mask**: a mask made from a path instead of pixels, so its edge stays crisp at any size.',
        '**Version**: a saved snapshot of a design you can go back to. Save one with {{Ctrl+Alt+S}}; find them in File, Version history.',
        '**.void file**: the Voidcanvas project format. It holds the whole design, layers and all, in one file. A .void.png also shows as a picture in any image viewer.',
      ] },

      { t: 'h3', text: 'W' },
      { t: 'list', items: [
        '**WCAG**: the Web Content Accessibility Guidelines, which set the contrast ratios text needs to be readable. Voidcanvas checks against WCAG 2.2.',
        '**WebP**: an image format for websites with smaller files than PNG, which still keeps transparency.',
        '**Workspace**: the arrangement of panels in the Editor. Switch or save one in Window, Workspace. See [Workspaces and panels](/learn/workspaces-and-panels).',
      ] },
    ],
  },
]
