// Signposts: the search and routing metadata for existing guides, kept in one file so it can be reviewed against the
// research without touching prose. Merged over each article in index.ts. New guides carry these fields themselves.
//
//   answers  the questions and searches the guide answers, in the words people type (from research/learn-seo)
//   goals    goal ids from goals.ts
//   feature  the product feature it leans on, shown on search cards
//   role     cornerstone pages carry a cluster; supporting pages answer one question inside it
//   guide    contextual links: before (read first), next (natural next step), also (branches)
//   seoTitle a shorter or query-shaped <title> when the display title runs long

import type { Article } from '../types'

type Signpost = Pick<Article, 'answers' | 'goals' | 'feature' | 'role' | 'guide' | 'seoTitle' | 'description'>

export const SIGNPOSTS: Record<string, Signpost> = {
  // ── Start ────────────────────────────────────────────────────────
  'what-is-voidcanvas': { answers: ['what is voidcanvas', 'is voidcanvas free', 'what can voidcanvas do', 'voidcanvas vs canva', 'browser based design tool'], goals: ['learn-design', 'leave-photoshop'], feature: 'Editor, Studio, Effects', role: 'supporting', seoTitle: 'What Voidcanvas is', guide: { next: ['your-first-design'], also: [{ when: 'you are coming from Photoshop', slug: 'editor-tour' }, { when: 'you want to know what is sent', slug: 'privacy-and-data' }, { when: 'a term is new to you', slug: 'glossary' }] } },
  'your-first-design': { answers: ['how to make a design online', 'design something in five minutes', 'first design tutorial', 'how to start a design'], goals: ['learn-design'], feature: 'Editor', role: 'supporting', guide: { next: ['layers', 'type'], also: [{ when: 'you want to save it properly', slug: 'saving-and-your-files' }] } },
  'saving-and-your-files': { answers: ['where are my designs saved', 'does voidcanvas save automatically', 'how to back up designs', 'my design disappeared', 'clear browser data lose designs'], goals: ['private-and-offline'], feature: 'Editor · Files', role: 'supporting', seoTitle: 'Where your designs are saved', guide: { next: ['templates-and-versions'], also: [{ when: 'you use more than one computer', slug: 'account-and-sync' }, { when: 'you want a file on disk', slug: 'desktop-app' }] } },
  'desktop-app': { answers: ['voidcanvas desktop app', 'offline design app windows mac linux', 'design software that works offline'], goals: ['private-and-offline', 'work-faster'], feature: 'Desktop app', role: 'supporting', guide: { before: ['install-as-an-app'], next: ['saving-and-your-files'] } },
  'account-and-sync': { answers: ['do i need an account', 'sync settings between devices', 'sign in voidcanvas'], goals: ['private-and-offline'], feature: 'Accounts', role: 'supporting', seoTitle: 'Accounts and settings sync', guide: { before: ['privacy-and-data'], next: ['teams'] } },
  'teams': { answers: ['share designs with team', 'design collaboration browser', 'share brand kit with colleagues'], goals: ['client-project', 'build-a-brand'], feature: 'Teams', role: 'supporting', guide: { before: ['account-and-sync', 'brands-library'], next: ['review-and-delivery-links'] } },
  'moving-work-between-tools': { answers: ['send effect to editor', 'open in editor', 'how do studio and editor connect'], goals: ['design-effects', 'work-faster'], feature: 'Handoff', role: 'supporting', seoTitle: 'Move work between Effects, Studio and the Editor', guide: { next: ['effects-overview', 'studio-overview'] } },
  'install-as-an-app': { answers: ['install voidcanvas', 'use voidcanvas offline', 'add to home screen design app', 'pwa design tool'], goals: ['private-and-offline'], feature: 'Install', role: 'supporting', guide: { next: ['desktop-app'], also: [{ when: 'you design on a phone', slug: 'designing-on-a-phone' }] } },
  'designing-on-a-phone': { answers: ['design on a phone', 'graphic design on mobile', 'edit photos on ipad browser', 'can i graphic design on my phone'], goals: ['edit-a-photo', 'learn-design'], feature: 'Mobile Editor', role: 'supporting', guide: { before: ['editor-tour'], next: ['install-as-an-app'] } },

  // ── Editor core ──────────────────────────────────────────────────
  'editor-tour': { answers: ['where is everything in the editor', 'editor layout', 'photoshop layout equivalent', 'tool rail options bar dock'], goals: ['leave-photoshop', 'learn-design'], feature: 'Editor', role: 'cornerstone', guide: { next: ['layers', 'keyboard-shortcuts'], also: [{ when: 'you are on a phone', slug: 'designing-on-a-phone' }] } },
  'layers': { answers: ['how do layers work', 'what is a layer', 'rename lock hide layers', 'merge layers', 'layer order'], goals: ['leave-photoshop', 'work-with-psd', 'learn-design'], feature: 'Editor · Layers', role: 'cornerstone', guide: { next: ['groups-align-guides', 'masks'], also: [{ when: 'you opened a PSD', slug: 'import-psd-and-pdf' }] } },
  'groups-align-guides': { answers: ['align layers', 'distribute evenly', 'smart guides', 'snap to grid', 'group layers'], goals: ['learn-design', 'work-faster'], feature: 'Editor · Align', role: 'supporting', guide: { before: ['layers'], next: ['layout-and-composition'] } },
  'masks': { answers: ['what is a layer mask', 'how to use a layer mask', 'photoshop masks equivalent', 'clipping mask', 'can i clipping mask in canva', 'clipping mask online', 'clip image to text', 'hide part of a layer without deleting', 'mask from selection', 'quick mask'], goals: ['leave-photoshop', 'work-with-psd', 'edit-a-photo'], feature: 'Editor · Masks', role: 'cornerstone', guide: { before: ['layers', 'selections'], next: ['adjustment-layers'], also: [{ when: 'you want a clean cutout', slug: 'remove-background' }] } },
  'blend-modes-and-opacity': { answers: ['what do blend modes do', 'multiply screen overlay explained', 'opacity vs fill', 'blend modes list', 'can i change blend mode in canva', 'how to blend modes in canva', 'multiply blend mode'], goals: ['design-effects', 'leave-photoshop'], feature: 'Editor · Blend modes', role: 'supporting', guide: { before: ['layers'], next: ['layer-styles', 'workflow-textured-print-look'] } },
  'selections': { answers: ['how to select part of an image', 'magic wand', 'lasso', 'feather selection', 'select subject'], goals: ['edit-a-photo', 'leave-photoshop'], feature: 'Editor · Selections', role: 'supporting', guide: { next: ['masks', 'remove-background'] } },
  'type': { answers: ['how to add text to an image', 'change font', 'use my own font', 'text outline shadow', 'paragraph text box'], goals: ['make-a-poster', 'social-content', 'learn-design'], feature: 'Editor · Type', role: 'cornerstone', guide: { next: ['typography-fundamentals'], also: [{ when: 'the font is missing from a PSD', slug: 'import-psd-and-pdf' }] } },
  'shapes-and-pen': { answers: ['draw a shape', 'pen tool', 'vector paths in an image editor', 'draw a star polygon'], goals: ['learn-design'], feature: 'Editor · Shapes and Pen', role: 'supporting', guide: { next: ['layer-styles'] } },
  'brand-kit': { answers: ['what is a brand kit', 'what to include in a brand kit', 'save brand colours and fonts', 'keep designs on brand'], goals: ['build-a-brand', 'social-content', 'work-faster'], feature: 'Editor · Brand kit', role: 'supporting', guide: { before: ['building-a-brand-identity'], next: ['brands-library'] } },
  'colour-and-swatches': { answers: ['colour picker', 'eyedropper', 'save swatches', 'gradient fill', 'hex code'], goals: ['learn-design'], feature: 'Editor · Colour', role: 'supporting', guide: { next: ['colour-that-works'] } },

  // ── Editor image ────────────────────────────────────────────────
  'adjustment-layers': { answers: ['what is an adjustment layer', 'curves levels explained', 'fix exposure non destructively', 'hue saturation', 'black and white conversion', 'colour correction'], goals: ['edit-a-photo', 'leave-photoshop'], feature: 'Editor · Adjustment layers', role: 'cornerstone', seoTitle: 'Adjustment layers: colour and tone', guide: { before: ['layers'], next: ['masks', 'retouching'], also: [{ when: 'you want a one-click look', slug: 'effects-overview' }] } },
  'filters-in-the-editor': { answers: ['filters as layers', 'editable filter', 'stack filters', 'filter gallery', 'apply effect to one layer'], goals: ['design-effects'], feature: 'Editor · Filters', role: 'supporting', guide: { before: ['effects-overview'], next: ['masks'] } },
  'layer-styles': { answers: ['drop shadow', 'add a stroke around text', 'outer glow', 'layer styles', 'outline text'], goals: ['make-a-poster', 'social-content'], feature: 'Editor · Layer styles', role: 'supporting', seoTitle: 'Layer styles: shadows, strokes and glows', guide: { before: ['type'], next: ['blend-modes-and-opacity'] } },
  'retouching': { answers: ['how to retouch a photo', 'remove blemishes', 'heal tool', 'clone stamp', 'smooth skin without blur'], goals: ['edit-a-photo'], feature: 'Editor · Retouch', role: 'cornerstone', seoTitle: 'Retouch photos: brush, heal and clone', guide: { before: ['layers'], next: ['workflow-portrait-retouch'], also: [{ when: 'the colour is the problem', slug: 'adjustment-layers' }] } },
  'remove-background': { answers: ['how to remove a background from an image', 'remove background free', 'background remover without upload', 'transparent png', 'cut out a person', 'refine the edge of a cutout'], goals: ['edit-a-photo', 'private-and-offline'], feature: 'Editor · Remove background', role: 'cornerstone', guide: { next: ['masks', 'export-for-screen'], also: [{ when: 'the edge needs work', slug: 'selections' }, { when: 'you want to know what is sent', slug: 'ai-on-this-device' }] } },
  'crop-and-canvas': { answers: ['how to crop an image', 'resize an image without losing quality', 'canvas size vs image size', 'rotate straighten flip', 'change aspect ratio'], goals: ['edit-a-photo', 'prepare-for-print'], feature: 'Editor · Crop and canvas', role: 'supporting', guide: { next: ['image-resolution-explained'], also: [{ when: 'you are adding bleed', slug: 'export-for-print' }] } },
  'ai-on-this-device': { answers: ['ai tools that run locally', 'on device ai image editing', 'is my photo uploaded for ai', 'ai without cloud'], goals: ['private-and-offline', 'edit-a-photo'], feature: 'Editor · On-device AI', role: 'supporting', seoTitle: 'AI tools that run on your device', guide: { before: ['privacy-and-data'], next: ['remove-background'] } },

  // ── Editor output ───────────────────────────────────────────────
  'artboards': { answers: ['artboards in an image editor', 'multiple sizes in one file', 'boards'], goals: ['many-formats', 'social-content'], feature: 'Editor · Boards', role: 'supporting', guide: { next: ['resize-to-every-format'] } },
  'resize-to-every-format': { answers: ['resize one design to multiple sizes', 'resize for every social platform', 'batch resize a design', 'adapt a design to different formats', 'magic resize alternative', 'magic resize free alternative', 'can i resize images in canva', 'resize design to all sizes free'], goals: ['many-formats', 'social-content', 'work-faster'], feature: 'Editor · Resize to every format', role: 'cornerstone', guide: { before: ['designing-for-social'], next: ['workflow-social-campaign'], also: [{ when: 'you want them side by side', slug: 'artboards' }] } },
  'import-psd-and-pdf': { answers: ['open a psd file', 'what does psd import keep', 'open pdf as layers', 'missing fonts in a psd', 'smart objects', 'import formats'], goals: ['work-with-psd', 'leave-photoshop'], feature: 'Editor · Import', role: 'cornerstone', seoTitle: 'Open PSD and PDF files', guide: { before: ['edit-a-psd-without-photoshop'], next: ['layers', 'workflow-psd-to-social'], also: [{ when: 'you want the full format list', slug: 'file-formats' }] } },
  'export-for-screen': { answers: ['png or jpg', 'export transparent png', 'webp', 'export at 2x', 'copy image to clipboard', 'best format for web'], goals: ['edit-a-photo', 'social-content'], feature: 'Editor · Export', role: 'supporting', guide: { before: ['image-resolution-explained'], next: ['export-for-print'] } },
  'export-for-print': { answers: ['export pdf for print', 'add bleed in the editor', 'pdf page size wrong', 'print pdf 300 dpi', 'editor pdf export settings'], goals: ['prepare-for-print', 'make-a-poster'], feature: 'Editor · Export PDF', role: 'supporting', guide: { before: ['designing-for-print'], next: ['workflow-print-flyer'], also: [{ when: 'you are making a poster', slug: 'prepare-a-poster-for-print' }] } },
  'templates-and-versions': { answers: ['save a template', 'restore an older version', 'version history', 'reuse a layout'], goals: ['work-faster'], feature: 'Editor · Templates and versions', role: 'supporting', guide: { before: ['saving-and-your-files'], next: ['history-and-undo'] } },
  'history-and-undo': { answers: ['how many undos', 'history panel', 'before and after', 'undo not working'], goals: ['work-faster', 'learn-design'], feature: 'Editor · History', role: 'supporting', guide: { next: ['templates-and-versions'] } },
  'command-palette-and-menus': { answers: ['find a command', 'ctrl k', 'command palette', 'where is the menu', 'shortcut sheet'], goals: ['work-faster', 'leave-photoshop'], feature: 'Editor · Command palette', role: 'supporting', seoTitle: 'Find any action: menus and Ctrl+K', guide: { next: ['keyboard-shortcuts'] } },
  'workspaces-and-panels': { answers: ['move panels', 'reset workspace', 'floating panels', 'preferences'], goals: ['work-faster'], feature: 'Editor · Workspaces', role: 'supporting', guide: { before: ['editor-tour'] } },

  // ── Studio ──────────────────────────────────────────────────────
  'studio-overview': { answers: ['what is studio in voidcanvas', 'studio tabs', 'job status direction design review delivered', 'how a job moves through studio'], goals: ['client-project'], feature: 'Studio', role: 'cornerstone', seoTitle: 'Run a client job in Studio, brief to delivery', guide: { before: ['run-a-client-design-project'], next: ['start-a-job-from-a-brief'], also: [{ when: 'the job is a brand', slug: 'workflow-client-brand-guideline' }] } },
  'start-a-job-from-a-brief': { answers: ['what should a design brief include', 'design brief template', 'how to read a design brief', 'start a design job'], goals: ['client-project'], feature: 'Studio · Brief', role: 'supporting', guide: { before: ['studio-overview'], next: ['references-and-palettes', 'directions-and-review'] } },
  'references-and-palettes': { answers: ['mood board', 'reference board', 'extract colour palette from image', 'palette from photo'], goals: ['client-project', 'build-a-brand'], feature: 'Studio · References', role: 'supporting', seoTitle: 'References and palettes', guide: { next: ['directions-and-review'], also: [{ when: 'you are building the palette properly', slug: 'colour-that-works' }] } },
  'directions-and-review': { answers: ['how to present design options to a client', 'design review round', 'client feedback on design', 'design approval process'], goals: ['client-project'], feature: 'Studio · Review', role: 'supporting', guide: { next: ['review-and-delivery-links', 'delivering-files'] } },
  'review-and-delivery-links': { answers: ['share a design for client review', 'send design proof link', 'client download link'], goals: ['client-project'], feature: 'Studio · Share links', role: 'supporting', guide: { before: ['directions-and-review'], next: ['delivering-files'] } },
  'delivering-files': { answers: ['how to deliver design files to a client', 'file naming for designers', 'design delivery checklist', 'what files to send to the printer'], goals: ['client-project', 'prepare-for-print'], feature: 'Studio · Deliver', role: 'supporting', seoTitle: 'Deliver design files, named and print-ready', guide: { before: ['designing-for-print'], also: [{ when: 'the client needs a link', slug: 'review-and-delivery-links' }] } },
  'brands-library': { answers: ['save client brands', 'reuse brand across projects', 'brand library'], goals: ['build-a-brand', 'client-project'], feature: 'Studio · Brands', role: 'supporting', seoTitle: 'Save and reuse client brands', guide: { before: ['brand-guidelines'], next: ['brand-kit', 'teams'] } },
  'brand-guidelines': { answers: ['how to create brand guidelines', 'brand guideline builder', 'brand style guide online', 'colour ramps contrast type scale logo rules'], goals: ['build-a-brand', 'client-project'], feature: 'Studio · Brand guideline builder', role: 'cornerstone', seoTitle: 'Build a brand guideline', guide: { before: ['building-a-brand-identity'], next: ['brand-guideline-exports', 'keep-a-brand-consistent'], also: [{ when: 'you want the numbers behind type and colour', slug: 'typography-fundamentals' }] } },
  'brand-guideline-exports': { answers: ['export brand guidelines pdf', 'design tokens json', 'brand colours to css tailwind', 'ase swatches', 'handoff brand to developers'], goals: ['build-a-brand', 'client-project'], feature: 'Studio · Exports', role: 'supporting', seoTitle: 'Export a brand guideline', guide: { before: ['brand-guidelines'], next: ['delivering-files'] } },

  // ── Effects ─────────────────────────────────────────────────────
  'effects-overview': { answers: ['photo effects online free', 'one click photo effects', 'how to use effects', 'compare before and after effect'], goals: ['design-effects', 'edit-a-photo'], feature: 'Effects', role: 'cornerstone', guide: { next: ['make-a-halftone-portrait', 'filters-in-the-editor'] } },
  'artistic-effects': { answers: ['oil paint effect', 'watercolor effect', 'pencil sketch effect', 'photo to sketch', 'pop art effect', 'woodcut effect', 'halftone settings'], goals: ['design-effects'], feature: 'Effects · Artistic', role: 'supporting', guide: { before: ['effects-overview'], also: [{ when: 'you want the halftone explained', slug: 'make-a-halftone-portrait' }] } },
  'stylise-effects': { answers: ['pixelate effect', 'posterize', 'emboss', 'threshold', 'solarize', 'kaleidoscope', 'low poly effect'], goals: ['design-effects'], feature: 'Effects · Stylize', role: 'supporting', guide: { before: ['effects-overview'] } },
  'colour-effects': { answers: ['gradient map', 'sepia', 'invert colours', 'vintage photo effect', 'cyberpunk colour grade', 'colour effects list'], goals: ['design-effects', 'edit-a-photo'], feature: 'Effects · Color', role: 'supporting', guide: { before: ['effects-overview', 'make-a-duotone-image'], also: [{ when: 'you want precise control', slug: 'adjustment-layers' }] } },
  'distortion-effects': { answers: ['glitch effect', 'rgb shift', 'pixel sort', 'wave distortion', 'crt effect', 'fisheye', 'motion blur'], goals: ['design-effects'], feature: 'Effects · Distort', role: 'supporting', guide: { before: ['effects-overview'], also: [{ when: 'you only need glitch', slug: 'quick-tools' }] } },
  'texture-effects': { answers: ['film grain', 'add noise', 'vignette', 'scanlines', 'bloom', 'lens flare', 'film burn'], goals: ['design-effects'], feature: 'Effects · Enhance and texture', role: 'supporting', guide: { before: ['effects-overview'], next: ['workflow-textured-print-look'] } },
  'quick-tools': { answers: ['halftone generator', 'dither generator', 'glitch generator', 'halftone effect online free', 'free halftone image generator'], goals: ['design-effects'], feature: 'Quick tools', role: 'supporting', seoTitle: 'Halftone, Dither and Glitch quick tools', guide: { before: ['make-a-halftone-portrait'], next: ['effects-overview'], also: [{ when: 'you want dithering explained', slug: 'dither-effect-explained' }, { when: 'you want the glitch controls explained', slug: 'glitch-effect-explained' }] } },

  // ── Workflows ───────────────────────────────────────────────────
  'workflow-event-poster': { answers: ['how to make an event poster', 'gig poster from a photo', 'poster to print ready pdf'], goals: ['make-a-poster', 'prepare-for-print'], feature: 'Editor · Workflow', role: 'supporting', seoTitle: 'Make an event poster, photo to print-ready PDF', guide: { before: ['prepare-a-poster-for-print'], next: ['export-for-print'], also: [{ when: 'you want the halftone treatment', slug: 'make-a-halftone-portrait' }] } },
  'workflow-social-campaign': { answers: ['one post in every social format', 'social media campaign design', 'launch post sizes'], goals: ['social-content', 'many-formats'], feature: 'Editor · Workflow', role: 'supporting', guide: { before: ['designing-for-social'], next: ['resize-to-every-format'] } },
  'workflow-print-flyer': { answers: ['how to make an a5 flyer', 'flyer with bleed', 'a5 flyer size pixels', 'flyer for the printer'], goals: ['prepare-for-print'], feature: 'Studio · Workflow', role: 'supporting', guide: { before: ['designing-for-print'], next: ['delivering-files'] } },
  'workflow-client-brand-guideline': { answers: ['brand guideline for a client', 'brand identity project from logo to handoff'], goals: ['build-a-brand', 'client-project'], feature: 'Studio · Workflow', role: 'supporting', seoTitle: 'A client brand guideline, logo to handoff', guide: { before: ['building-a-brand-identity'], next: ['brand-guideline-exports'] } },
  'workflow-portrait-retouch': { answers: ['retouch a portrait', 'non destructive retouching', 'portrait retouch workflow'], goals: ['edit-a-photo'], feature: 'Editor · Workflow', role: 'supporting', guide: { before: ['retouching'], next: ['export-for-screen'] } },
  'workflow-psd-to-social': { answers: ['adapt a psd for social media', 'reuse a photoshop file', 'psd to instagram'], goals: ['work-with-psd', 'social-content'], feature: 'Editor · Workflow', role: 'supporting', guide: { before: ['edit-a-psd-without-photoshop'], next: ['resize-to-every-format'] } },
  'workflow-textured-print-look': { answers: ['risograph poster step by step', 'screen print look in the editor', 'textured print look workflow', 'riso poster with type in two inks'], goals: ['design-effects', 'make-a-poster'], feature: 'Effects and Editor · Workflow', role: 'supporting', seoTitle: 'Make a risograph or screen-print look, step by step', guide: { before: ['make-a-risograph-effect', 'make-a-halftone-portrait'], next: ['blend-modes-and-opacity'], also: [{ when: 'it is going to a printer', slug: 'designing-for-print' }] } },

  // ── Craft ───────────────────────────────────────────────────────
  'typography-fundamentals': { answers: ['typography basics', 'how to pair fonts', 'type scale', 'line height', 'how big should text be', 'letter spacing', 'typography for beginners'], goals: ['learn-design', 'make-a-poster', 'build-a-brand'], feature: 'Editor · Type', role: 'cornerstone', seoTitle: 'Typography fundamentals', guide: { next: ['layout-and-composition', 'type'], also: [{ when: 'you are setting a brand scale', slug: 'brand-guidelines' }] } },
  'colour-that-works': { answers: ['how to choose a colour palette', 'colour theory for designers', 'contrast ratio', 'accessible colours', 'colour on screen vs print', 'oklch'], goals: ['learn-design', 'build-a-brand', 'prepare-for-print'], feature: 'Studio · Colour', role: 'cornerstone', seoTitle: 'Colour that works on screen and in print', guide: { next: ['brand-guidelines'], also: [{ when: 'the job is going to print', slug: 'designing-for-print' }] } },
  'layout-and-composition': { answers: ['layout design principles', 'how to use a grid', 'visual hierarchy', 'white space', 'focal point', 'composition rules'], goals: ['learn-design', 'make-a-poster'], feature: 'Editor · Guides', role: 'cornerstone', seoTitle: 'Layout and composition', guide: { before: ['typography-fundamentals'], next: ['make-your-design-look-less-generic', 'groups-align-guides'] } },
  'image-resolution-explained': { answers: ['why does my image look blurry', 'what is dpi', 'dpi vs ppi', 'how to check image resolution', 'what resolution for printing', 'image too small to print', 'pixels vs dpi'], goals: ['prepare-for-print', 'learn-design', 'edit-a-photo'], feature: 'Editor · Image size', role: 'cornerstone', seoTitle: 'Image resolution explained: pixels, dpi and soft images', guide: { next: ['printed-design-looks-blurry', 'designing-for-print'], also: [{ when: 'you are making a poster', slug: 'prepare-a-poster-for-print' }, { when: 'the photo needs cropping or resizing', slug: 'crop-and-canvas' }] } },
  'designing-for-print': { answers: ['how to prepare artwork for print', 'what is bleed', 'safe area', 'rgb vs cmyk', 'crop marks', 'print ready checklist', 'paper weight gsm', 'trim bleed safe area'], goals: ['prepare-for-print', 'make-a-poster'], feature: 'Studio · Print PDF', role: 'cornerstone', seoTitle: 'Designing for print: bleed, dpi, CMYK and proofs', guide: { before: ['image-resolution-explained'], next: ['export-for-print', 'workflow-print-flyer'], also: [{ when: 'you are making a poster', slug: 'prepare-a-poster-for-print' }, { when: 'it is a client job', slug: 'delivering-files' }, { when: 'the printer uses a term you do not know', slug: 'glossary' }] } },
  'designing-for-social': { answers: ['social media design tips', 'instagram safe zone', 'text size for social posts', 'design a series of posts', 'story safe area'], goals: ['social-content', 'learn-design'], feature: 'Editor · Presets', role: 'cornerstone', guide: { next: ['resize-to-every-format', 'workflow-social-campaign'], also: [{ when: 'you need the sizes', slug: 'size-presets' }] } },
  'building-a-brand-identity': { answers: ['how to create a brand identity', 'brand identity checklist', 'brand identity for small business', 'brand identity process', 'logo colour type rules'], goals: ['build-a-brand', 'learn-design'], feature: 'Studio · Brand guideline builder', role: 'cornerstone', guide: { next: ['brand-guidelines', 'colour-that-works'], also: [{ when: 'it is a client job', slug: 'workflow-client-brand-guideline' }] } },

  // ── Reference ───────────────────────────────────────────────────
  'keyboard-shortcuts': { answers: ['keyboard shortcuts', 'photoshop shortcuts equivalent', 'shortcut list', 'hotkeys'], goals: ['work-faster', 'leave-photoshop'], feature: 'Editor', role: 'reference', guide: { next: ['command-palette-and-menus'] } },
  'size-presets': { answers: ['instagram post size', 'story size in pixels', 'a4 in pixels', 'a5 in pixels 300 dpi', 'poster size in pixels', 'business card size pixels', 'youtube thumbnail size', 'linkedin banner size'], goals: ['social-content', 'prepare-for-print', 'many-formats'], feature: 'Editor · Presets', role: 'reference', seoTitle: 'Size presets: every format in pixels', guide: { next: ['designing-for-social', 'designing-for-print'] } },
  'file-formats': { answers: ['png vs jpg vs webp', 'what file formats can i open', 'psd support', 'export formats', 'best format for print', 'svg support'], goals: ['work-with-psd', 'prepare-for-print'], feature: 'Editor · Import and export', role: 'reference', guide: { next: ['export-for-screen', 'export-for-print'] } },
  'glossary': { answers: ['design terms explained', 'what does bleed mean', 'what is a raster image', 'glossary of graphic design'], goals: ['learn-design'], feature: 'Reference', role: 'reference', guide: { next: ['typography-fundamentals'] } },

  // ── Help ────────────────────────────────────────────────────────
  'privacy-and-data': { answers: ['does voidcanvas upload my images', 'what data is sent', 'turn off analytics', 'anonymous usage counts', 'what voidcanvas sends'], goals: ['private-and-offline'], feature: 'Privacy', role: 'cornerstone', seoTitle: 'What Voidcanvas sends and what stays on your device', guide: { before: ['photo-editor-that-does-not-upload'], next: ['private-session', 'ai-on-this-device'] } },
  'private-session': { answers: ['private mode design app', 'shared computer', 'delete all my data'], goals: ['private-and-offline'], feature: 'Privacy', role: 'supporting', guide: { before: ['privacy-and-data'] } },
  'troubleshooting': { answers: ['fonts not loading', 'export failed', 'storage full', 'editor slow', 'big file will not open'], goals: [], feature: 'Help', role: 'supporting', seoTitle: 'Fix common problems', guide: { next: ['report-a-bug-well', 'browser-support'] } },
  'browser-support': { answers: ['which browsers work', 'webgpu', 'safari support', 'ai tools requirements'], goals: ['private-and-offline'], feature: 'Help', role: 'supporting', guide: { next: ['troubleshooting'] } },
  'report-a-bug-well': { answers: ['report a bug', 'how to write a bug report'], goals: [], feature: 'Help', role: 'supporting', guide: { before: ['troubleshooting'] } },
}
